### ISSUE TITLE
ImageCleaner.next_batch() and/or .render() broken in JupyterLab

### ISSUE THREAD

**Issue by amqdn** [fastai/fastai#1539] opened 2019-01-30 00:01 UTC
**Describe the bug**
Hello,
After successfully running notebooks in an instance running on GCP by following the [instructions](https://course.fast.ai/start_gcp.html), I cannot get the ImageCleaner widget to work properly. First issue: the widget does not even appear in JupyterLab unless I install the [ipywidgets JupyterLab extension](https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension); only the object is returned. Second, even after installing this extension, the "Next Batch" button does not work. The CSV is properly created and updated, but the next batch of images are not rendered. This leads me to believe that ImageCleaner.render() is broken. 

**Provide your installation details**
```
=== Software === 
python        : 3.7.1
fastai        : 1.0.42
fastprogress  : 0.1.18
torch         : 1.0.0
nvidia driver : 410.72
torch cuda    : 10.0.130 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 7611MB | Tesla P4

=== Environment === 
platform      : Linux-4.9.0-8-amd64-x86_64-with-debian-9.7
distro        : #1 SMP Debian 4.9.130-2 (2018-10-27)
conda env     : base
python        : /opt/anaconda3/bin/python
sys.path      : /home/jupyter/tutorials/fastai/course-v3/nbs/dl1
/opt/anaconda3/lib/python37.zip
/opt/anaconda3/lib/python3.7
/opt/anaconda3/lib/python3.7/lib-dynload

/opt/anaconda3/lib/python3.7/site-packages
/opt/anaconda3/lib/python3.7/site-packages/IPython/extensions
/home/jupyter/.ipython
```

**To Reproduce**
1. Create a new instance via GCP [instructions](https://course.fast.ai/start_gcp.html)
2. ```gcloud compute ssh --zone=$ZONE jupyter@$INSTANCE_NAME -- -L 8080:localhost:8080```
3. Point browser to localhost:8080
4. Open lesson2-download.ipynt
5. Run all cells as instructed in Lesson 2 (careful to create dirs and download images properly)
6. Attempt to instantiate ```ImageCleaner(ds, idxs, path)```; note that the current version of lesson2-download.ipynt is missing the necessary path argument
7. See that the output of the cell is merely the object
8. Install ipywidgets JupyterLab extension via ```jupyter labextension install @jupyter-widgets/jupyterlab-manager```
9. Refresh notebook browser window
10. Attempt to instantiate ```ImageCleaner(ds, idxs, path)``` again
11. See that the widget appears
12. Interact with the widget and click "Next Batch"
13. See that the next batch of images does not render, but that ```cleaned.csv``` is created

**Expected behavior**
The next batch of images should appear. 

Thanks.

**Comment by sgugger** [comment] 2019-01-30 14:16
Pining @fpingham on this.

**Comment by fpingham** [comment] 2019-02-08 20:43
Hi! Running the widget in Jupyter Lab is not currently supported. Can you run it on Jupyter Notebook (localhost:8080/tree)?

**Comment by amqdn** [comment] 2019-02-08 21:23
It turns out I can, yes! 

When I first encountered this problem, one of the things I wanted to try was to simply use Jupyter Notebook instead, but I couldn't figure out, even after searching around, how to open the regular notebook window given that navigating to localhost:8080 automatically redirected me to localhost:8080/lab? every time...

Well, it works! Thanks for the workaround!

**Comment by sgugger** [comment] 2019-02-09 14:02
Closing then.

**Closed by sgugger** 2019-02-09 14:02 UTC

**Comment by 3centsv** [comment] 2019-05-07 09:37
Hi I am trying to run ImageCleaner(ds, idxs, path) command in my notebook. I am using Colab platform to run this notebook. It just keeps running forever. I don't see any output. How do I make sure it is running in Jupyter Notebook and Jupyter Lab?

**Comment by sgugger** [comment] 2019-05-07 12:54
Widgets don't work in colab (it's not a jupyter notebook).

**Comment by 3centsv** [comment] 2019-05-08 07:45
Thanks Sylvain. I realised that after reading some of the comments. So I
manually deleted some of the images that were causing my loss function to
blow up. That worked.

Thanks for your response. Appreciate it!

**Comment by panaali** [comment] 2019-05-31 03:32
> Widgets don't work in colab (it's not a jupyter notebook).

Looks they work [now](https://colab.research.google.com/notebooks/widgets.ipynb).
also, `ipywidgets` are supported now. You can test run the [tutorials](https://colab.research.google.com/github/jupyter-widgets/ipywidgets/blob/master/docs/source/examples/Index.ipynb).

**Comment by deboiph** [comment] 2019-06-20 20:50
I just tested lessons2_download in Colab (JupyterLab) and I have the same problem as 3centsv so it seems the problem is not solved.

**Comment by sgugger** [comment] 2019-06-20 20:54
No it's not. Google doesn't support ipywidgets, it supports its own set of widgets which are different. `ImageCleaner` will continue to not work in colab and probably never will since they made the choice to design a new tool instead of using the one everyone else uses.

The issue is closed because there is nothing we can do about it on the fastai side.

**Comment by panaali** [comment] 2019-06-20 21:21
> No it's not. Google doesn't support ipywidgets, it supports its own set of widgets which are different. `ImageCleaner` will continue to not work in colab and probably never will since they made the choice to design a new tool instead of using the one everyone else uses.
> 
> The issue is closed because there is nothing we can do about it on the fastai side.

@sgugger could you look at [this](https://colab.research.google.com/github/jupyter-widgets/ipywidgets/blob/master/docs/source/examples/Using%20Interact.ipynb#scrollTo=ngbH-aW5wPnW) notebook? is this different than `ipywidgets` that fastai is using?

**Comment by sgugger** [comment] 2019-06-20 21:58
Oh, those are the normal widgets indeed. I was confused because in your first notebook I saw
```
from google.colab import widgets
```
so there clearly are some google colab-specific widgets.

In any case, if the `ImageCleaner` doesnt work in colab it's because they don't support all ipywidget widgets, there is no exterior magic in it (if you look at the source code, we only import from widgets and Layout). Maybe there is workaround but I have no time figuring it out. I suspect it's possible we have to import the widgets from google.colab instead of the one from ipywidget but 
1. it would require some ugly code in the library to make the switch
2. I don't know if it's the only thing to change

**Comment by Light--** [comment] 2019-06-26 02:51
I still got this problem and 3 other people too.. not caused by colab or jupyter lab, see link: https://forums.fast.ai/t/imagecleaner-doesnt-render/37152

**Comment by sgugger** [comment] 2019-06-26 12:50
The problem somehow lies in your installation of ipywidgets: fastai did create it properly from what you're telling me, but it's not showing for some reason. I'm no expert in ipywidgets, so apart from trying to reinstall it properly, I don't have any better advice :-/

**Comment by Light--** [comment] 2019-06-26 18:48
> The problem somehow lies in your installation of ipywidgets: fastai did create it properly from what you're telling me, but it's not showing for some reason. I'm no expert in ipywidgets, so apart from trying to reinstall it properly, I don't have any better advice :-/

Thanks very much! After hours of struggling(forgive me i'm a beginner :P ), finally i solved this problem(If the problem happens on mac or windows) by running these codes in the terminal:

```
pip install --upgrade --force-reinstall ipywidgets
# for windows cmd: pip install --upgrade --force-reinstall ipywidgets --user

pip install --upgrade --force-reinstall widgetsnbextension 
# for windows cmd: pip install --upgrade --force-reinstall widgetsnbextension --user

jupyter nbextension install --py widgetsnbextension
# for windows cmd: jupyter nbextension install --py widgetsnbextension --user

jupyter nbextension enable --py widgetsnbextension --sys-prefix
# for windows cmd: jupyter nbextension enable --py widgetsnbextension --sys-prefix --user

```

**Comment by sgugger** [comment] 2019-06-26 19:00
Glad you solved it and thanks for the detailed instructions! That'll help people :)
I'd suggest you copy them in the topic you mentioned on the forum for maximum visibility.

**Comment by Light--** [comment] 2019-06-26 19:14
> Glad you solved it and thanks for the detailed instructions! That'll help people :)
> I'd suggest you copy them in the topic you mentioned on the forum for maximum visibility.

ok, no problem.

**Comment by wjlgatech** [comment] 2019-06-29 03:10
> > The problem somehow lies in your installation of ipywidgets: fastai did create it properly from what you're telling me, but it's not showing for some reason. I'm no expert in ipywidgets, so apart from trying to reinstall it properly, I don't have any better advice :-/
> 
> Thanks very much! After hours of struggling(forgive me i'm a beginner :-p ), finally i solved this problem(If that happened on mac or windows) by running these codes in the terminal:
> 
> ```
> # for mac terminal, use the command below; for windows cmd, add '--user' to the end of each command.
> 
> ###  First, reinstall ipywidgets and widgetsnbextension 
> pip install --upgrade --force-reinstall ipywidgets
> 
> pip install --upgrade --force-reinstall widgetsnbextension 
> 
> ### Second, install jupyter-js-widgets/extension
> jupyter nbextension install --py widgetsnbextension
> 
> ### Third, enable  widgetsnbextension
> jupyter nbextension enable --py widgetsnbextension --sys-prefix
> ```
> 
> now, we can enjoy lesson2_download.ipynb again. Simply type `jupyter notebook` in the terminal and open it in the browser.

@Light : your solution works for jupyter notebook but NOT colab notebook, right? If it only works for jupyter notebook and (I assume that you use a local machine), where  do you use GPU? Thanks!

**Comment by Light--** [comment] 2019-06-30 13:46
> > > The problem somehow lies in your installation of ipywidgets: fastai did create it properly from what you're telling me, but it's not showing for some reason. I'm no expert in ipywidgets, so apart from trying to reinstall it properly, I don't have any better advice :-/
> > 
> > 
> > Thanks very much! After hours of struggling(forgive me i'm a beginner :-p ), finally i solved this problem(If that happened on mac or windows) by running these codes in the terminal:
> > ```
> > # for mac terminal, use the command below; for windows cmd, add '--user' to the end of each command.
> > 
> > ###  First, reinstall ipywidgets and widgetsnbextension 
> > pip install --upgrade --force-reinstall ipywidgets
> > 
> > pip install --upgrade --force-reinstall widgetsnbextension 
> > 
> > ### Second, install jupyter-js-widgets/extension
> > jupyter nbextension install --py widgetsnbextension
> > 
> > ### Third, enable  widgetsnbextension
> > jupyter nbextension enable --py widgetsnbextension --sys-prefix
> > ```
> > 
> > 
> > now, we can enjoy lesson2_download.ipynb again. Simply type `jupyter notebook` in the terminal and open it in the browser.
> 
> @light : your solution works for jupyter notebook but NOT colab notebook, right? If it only works for jupyter notebook and (I assume that you use a local machine), where do you use GPU? Thanks!

i assume colab would not have supported all widgets, please refer to what sgugger said. i use my local gpu by jupter notebook.

**Comment by nargroves** [comment] 2019-07-16 05:30
> > The problem somehow lies in your installation of ipywidgets: fastai did create it properly from what you're telling me, but it's not showing for some reason. I'm no expert in ipywidgets, so apart from trying to reinstall it properly, I don't have any better advice :-/
> 
> Thanks very much! After hours of struggling(forgive me i'm a beginner :-p ), finally i solved this problem(If that happened on mac or windows) by running these codes in the terminal:
> 
> ```
> # for mac terminal, use the command below; for windows cmd, add '--user' to the end of each command.
> 
> ###  First, reinstall ipywidgets and widgetsnbextension 
> pip install --upgrade --force-reinstall ipywidgets
> 
> pip install --upgrade --force-reinstall widgetsnbextension 
> 
> ### Second, install jupyter-js-widgets/extension
> jupyter nbextension install --py widgetsnbextension
> 
> ### Third, enable  widgetsnbextension
> jupyter nbextension enable --py widgetsnbextension --sys-prefix
> ```
> 
> now, we can enjoy lesson2_download.ipynb again. Simply type `jupyter notebook` in the terminal and open it in the browser.

In order to get this block of code to work for me I had to add --user after this command:
```
### Second, install jupyter-js-widgets/extension
jupyter nbextension install --py widgetsnbextension
```

Changing that line to: ` jupyter nbextension install --py widgetsnbextension --user` fixed it for me.

**Comment by Light--** [comment] 2019-07-16 07:54
> # for mac terminal, use the command below; for windows cmd, add '--user' to the end of each command.

yes, i have already mentioned above.
```
# for mac terminal, use the command below; for windows cmd, add '--user' to the end of each command.
```

**Comment by Light--** [comment] 2019-07-16 07:56
> > > The problem somehow lies in your installation of ipywidgets: fastai did create it properly from what you're telling me, but it's not showing for some reason. I'm no expert in ipywidgets, so apart from trying to reinstall it properly, I don't have any better advice :-/
> > 
> > 
> > Thanks very much! After hours of struggling(forgive me i'm a beginner :-p ), finally i solved this problem(If that happened on mac or windows) by running these codes in the terminal:
> > ```
> > # for mac terminal, use the command below; for windows cmd, add '--user' to the end of each command.
> > 
> > ###  First, reinstall ipywidgets and widgetsnbextension 
> > pip install --upgrade --force-reinstall ipywidgets
> > 
> > pip install --upgrade --force-reinstall widgetsnbextension 
> > 
> > ### Second, install jupyter-js-widgets/extension
> > jupyter nbextension install --py widgetsnbextension
> > 
> > ### Third, enable  widgetsnbextension
> > jupyter nbextension enable --py widgetsnbextension --sys-prefix
> > ```
> > 
> > 
> > now, we can enjoy lesson2_download.ipynb again. Simply type `jupyter notebook` in the terminal and open it in the browser.
> 
> In order to get this block of code to work for me I had to add --user after this command:
> 
> ```
> ### Second, install jupyter-js-widgets/extension
> jupyter nbextension install --py widgetsnbextension
> ```
> 
> Changing that line to: ` jupyter nbextension install --py widgetsnbextension --user` fixed it for me.



> > > The problem somehow lies in your installation of ipywidgets: fastai did create it properly from what you're telling me, but it's not showing for some reason. I'm no expert in ipywidgets, so apart from trying to reinstall it properly, I don't have any better advice :-/
> > 
> > 
> > Thanks very much! After hours of struggling(forgive me i'm a beginner :-p ), finally i solved this problem(If that happened on mac or windows) by running these codes in the terminal:
> > ```
> > # for mac terminal, use the command below; for windows cmd, add '--user' to the end of each command.
> > 
> > ###  First, reinstall ipywidgets and widgetsnbextension 
> > pip install --upgrade --force-reinstall ipywidgets
> > 
> > pip install --upgrade --force-reinstall widgetsnbextension 
> > 
> > ### Second, install jupyter-js-widgets/extension
> > jupyter nbextension install --py widgetsnbextension
> > 
> > ### Third, enable  widgetsnbextension
> > jupyter nbextension enable --py widgetsnbextension --sys-prefix
> > ```
> > 
> > 
> > now, we can enjoy lesson2_download.ipynb again. Simply type `jupyter notebook` in the terminal and open it in the browser.
> 
> In order to get this block of code to work for me I had to add --user after this command:
> 
> ```
> ### Second, install jupyter-js-widgets/extension
> jupyter nbextension install --py widgetsnbextension
> ```
> 
> Changing that line to: ` jupyter nbextension install --py widgetsnbextension --user` fixed it for me.

yes, i have already mentioned above.
```
# for mac terminal, use the command below; for windows cmd, add '--user' to the end of each command.
```

**Comment by petersolimine** [comment] 2020-01-10 20:45
> 
> 
> > The problem somehow lies in your installation of ipywidgets: fastai did create it properly from what you're telling me, but it's not showing for some reason. I'm no expert in ipywidgets, so apart from trying to reinstall it properly, I don't have any better advice :-/
> 
> Thanks very much! After hours of struggling(forgive me i'm a beginner :-p ), finally i solved this problem(If that happened on mac or windows) by running these codes in the terminal:
> 
> ```
> # for mac terminal, use the command below; for windows cmd, add '--user' to the end of each command.
> 
> ###  First, reinstall ipywidgets and widgetsnbextension 
> pip install --upgrade --force-reinstall ipywidgets
> 
> pip install --upgrade --force-reinstall widgetsnbextension 
> 
> ### Second, install jupyter-js-widgets/extension
> jupyter nbextension install --py widgetsnbextension
> 
> ### Third, enable  widgetsnbextension
> jupyter nbextension enable --py widgetsnbextension --sys-prefix
> ```
> 
> now, we can enjoy lesson2_download.ipynb again. Simply type `jupyter notebook` in the terminal and open it in the browser.

This still isn't working for me, I have the same output as you have listed in your original post. I'm on not using colab or lab (just a regular jupyter notebook, and I' on windows (used --user, everything worked smoothly on the terminal end) but still no changes. Any recommendations?
Thanks!

**Comment by yjkimjunior** [comment] 2020-04-04 09:12
this is what did it for me https://github.com/Calysto/matlab_kernel/issues/68#issuecomment-491128644

**Comment by nnnnicholas** [comment] 2020-04-07 02:34
> 
> 
> Oh, those are the normal widgets indeed. I was confused because in your first notebook I saw
> 
> ```
> from google.colab import widgets
> ```
> 
> so there clearly are some google colab-specific widgets.
> 
> In any case, if the `ImageCleaner` doesnt work in colab it's because they don't support all ipywidget widgets, there is no exterior magic in it (if you look at the source code, we only import from widgets and Layout). Maybe there is workaround but I have no time figuring it out. I suspect it's possible we have to import the widgets from google.colab instead of the one from ipywidget but
> 
>     1. it would require some ugly code in the library to make the switch
> 
>     2. I don't know if it's the only thing to change



> No it's not. Google doesn't support ipywidgets, it supports its own set of widgets which are different. `ImageCleaner` will continue to not work in colab and probably never will since they made the choice to design a new tool instead of using the one everyone else uses.
> 
> The issue is closed because there is nothing we can do about it on the fastai side.

Hi, I've just started fast.ai and I'm on part 1 v3 lesson 2: https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson2-download.ipynb

I'm just encountering this information that Google Colab is incompatible with parts of fast.ai's course, such as ImageCleaner. If I had known this earlier I would not have spent time getting used to Colab, which already seems to deviate from default Jupyter's normal key commands and UI. 

Perhaps you could remove it from the the list of suggested hosted platforms on fast.ai v3's intro page? It is listed as one of two free options. There is no mention of it being incompatible with parts of the course. 

Is there another hosted service that runs Jupyter Notebook rather than Lab? I don't have a nice GPU so I need a hosted option. Thanks for any advice.

**Comment by guixermo** [comment] 2020-05-04 09:34
> > In any case, if the `ImageCleaner` doesnt work in colab it's because they don't support all ipywidget widgets, there is no exterior magic in it (if you look at the source code, we only import from widgets and Layout). Maybe there is workaround but I have no time figuring it out. I suspect it's possible we have to import the widgets from google.colab instead of the one from ipywidget but
> > The issue is closed because there is nothing we can do about it on the fastai side.
> 
> Hi, I've just started fast.ai and I'm on part 1 v3 lesson 2: https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson2-download.ipynb
> 
> I'm just encountering this information that Google Colab is incompatible with parts of fast.ai's course, such as ImageCleaner. If I had known this earlier I would not have spent time getting used to Colab, which already seems to deviate from default Jupyter's normal key commands and UI.
> 
> Perhaps you could remove it from the the list of suggested hosted platforms on fast.ai v3's intro page, or at least add a warning? It is listed as one of two free options. There is no mention of it being incompatible with parts of the course.
> 
> Is there another hosted service that runs Jupyter Notebook rather than Lab? I don't have a nice GPU so I need a hosted option. Thanks for any advice.

I've just arrived to this part and i was working with colab too, so i'd need an alternative to google colab in case there is no way of cleaning datasets as well as further problems related to colab.

Thanks for any advice :)
