### ISSUE TITLE
Tokenizer Multiprocessing Hang

### ISSUE THREAD

**Issue by rothn** [fastai/fastai#2489] opened 2020-02-13 05:52 UTC
**Describe the bug**

FastAI's multiprocessing Tokenizer hangs when tokenizing a text corpus (982619 documents with an average length of just over 100 tokens, counted by my own single-process tokenizer.

**Provide your installation details**
```
=== Software ===
python       : 3.7.3
fastai       : 1.0.60
fastprogress : 0.2.2
torch        : 1.3.0
torch cuda   : 10.1.243 / is **Not available**

=== Hardware ===
No GPUs available

=== Environment ===
platform     : Linux-4.4.0-17763-Microsoft-x86_64-with-Ubuntu-18.04-bionic
distro       : #864-Microsoft Thu Nov 07 15:22:00 PST 2019
conda env    : Unknown
python       : /home/nroth/ml_python/bin/python
sys.path     : /home/nroth
/usr/lib/python37.zip
/usr/lib/python3.7
/usr/lib/python3.7/lib-dynload
/home/nroth/ml_python/lib/python3.7/site-packages
no supported gpus found on this system
```

I looked through the commits since the last release and none of them seemed relevant to this issue.

**To Reproduce**

1. Load a text corpus like my proprietary one (982619 documents with an average length of just over 100 tokens) in Ubuntu on Windows
2. Run `[Tokenizer(n_cpus=8).process_all(review_class) for review_class in reviews_by_class]`
3. Observe the hang

**Expected behavior**
This should not hang. It should complete eventually, ideally faster than a single-process tokenizer.

**Screenshots**
The tokenizer hangs...
![hung_tokenizer](https://user-images.githubusercontent.com/4665783/74405301-a0dc6480-4de1-11ea-85b6-ee488bfc7452.png)

The one active process appears merely to be waiting on workers...
![running_proc_stack](https://user-images.githubusercontent.com/4665783/74405423-e0a34c00-4de1-11ea-84d4-9a82abacb808.png)

**Additional context**
This was observed using Ubuntu on Windows, but I have a good reason for using it.

**Comment by rothn** [comment] 2020-02-13 06:03
The workaround for this seems to be batching the documents in groups of no larger than 100k, but it is an annoyance nonetheless.

**Comment by sgugger** [comment] 2020-02-13 14:57
As it is, it's a bit hard to know the cause of the bug and if it comes from fastai:
- it could be one bad sample 
- it could be Ubuntu on windows + multiprocessing in python
- it could be the fact you get our of RAM that triggers the error

For the last one, only v2 will support tokenizing from files without loading everything in memory. The second one can be tested by using anther env, and you'll know if it's the first one once the tokenization is over.

If you say batching texts by 100k samples is a workaround, I think it points toward the third one being the cause, in which case you should switch to v2.

Closing as I don't have a clear reproducer, but please reopen with more info if you have them.

**Closed by sgugger** 2020-02-13 14:57 UTC

**Comment by rothn** [comment] 2020-02-13 17:24
This used less than 30% of the system’s RAM at its peak

**Comment by rothn** [comment] 2020-02-13 17:26
I also looked for multiprocessing bugs in that configuration online and found no bug reports. I’ll try to make a synthetic dataset I can upload and reproduce it on my MBP, but that only has 16 GiB of RAM

**Comment by jd445** [comment] 2024-01-04 02:29
I also meet this bug....
