### ISSUE TITLE
Running TTA() in fp16 / half mode raises "RuntimeError: _th_cat is not implemented for type torch.HalfTensor" + work-around

### ISSUE THREAD

**Issue by cpbotha** [fastai/fastai#1203] opened 2018-11-17 20:47 UTC
**Describe the bug**

This is with fastai 1.0.24 and a fairly recent (a few days old) build of PyTorch master on CUDA 10.

After successfully training and being able to call `get_preds()` normally, invoking `learn.TTA()` raises the following exception:

```
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/cpbotha/Dropbox/work/code/kaggle/human-protein-atlas/exp_20181117_fastai_other_nets.py", line 176, in <module>
     vpreds, vtargs = learner.TTA()
    File "/home/cpbotha/miniconda3/envs/kag-protein/lib/python3.7/site-packages/fastai/vision/tta.py", line 35, in _TTA
     avg_preds = torch.stack(all_preds).mean(0)
RuntimeError: _th_cat is not implemented for type torch.HalfTensor
```

**To Reproduce**

Train any network in half precision mode, then try TTA().

**Expected behavior**

TTA should run without raising exceptions.

One can work around this issue by replacing this line in `tta.py`:

``` python
avg_preds = torch.stack(all_preds).mean(0)
```

with this:

``` python
avg_vpreds = torch.stack([p.float() for p in all_preds]).mean(0)
```
(It might be more compact to combine this float-converting list comprehension with the tta_only() generator invocation on the previous line, but I have not tested that. Let me know if I should make a PR.)

**Comment by sgugger** [comment] 2018-12-19 15:32
I'm not too fond on going back to FP32 behind the user. My fix for this is to leave the issue (TTA isn't working in FP16 because torch.stack isn't, which may very well change in the future) but offer the ability to quickly switch back to FP32 with a new `Leaner.to_fp32`  method.
So you should do:
``` 
learn.to_fp32()
preds, targs = learn.TTA()
```

**Closed by sgugger** 2018-12-19 15:32 UTC

**Comment by hokmund** [comment] 2019-10-17 12:24
I'd like to raise this issue again.
TTA can take some time (e.g. for me it takes 4 hours for current RSNA Kaggle competition), and it's a shame that issue raises only at the end of TTA process.

I guess, that the expected behavior is at least to check whether model is in fp16 and raise an exception at the beginning of the method.

Also, at the moment torch.stack works for fp16, and issue is with torch.mean. It can be handled in a couple of ways:
1) Convert tensors in all_preds to FP32 (we can even convert it back to FP16 later)
2) Use safe FP16 mean implementation (e.g. like this one: https://github.com/pytorch/pytorch/issues/12115)

@sgugger could you please check this issue? If you think that one of the solutions I mentioned is reasonable, I am willing to implement it into PR since current behavior can be a bit irritating for users.

**Comment by sgugger** [comment] 2019-10-17 13:48
Mixed precision isn't meant to be used outside of training. I can add a defensive test at the beginning of TTA so that the error comes immediately (good practice is to always try thing on a sample first to avoid bad surprises :) )

**Comment by hokmund** [comment] 2019-10-17 14:03
> I can add a defensive test at the beginning of TTA so that the error comes immediately

It will be great, thank you!

> Mixed precision isn't meant to be used outside of training

Generally speaking, you are right.
However, sometimes even inference is taking too long, and FP16 can give it a boost. So if it possible to use, maybe it's not a bad thing to do?
If you are worried about this approach being unexpected for users, we can add a UserWarning.

**Comment by sgugger** [comment] 2019-10-17 14:29
Done and pushed, this is now in master.
