### ISSUE TITLE
DataLoaders.from_dsets does not apply after_item transforms to the validation dataset

### ISSUE THREAD

**Issue by backdoorbreaker** [fastai/fastai#3373] opened 2021-05-13 00:03 UTC
I'm admittedly fairly new to fastai2, but I did search in the forums for the `from_dsets` keyword and found no useful results. 

Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
When the `DataLoaders.from_dsets` classmethod is used, the `after_item` transforms are not applied to the validation dataset. This results in a `TypeError` within the `fa_collate` function because in my specific use case, the `ToTensor` transform is not called on my validation dataset which consists of `PILImage` types. This `TypeError` occurs at the start of the validation portion of the training loop.

This is different than the behavior of some of the other functions which accept `after_item`. (e.g. the `dataloaders` instance method on `TfmdLists`)

When inspecting the source code for [`DataLoaders.from_dsets`](https://github.com/fastai/fastai/blob/master/fastai/data/core.py#L182), we can see that the function builds up a list of `kwargs` for each of the datasets. When printing these `kwargs` out, `after_item: Pipeline: ToTensor` appears in the `kwargs` for both the training and validation dataset which seems to contradict the behavior that I see.

**To Reproduce**
It's a bit challenging to exactly reproduce my local setup, but I will describe how to view similar behavior in the siamese tutorial.
1. Open the [siamese tutorial colab](https://colab.research.google.com/github/fastai/fastai/blob/master/nbs/24_tutorial.siamese.ipynb)
2. Run the cells up to cell 34 (at the time of writing). cell contents: `dls = DataLoaders.from_dsets(...)`
3. Add an `after_item=[ToTensor]` to that `from_dsets` call
4. Print out `dls.train.after_item` and `dls.valid.after_item`
5. You should see that `dls.valid.after_item` is an empty pipeline

**Expected behavior**
I expected `ToTensor` to also be applied to my validation dataset during training.

It was simple enough to manually add the transform back in like so:
```
dls.valid.after_item = Pipeline([ToTensor])
```
Everything worked with that addition - I can't help but feel like I'm doing something incorrect though.

**Error with full stack trace**
```
    learner.fit_one_cycle(1, lr_steep)
  File "/usr/local/lib/python3.6/dist-packages/fastai/callback/schedule.py", line 112, in fit_one_cycle
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
  File "/usr/local/lib/python3.6/dist-packages/fastai/learner.py", line 218, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "/usr/local/lib/python3.6/dist-packages/fastai/learner.py", line 160, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/usr/local/lib/python3.6/dist-packages/fastai/learner.py", line 209, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "/usr/local/lib/python3.6/dist-packages/fastai/learner.py", line 160, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/usr/local/lib/python3.6/dist-packages/fastai/learner.py", line 204, in _do_epoch
    self._do_epoch_validate()
  File "/usr/local/lib/python3.6/dist-packages/fastai/learner.py", line 200, in _do_epoch_validate
    with torch.no_grad(): self._with_events(self.all_batches, 'validate', CancelValidException)
  File "/usr/local/lib/python3.6/dist-packages/fastai/learner.py", line 160, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/usr/local/lib/python3.6/dist-packages/fastai/learner.py", line 166, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
  File "/usr/local/lib/python3.6/dist-packages/fastai/data/load.py", line 109, in __iter__
    for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 34, in fetch
    data = next(self.dataset_iter)
  File "/usr/local/lib/python3.6/dist-packages/fastai/data/load.py", line 118, in create_batches
    yield from map(self.do_batch, self.chunkify(res))
  File "/usr/local/lib/python3.6/dist-packages/fastai/data/load.py", line 144, in do_batch
    def do_batch(self, b): return self.retain(self.create_batch(self.before_batch(b)), b)
  File "/usr/local/lib/python3.6/dist-packages/fastai/data/load.py", line 143, in create_batch
    def create_batch(self, b): return (fa_collate,fa_convert)[self.prebatched](b)
  File "/usr/local/lib/python3.6/dist-packages/fastai/data/load.py", line 50, in fa_collate
    else type(t[0])([fa_collate(s) for s in zip(*t)]) if isinstance(b, Sequence)
  File "/usr/local/lib/python3.6/dist-packages/fastai/data/load.py", line 50, in <listcomp>
    else type(t[0])([fa_collate(s) for s in zip(*t)]) if isinstance(b, Sequence)
  File "/usr/local/lib/python3.6/dist-packages/fastai/data/load.py", line 51, in fa_collate
    else default_collate(t))
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 85, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'fastai.vision.core.PILImage'>
```

**Additional context**
I'm not 100% positive this is a bug. It's likely that I am just using the `DataLoaders.from_dsets` API incorrectly. Any additional insights or help would be much appreciated.

**Comment by riven314** [comment] 2021-05-30 14:22
The issue is gone when I tried to `deepcopy` the `kwargs` from train and valid set.  
So I think probably its caused by the fact that `kwargs['after_item']` are pointing to the same object for both train and valid set. And during train's `DataLoader` is setup, `kwargs['after_item']` is popped out which caused later on valid's `DataLoader` failed to access it. 
![Screenshot from 2021-05-30 22-20-18](https://user-images.githubusercontent.com/21143399/120107889-5547f880-c195-11eb-8aef-624a2af76ebb.png)

Thats what I found in prelim stage, needa further investigate.  
The above screenshot comes from this colab notebook which I copied from yours. 
https://colab.research.google.com/drive/1UhcEL5ykvNj4NJ4LU0BqH0qNGLRoQl0c?usp=sharing

**Comment by backdoorbreaker** [comment] 2021-06-02 13:07
Thank you for digging into this, Alex. Your findings were very insightful for me.

As an existing contributor, what is your opinion on me opening a PR to add this `deepcopy` to `from_dsets` and `TfmdDL`?

**Comment by riven314** [comment] 2021-06-02 17:14
@backdoorbreaker 
I have opened a new issue to track and elaborate this issue
meanwhile @arampacha and I are working on a fix for this.
Instead of doing `deepcopy`, we plan to restructure `DataLoaders.from_dsets`

**Comment by backdoorbreaker** [comment] 2021-06-02 18:32
Sounds good. And again, @riven314 @arampacha I appreciate the help!

**Comment by tcapelle** [comment] 2021-06-29 07:23
I think you can close this @jph00

**Closed** 2021-06-29 07:26 UTC
