### ISSUE TITLE
Fastai Tokenization Python "OSError: [Errno 12] Cannot allocate memory" when there is still free memory

### ISSUE THREAD

**Issue by Knight-H** [fastai/fastai#1979] opened 2019-04-15 11:16 UTC
**Describe the bug**

I am not sure about the root cause of the issue that I am facing, but I am getting the error `OSError: [Errno 12] Cannot allocate memory` when trying to Tokenize. The code that I used to Tokenize is shown below (similar to how [thai2fit](https://github.com/cstorm125/thai2fit/blob/master/thwiki_lm/thwiki_lm.ipynb) created their Tokenizer and databunch):

```Python
tt = Tokenizer(tok_func = ThaiTokenizer, lang = 'th', pre_rules = pre_rules_th, post_rules=post_rules_th, n_cpus=40)
processor = [TokenizeProcessor(tokenizer=tt, chunksize=300000, mark_fields=True),
             NumericalizeProcessor(vocab=None, max_vocab=80000, min_freq=4)]
data_lm = (ItemLists(MODEL_PATH, 
    TextList.from_df(trn_texts, MODEL_PATH, cols=['Title', 'Kratoo'], processor=processor),
    TextList.from_df(val_texts, MODEL_PATH, cols=['Title', 'Kratoo'], processor=processor))
    .label_for_lm()
    .add_test(TextList.from_df(test_texts, MODEL_PATH, cols=['Title', 'Kratoo'], processor=processor))
    .databunch(bs=64, val_bs=64, num_workers=40))
```

The progress bar went from 0% to 100% (which should indicate that the `TokenizeProcessor` is done on the train data  - the size is around 11 GB of data with 5 million rows). And the progress bar vanish and the CPU utilization went down for a while (my guess is that it is starting the `NumericalizeProcessor`?) At that stage the RAM is not fully utilized, around 120 GB from a total of 188 GB as indicated in the screenshot below in *Ram Usage After Error*.  However, waiting a while, it shows the error `OSError: [Errno 12] Cannot allocate memory` without any more RAM utilization (still at 120/188).   
  
I reran the process many times with different chunksizes (100k, 200k, 250k, 300k) and it seems that the error is persistent. I am not sure what configuration am I supposed to change or how am I supposed to handle this.   
  
I also tried making a `CustomTokenizer` with `Pool` instead of `ProcessPoolExecutor`, and it doesn't help, so I guess that was not the cause. 
```Python
class CustomTokenizer(Tokenizer):
    def __init__(self, *args, **kwargs):
        super(CustomTokenizer, self).__init__(*args, **kwargs)
        
    def process_all(self, texts:Collection[str]) -> List[List[str]]:
        "Process a list of `texts`."
        
        if self.n_cpus <= 1: return self._process_all_1(texts)
        pool = self.ctx.Pool(processes = self.n_cpus)
        
        result = sum(pool.map(self._process_all_1, partition_by_cores(texts, self.n_cpus)), [])
        pool.close()
        pool.join()
        return result
```

Trying `set_start_method()` according to [this post](https://stackoverflow.com/questions/42584525/python-multiprocessing-debugging-oserror-errno-12-cannot-allocate-memory/45620524#45620524) also somehow didn't work because the process did not run at all.   
  
In all, I am lost with what am I supposed to do, running one iteration uses a lot of time, and I am out of ideas to debug. Using a smaller train data (from 3mil to 5mil rows) works fine, but that isn't a solution that I would prefer. Do you have any suggestions for me?

**Provide your installation details**

```text
=== Software === 
python        : 3.7.3
fastai        : 1.0.51
fastprogress  : 0.1.20
torch         : 1.0.1.post2
nvidia driver : 410.79
torch cuda    : 9.0.176 / is available
torch cudnn   : 7402 / is enabled

=== Hardware === 
nvidia gpus   : 4
torch devices : 4
  - gpu0      : 24449MB | Quadro P6000
  - gpu1      : 24449MB | Quadro P6000
  - gpu2      : 24449MB | Quadro P6000
  - gpu3      : 24449MB | Quadro P6000

=== Environment === 
platform      : Linux-4.4.0-140-generic-x86_64-with-debian-stretch-sid
distro        : #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018
conda env     : Unknown
python        : /usr/local/bin/python3.7
sys.path      : /workdir/senior_proj/data_tokenized
/usr/local/lib/python37.zip
/usr/local/lib/python3.7
/usr/local/lib/python3.7/lib-dynload
/usr/local/lib/python3.7/site-packages
```

**To Reproduce**

I am not sure how to give you guys to reproduce because the data is not open to all.. But the code I exactly used was shown above. 

**Expected behavior**

The run should progress without any OS memory errors, just like how it did with the smaller batch of data - and returns to be a big bunch of `TextLMDataBunch` and able to `save()` to use the data for later training. 

**Screenshots**

*Ram Usage After Error*
![Screenshot from 2019-04-15 02-41-59](https://user-images.githubusercontent.com/19682720/56127965-94f8f980-5fa8-11e9-91b4-ff1b34b42d53.png)

**Additional context**

`ThaiTokenizer` is a wrapper of the [PyThaiNLP Tokenizer](https://github.com/PyThaiNLP/pythainlp/blob/dev/pythainlp/tokenize/__init__.py), with the code as shown:
```Python
class ThaiTokenizer(BaseTokenizer):
    def __init__(self, lang='th'):
        self.lang = lang
        self.pyengine = PyThaiTokenizer(os.path.join(github_path, 'words_modified.txt'))
    
    def tokenizer(self, t):
        return self.pyengine.word_tokenize(t)
```

**Comment by sgugger** [comment] 2019-04-15 13:03
From what you're describing, it sounds like there is not enough RAM to allocate the array with all the ids when the numericalization is done. My advise would be to tokenize and numericalize by chunks and save everything in memory then only load the ids for training. I've seen code on the [forum](https://forums.fast.ai) to do that, don't remember the particular thread.

Closing this as it's not a bug in the library per se, we can continue discussing it on the forum.

**Closed by sgugger** 2019-04-15 13:03 UTC
