### ISSUE TITLE
Rectangular Image Sizing not working

### ISSUE THREAD

**Issue by jaideep11061982** [fastai/fastai#1851] opened 2019-03-21 05:23 UTC
**Describe the bug**

I pass below arguments to data block. It takes image size as tuple but in actual image get resized as square only. 

data1 = (src1.transform((trn_tfms,trn_tfms), size=(324,224),resize_method=ResizeMethod.SQUISH)
        .databunch(bs=56).normalize(imagenet_stats)) #40

when i query data1
Train: LabelList (19040 items)
x: ImageList
Image (3, 324, 324),Image (3, 324, 324),Image (3, 324, 324),Image (3, 324, 324),Image (3, 324, 324)

Why image is getting resized as square rather than rectangle...
**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment] 2019-03-21 13:43
Are you sure you are on the latest of fastai? I just tested and the following
```
from fastai.vision import *

path = untar_data(URLs.PETS)
path_img = path/'images'
fnames = get_image_files(path_img)
pat = re.compile(r'/([^/]+)_\d+.jpg$')
src = ImageList.from_folder(path_img).split_by_rand_pct().label_from_re(pat)
src = src.transform(get_transforms(), size=(324,224), resize_method=ResizeMethod.SQUISH)
src.train
```
produces
```
LabelList (5912 items)
x: ImageList
Image (3, 324, 224),Image (3, 324, 224),Image (3, 324, 224),Image (3, 324, 224),Image (3, 324, 224)
y: CategoryList
saint_bernard,staffordshire_bull_terrier,Persian,Maine_Coon,newfoundland
Path: /home/ubuntu/notebooks/data/oxford-iiit-pet/images
```

In general, please include your installation details when filing an issue, as instructed by the template.

**Comment by sgugger** [comment] 2019-03-27 18:50
Closing this since there is no news in a week and we can't reproduce. Feel free to reopen if the bug persists on master with a reproducible example.

**Closed by sgugger** 2019-03-27 18:50 UTC
