### ISSUE TITLE
AttributeError: 'wrapper_descriptor' object has no attribute '__code__'

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [fastai/fastai#1844] opened 2019-03-20 11:54 UTC
If I try to call 

`leaner.load(NAME)`

I get this error:

```
    learner = get_learner(model_name, model_dir, callbacks=[store_inputs], root=root, transform=get_transform(None, scale=10),  tr=0.45, n=1)
  File "/Users/vaevictis/Documents/Project/Master-Thesis/core/estimators/utils.py", line 31, in get_learner
    learner.load(load_metric)
  File "/usr/local/lib/python3.6/site-packages/fastai/basic_train.py", line 261, in load
    if purge: self.purge(clear_opt=ifnone(with_opt, False))
  File "/usr/local/lib/python3.6/site-packages/fastai/basic_train.py", line 320, in purge
    self.callbacks = [load_callback(c,s, self) for c,s in cb_state.items()]
  File "/usr/local/lib/python3.6/site-packages/fastai/basic_train.py", line 320, in <listcomp>
    self.callbacks = [load_callback(c,s, self) for c,s in cb_state.items()]
  File "/usr/local/lib/python3.6/site-packages/fastai/basic_train.py", line 577, in load_callback
    init_kwargs, others = split_kwargs_by_func(state, class_func.__init__)
  File "/usr/local/lib/python3.6/site-packages/fastai/core.py", line 262, in split_kwargs_by_func
    args = func_args(func)
  File "/usr/local/lib/python3.6/site-packages/fastai/core.py", line 253, in func_args
    code = func.__code__
AttributeError: 'wrapper_descriptor' object has no attribute '__code__'

```

My `fastai` version is `1.0.50.post1`

Thank you in advance,

Best

**Comment by sgugger** [comment] 2019-03-20 13:07
We can't help without, at the very minimum, see the whole code you are running, and preferably a reproducible example.

**Comment by sgugger** [comment] 2019-03-27 13:07
Closing this since no news in a week. Feel free to reopen with more details (the issue template contains all the information we need from you to be able to sole the bug).

**Closed by sgugger** 2019-03-27 13:07 UTC

**Comment by ohmeow** [comment] 2019-11-19 17:28
Just saw this.  I'm getting this error as well.

It looks like it's happening when `load_learner()` is trying to load any custom callbacks.  Here is the error followed by the code:

```
<ipython-input-196-75490d6db2c0> in <module>
----> 1 inf_learn = load_learner(PATH)

~/.local/share/virtualenvs/nlp-playground-XzalehAv/lib/python3.7/site-packages/fastai/basic_train.py in load_learner(path, file, test, tfm_y, **db_kwargs)
    623     res = clas_func(data, model, **state)
    624     res.callback_fns = state['callback_fns'] #to avoid duplicates
--> 625     res.callbacks = [load_callback(c,s, res) for c,s in cb_state.items()]
    626     return res

~/.local/share/virtualenvs/nlp-playground-XzalehAv/lib/python3.7/site-packages/fastai/basic_train.py in <listcomp>(.0)
    623     res = clas_func(data, model, **state)
    624     res.callback_fns = state['callback_fns'] #to avoid duplicates
--> 625     res.callbacks = [load_callback(c,s, res) for c,s in cb_state.items()]
    626     return res

~/.local/share/virtualenvs/nlp-playground-XzalehAv/lib/python3.7/site-packages/fastai/basic_train.py in load_callback(class_func, state, learn)
    606 
    607 def load_callback(class_func, state, learn:Learner):
--> 608     init_kwargs, others = split_kwargs_by_func(state, class_func.__init__)
    609     res = class_func(learn, **init_kwargs) if issubclass(class_func, LearnerCallback) else class_func(**init_kwargs)
    610     for k,v in others.items(): setattr(res, k, v)

~/.local/share/virtualenvs/nlp-playground-XzalehAv/lib/python3.7/site-packages/fastai/core.py in split_kwargs_by_func(kwargs, func)
    287 def split_kwargs_by_func(kwargs, func):
    288     "Split `kwargs` between those expected by `func` and the others."
--> 289     args = func_args(func)
    290     func_kwargs = {a:kwargs.pop(a) for a in args if a in kwargs}
    291     return func_kwargs, kwargs

~/.local/share/virtualenvs/nlp-playground-XzalehAv/lib/python3.7/site-packages/fastai/core.py in func_args(func)
    278 def func_args(func)->bool:
    279     "Return the arguments of `func`."
--> 280     code = func.__code__
    281     return code.co_varnames[:code.co_argcount]
    282 

```

... and the code is

```
inf_learn = load_learner(PATH)
```

The only custom callback I have is this:
```
class HFT_Loss(Callback):
    def on_loss_begin(self, last_output, **kwargs)->Any:
        return {'last_output': last_output[0]}
```

Again, model trains just fine with the custom ItemList I'm using; I can save it, load it, run `learn.predict` on it ... but `load_learner` throws this error.

-wg

**Comment by ohmeow** [comment] 2019-11-19 17:46
> If I try to call
> 
> `leaner.load(NAME)`
> 
> I get this error:
> 
> ```
>     learner = get_learner(model_name, model_dir, callbacks=[store_inputs], root=root, transform=get_transform(None, scale=10),  tr=0.45, n=1)
>   File "/Users/vaevictis/Documents/Project/Master-Thesis/core/estimators/utils.py", line 31, in get_learner
>     learner.load(load_metric)
>   File "/usr/local/lib/python3.6/site-packages/fastai/basic_train.py", line 261, in load
>     if purge: self.purge(clear_opt=ifnone(with_opt, False))
>   File "/usr/local/lib/python3.6/site-packages/fastai/basic_train.py", line 320, in purge
>     self.callbacks = [load_callback(c,s, self) for c,s in cb_state.items()]
>   File "/usr/local/lib/python3.6/site-packages/fastai/basic_train.py", line 320, in <listcomp>
>     self.callbacks = [load_callback(c,s, self) for c,s in cb_state.items()]
>   File "/usr/local/lib/python3.6/site-packages/fastai/basic_train.py", line 577, in load_callback
>     init_kwargs, others = split_kwargs_by_func(state, class_func.__init__)
>   File "/usr/local/lib/python3.6/site-packages/fastai/core.py", line 262, in split_kwargs_by_func
>     args = func_args(func)
>   File "/usr/local/lib/python3.6/site-packages/fastai/core.py", line 253, in func_args
>     code = func.__code__
> AttributeError: 'wrapper_descriptor' object has no attribute '__code__'
> ```
> 
> My `fastai` version is `1.0.50.post1`
> 
> Thank you in advance,
> 
> Best

Make sure you have `@dataclass` annotation above your custom callback class.

**Comment by TanayPandya18** [comment] 2022-03-01 11:04
how did you solve this error? I have the same issue and its bothering me for days. Please help. 
Thanks in advance

**Comment by Gurvinder18** [comment] 2022-03-01 11:06
> how did you solve this error? I have the same issue and its bothering me for days. Please help. Thanks in advance

help
