### ISSUE TITLE
Do we have an image template as part of the library?

### ISSUE THREAD

**Issue by kechan** [fastai/fastai#1687] opened 2019-02-20 19:07 UTC
I remembered OpenCV has such a feature. I thought it may be for face recognition.

I wonder if we have an image that’s embedded in the library itself? This is good for quick test, unit test, CI run, bug report, etc. etc. The URLs in tutorial and lessons seem to take too much time and assume a working directory. Too cumbersome and slow.

**Comment by sgugger** [comment] 2019-02-20 21:31
Our sample at URLs.MNIST_TINY is downloaded during the test suite. Any image of it would be available for tests.

**Comment by kechan** [comment] 2019-02-20 21:42
Does this rely on network connection and a local working dir to work?

**Comment by sgugger** [comment] 2019-02-20 21:47
I don't understand the question. Obviously it requires an internet connection to be downloaded and it will be downloaded in .fastai/data/ like every dataset the library provides convenient links for. I'm just stating it can be used for the tests in the test suite since it's part of the four datasets downloaded when it's executed.

**Comment by stas00** [comment] 2019-02-20 21:52
We originally started with [several small datasets in the repo](https://github.com/fastai/fastai/tree/master/data), so that you won't need an internet connection, but then the needs for a variety of such datasets has grown, so we stopped adding those to the repo (as repo's size continually grows already).

But I understand that you're talking about images in the repo that can be fetched via a function, rather read from the disk. Kind of like the inlined images in the html.

**Comment by kechan** [comment] 2019-02-20 22:03
A self-synthesize one from a function is even better than what I talked about. 
Basically, it's used for lowest # of code lines to reproduce data aug type of bug, where  you don't need a whole dataset.

This is not urgent, if this is not wanted by most, maybe we can have this issue closed.

**Comment by stas00** [comment] 2019-02-20 22:06
I think we are just not clear on what you're proposing. Do you know of an existing implementation that you can point to? ideally one that's documented/demo'ed so it's easy to quickly see it in action.

So far I understand you're proposing for fastai to have a synthetic image generator.

**Comment by kechan** [comment] 2019-02-20 22:20
Well, a synthetic one is probably not necessary right now. You can just check in a static image into the library. A simple geometric one like this: 

![get_transforms](https://user-images.githubusercontent.com/122762/53128544-139a6300-3533-11e9-9ee1-fac9acd41733.jpg)

We may replace this with an official logo of fastai, maybe a version that make most data aug transform easily to spot. 

OpenCV, if i remembered right, did this:

cv::Mat img = cv::imread("lenna.png");

Where lenna.png is always available no matter what env you are, 'cos it is part of the library. This photo has become one of the most popular one in the history of CS (maybe on par with the "tea pot" in computer graphics).

**Comment by stas00** [comment] 2019-02-20 22:31
There is no problem adding such images to the repo, @kechan, if it helps our and users' cause. Let's just try to put it to use right away and then it'll be clear where and how to integrate it into the repo. Does it make sense?

**Comment by sgugger** [comment] 2019-02-20 22:39
I'll close the issue since it's not a bug in the library, and I think this should then be debated on the [forum](https://forums.fast.ai) so that anyone can weight in.

**Closed by sgugger** 2019-02-20 22:39 UTC
