### ISSUE TITLE
Windows multiprocessing broken in latest commits

### ISSUE THREAD

**Issue by EtienneT** [fastai/fastai#1846] opened 2019-03-20 15:16 UTC
**Describe the bug**
Something happened between commit e46223bd6f0edc35b56fb7371297731241a595ae and the most recent HEAD regarding windows multiprocessing.  Using fastai master most recent commit, when calling learn.fit on any model in windows you get a Broken Pipe error (related to multi-processing).  Using num_workers=0 works, but multi-processing works if you checkout fastai at e46223bd6f0edc35b56fb7371297731241a595ae (~ feb 28 commit).  So something changed between the two.  Digging deeper, using git bisect, **I found that the problem started occurring at commit fb5d2f525392be5d2affc7138a920065a80d062b**.  Something related to google colab checks...  Here is the exception we get when using the latest commit:

```
---------------------------------------------------------------------------
BrokenPipeError                           Traceback (most recent call last)
<ipython-input-6-0ef5bf68f37d> in <module>
----> 1 data.show_batch(rows=10)

c:\work\ml\fastai-dev\fastai\fastai\basic_data.py in show_batch(self, rows, ds_type, reverse, **kwargs)
    183     def show_batch(self, rows:int=5, ds_type:DatasetType=DatasetType.Train, reverse:bool=False, **kwargs)->None:
    184         "Show a batch of data in `ds_type` on a few `rows`."
--> 185         x,y = self.one_batch(ds_type, True, True)
    186         if reverse: x,y = x.flip(0),y.flip(0)
    187         n_items = rows **2 if self.train_ds.x._square_show else rows

c:\work\ml\fastai-dev\fastai\fastai\basic_data.py in one_batch(self, ds_type, detach, denorm, cpu)
    166         w = self.num_workers
    167         self.num_workers = 0
--> 168         try:     x,y = next(iter(dl))
    169         finally: self.num_workers = w
    170         if detach: x,y = to_detach(x,cpu=cpu),to_detach(y,cpu=cpu)

c:\work\ml\fastai-dev\fastai\fastai\basic_data.py in __iter__(self)
     73     def __iter__(self):
     74         "Process and returns items from `DataLoader`."
---> 75         for b in self.dl: yield self.proc_batch(b)
     76 
     77     @classmethod

~\Anaconda3\envs\fastai-master\lib\site-packages\torch\utils\data\dataloader.py in __iter__(self)
    817 
    818     def __iter__(self):
--> 819         return _DataLoaderIter(self)
    820 
    821     def __len__(self):

~\Anaconda3\envs\fastai-master\lib\site-packages\torch\utils\data\dataloader.py in __init__(self, loader)
    558                 #     before it starts, and __del__ tries to join but will get:
    559                 #     AssertionError: can only join a started process.
--> 560                 w.start()
    561                 self.index_queues.append(index_queue)
    562                 self.workers.append(w)

~\Anaconda3\envs\fastai-master\lib\multiprocessing\process.py in start(self)
    110                'daemonic processes are not allowed to have children'
    111         _cleanup()
--> 112         self._popen = self._Popen(self)
    113         self._sentinel = self._popen.sentinel
    114         # Avoid a refcycle if the target function holds an indirect

~\Anaconda3\envs\fastai-master\lib\multiprocessing\context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224 
    225 class DefaultContext(BaseContext):

~\Anaconda3\envs\fastai-master\lib\multiprocessing\context.py in _Popen(process_obj)
    320         def _Popen(process_obj):
    321             from .popen_spawn_win32 import Popen
--> 322             return Popen(process_obj)
    323 
    324     class SpawnContext(BaseContext):

~\Anaconda3\envs\fastai-master\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     63             try:
     64                 reduction.dump(prep_data, to_child)
---> 65                 reduction.dump(process_obj, to_child)
     66             finally:
     67                 set_spawning_popen(None)

~\Anaconda3\envs\fastai-master\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

BrokenPipeError: [Errno 32] Broken pipe
```

**Provide your installation details**

```text
=== Software === 
python        : 3.7.1
fastai        : 1.0.51.dev0
fastprogress  : 0.1.20
torch         : 1.0.0
torch cuda    : 10.0 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
torch devices : 1
  - gpu0      : GeForce GTX 1070

=== Environment === 
platform      : Windows-10-10.0.17763-SP0
conda env     : fastai-master
python        : C:\Users\Etienne-PC\Anaconda3\envs\fastai-master\python.exe
sys.path      : C:\work\ML\fastai-v3\nbs\dl1
C:\Users\Etienne-PC\Anaconda3\envs\fastai-master\python37.zip
C:\Users\Etienne-PC\Anaconda3\envs\fastai-master\DLLs
C:\Users\Etienne-PC\Anaconda3\envs\fastai-master\lib
C:\Users\Etienne-PC\Anaconda3\envs\fastai-master

C:\Users\Etienne-PC\Anaconda3\envs\fastai-master\lib\site-packages
c:\work\ml\fastai-dev\fastai
C:\Users\Etienne-PC\Anaconda3\envs\fastai-master\lib\site-packages\win32
C:\Users\Etienne-PC\Anaconda3\envs\fastai-master\lib\site-packages\win32\lib
C:\Users\Etienne-PC\Anaconda3\envs\fastai-master\lib\site-packages\Pythonwin
C:\Users\Etienne-PC\Anaconda3\envs\fastai-master\lib\site-packages\IPython\extensions
C:\Users\Etienne-PC\.ipython
no nvidia-smi is found
```

**To Reproduce**

Using the latest version of fastai in master, run in windows https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson4-tabular.ipynb.  Notice the broken pipe exception.

Then checkout to commit e46223bd6f0edc35b56fb7371297731241a595ae and notice that the exception does not occur.  The exception starts occurring after commit fb5d2f525392be5d2affc7138a920065a80d062b.

**Expected behavior**
Multi-processing should work in windows.  It used to work.

**Comment by EtienneT** [comment] 2019-03-20 15:37
I am trying to fork and submit a pull-request but github clone is super slow...  Here is my fix inside the file ipython.py:

```
def is_in_colab():
    "Is the code running in Google Colaboratory?"
    def ipython_is_colab():
        if __name__ == '__main__':
            return get_ipython().__class__.__module__ == 'google.colab._shell'

    if IS_IN_IPYTHON and ipython_is_colab(): return True
    else:                                    return False

IS_IN_COLAB = is_in_colab()
```

I just added the if __name__ == '__main__':

This seems to make it work in windows.

**Comment by EtienneT** [comment] 2019-03-20 15:44
@ericricky could you test that my change still works in Google Colab?  Without this, windows multi-processing is broken.

Thanks,

**Comment by EtienneT** [comment] 2019-03-20 17:06
Proposed pull request: #1848

**Comment by stas00** [comment] 2019-03-20 17:17
Fixed by https://github.com/fastai/fastai/pull/1848

**Comment by stas00** [comment] 2019-03-20 17:22
I refactored it to be just:
```
    "Is the code running in Google Colaboratory?"
    return (IS_IN_IPYTHON and
            __name__ == '__main__' and
            get_ipython().__class__.__module__ == 'google.colab._shell')
```

Let me know if I broke anything.

**Comment by EtienneT** [comment] 2019-03-20 17:28
Just tested it and it works fine on windows.

Thanks,

**Comment by ericricky** [comment] 2019-03-20 19:36
@EtienneT Thanks for the note. Unfortunately, `doc` doesn't work for me in Colab with the dev branch now. I'll try a different test for Colab in my fork and tag you - maybe you can try it out on Windows and see if it works. One option is to try my original test, which is to check to see if `/var/colab` exists, which is definitely less reliable, but probably not as disruptive. Another option would be to call `is_in_colab` when `doc` is run. Idk how to do this in Python, but maybe we can call `is_in_colab` the first time `doc` is run and cache the result

**Comment by EtienneT** [comment] 2019-03-20 19:56
Hum, never really played with Colab so I am not sure what is best here.  But if you want me to test something on windows @ericricky  let me know!

**Comment by stas00** [comment] 2019-03-20 20:18
@ericricky, so in what situation `__name__ == '__main__'` is False on colab? I open colab and run it and it was true, hence I merged @EtienneT's PR.

And then perhaps it was my refactoring that broke it, that somehow earlier it was caching it - if you revert it back from https://github.com/fastai/fastai/commit/0e7c798b2cc4037169b99abd3e342f96c8354150 does it work?

**Comment by sgugger** [comment] 2019-03-20 21:18
Another way to test whether you're in colab is simply
```
try:
    from google import colab
    return True
except: return False
```
That's what is used in fastprogress.

**Comment by ericricky** [comment] 2019-03-21 01:59
@stas00 Colab is just running Ubuntu under the hood, so when the code in fastai.utils.ipython runs, `__name__` evaluates to `'fastai.utils.ipython'` like usual.

@sgugger That's another option. We can just do that if you're already using it in fastprogress.

@EtienneT Can you try [my fork](https://github.com/ericricky/fastai) in Windows?

**Comment by stas00** [comment] 2019-03-21 02:06
> @stas00 Colab is just running Ubuntu under the hood, so when the code in fastai.utils.ipython runs, __name__ evaluates to 'fastai.utils.ipython' like usual.

Thank you, @ericricky - so my test was invalid and I shouldn't have merged it. Sorry about that.

Let's go with fastprogress solution then.

**Comment by EtienneT** [comment] 2019-03-21 12:43
Tested your fork on windows @ericricky  and the fix seems to work on windows!  You should push the pull request.

Thanks,

**Comment by bny6613** [comment] 2019-03-21 13:07
Just faced this issue as well, so for me it shows that the error is: 

    NameError: name 'get_ipython' is not defined 
And simply adding 

    from IPython import get_ipython 
to the https://github.com/fastai/fastai/blob/master/fastai/utils/ipython.py solves the issue.

**Closed** 2019-03-21 13:18 UTC

**Comment by sgugger** [comment] 2019-03-21 13:21
Pushed the fastprogress since it's the same as @ericricky and @EtienneT confirmed it worked.
@bny6613 I added the import too, in case people want to use this directly (guessing the others didn't have the problem because `get_ipython` is imported somewhere else in fastai).

**Comment by EtienneT** [comment] 2019-03-21 13:33
@sgugger tested your commit on windows and it works. 👍

**Comment by bdubreu** [comment] 2019-08-17 12:16
Hi,

I am sorry if I make a mistake while posting here, but I'm quite new to the process of asking questions about library development. 
Right now I am facing the same Broken Pipe Error. 
I installed Pytorch and Fastai yesterday (using Anaconda, on Windows 10 64 bits). Well, first of all after conda installing pytorch, I couldn't conda install fastai as there were some conflicts that the install didn't manage to resolve. When using "pip install fastai", however, it worked (I'm mentionning this because maybe it could be why I still have this broken pipe error in August ?)

In any case, I read multiple threads, and found what is supposed to be a workaround but doesn't work for me, using if __name__ == '__main__':

Could anyone please tell me what steps I can take to solve this Broken Pipe error ?

Thanks and have a nice day
