### ISSUE TITLE
fastai 2.1.8

### ISSUE THREAD

**Issue by henry090** [fastai/fastai#3055] opened 2020-12-05 08:48 UTC
https://colab.research.google.com/drive/10SQKNaoxsEb8GWjziBrZRQV-AWfmul0Z?usp=sharing

```
from fastai.vision.all import *

fnames = get_image_files(untar_data(URLs.PETS))
dls = ImageDataLoaders.from_name_re(
    path, fnames, pat=r'(.+)_\d+.(?:png|jpg)$', item_tfms=Resize(460), bs=12,
    batch_tfms=[*aug_transforms(size=224, min_scale=0.75), Normalize.from_stats(*imagenet_stats)])

learn = cnn_learner(dls, resnet34, metrics=error_rate)
learn.summary()
```
```
TypeError: 'int' object is not iterable

Detailed traceback: 
  File "/home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/fastai/callback/hook.py", line 205, in summary
    res = module_summary(self, *xb)
  File "/home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/fastai/callback/hook.py", line 175, in module_summary
    inp_sz = _print_shapes(apply(lambda x:x.shape, xb), bs)
  File "/home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/fastai/callback/hook.py", line 165, in _print_shapes
    else: return str([_print_shapes(x, bs) for x in o])
  File "/home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/fastai/callback/hook.py", line 165, in <listcomp>
    else: return str([_print_shapes(x, bs) for x in o])
  File "/home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/fastai/callback/hook.py", line 165, in _print_shapes
```

**Comment by muellerzr** [comment] 2020-12-07 05:11
Duplicate of https://github.com/fastai/fastai/issues/3011

**Comment by muellerzr** [comment] 2020-12-24 19:05
@jph00 this can be closed!

**Closed** 2020-12-24 19:08 UTC

**Comment by jph00** [comment] 2020-12-24 21:43
Thank you!
