### ISSUE TITLE
ObjectItemList.from_folder(...).random_split_by_pct().label_from_func does not work with constant count of bboxes

### ISSUE THREAD

**Issue by radekosmulski** [fastai/fastai#1408] opened 2018-12-28 16:21 UTC
When creating a databunch with varying number of bboxes per example, everything works

(this is an example based on the [docs](https://docs.fast.ai/data_block.html) for the coco dataset)

![56565c1f-777c-4186-bfff-e3f30f2fcb60](https://user-images.githubusercontent.com/2444926/50521021-d92cc080-0ac3-11e9-82f7-4133e03ad09e.png)

When creating a databunch with a constant number of bboxes per example, something goes wrong.

![ebda6bf2-29d2-42d5-a49c-e3389782a1e6](https://user-images.githubusercontent.com/2444926/50521073-201ab600-0ac4-11e9-8079-59194e8fb5d6.png)

This behavior manifests for any value of `i` that I tried.

This is the stack trace that I get upon executing `data.train_ds`

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda3/envs/fastai_n/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/anaconda3/envs/fastai_n/lib/python3.7/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    398                         if cls is not object \
    399                                 and callable(cls.__dict__.get('__repr__')):
--> 400                             return _repr_pprint(obj, self, cycle)
    401 
    402             return _default_pprint(obj, self, cycle)

~/anaconda3/envs/fastai_n/lib/python3.7/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    693     """A pprint that just redirects to the normal repr function."""
    694     # Find newlines and replace them with p.break_()
--> 695     output = repr(obj)
    696     for idx,output_line in enumerate(output.splitlines()):
    697         if idx:

~/workspace/fastai/fastai/data_block.py in __repr__(self)
    514     def __repr__(self)->str:
    515         x = f'{self.x}' # force this to happen first
--> 516         return f'{self.__class__.__name__}\ny: {self.y}\nx: {x}'
    517     def predict(self, res):
    518         "Delegates predict call on `res` to `self.y`."

~/workspace/fastai/fastai/data_block.py in __repr__(self)
     59         return self.items[i]
     60     def __repr__(self)->str:
---> 61         items = [self[i] for i in range(min(5,len(self.items)))]
     62         return f'{self.__class__.__name__} ({len(self.items)} items)\n{items}...\nPath: {self.path}'
     63 

~/workspace/fastai/fastai/data_block.py in <listcomp>(.0)
     59         return self.items[i]
     60     def __repr__(self)->str:
---> 61         items = [self[i] for i in range(min(5,len(self.items)))]
     62         return f'{self.__class__.__name__} ({len(self.items)} items)\n{items}...\nPath: {self.path}'
     63 

~/workspace/fastai/fastai/data_block.py in __getitem__(self, idxs)
     92     def __getitem__(self,idxs:int)->Any:
     93         idxs = try_int(idxs)
---> 94         if isinstance(idxs, numbers.Integral): return self.get(idxs)
     95         else: return self.new(self.items[idxs], xtra=index_row(self.xtra, idxs))
     96 

~/workspace/fastai/fastai/vision/data.py in get(self, i)
    347 
    348     def get(self, i):
--> 349         return ImageBBox.create(*_get_size(self.x,i), *self.items[i], classes=self.classes, pad_idx=self.pad_idx)
    350 
    351     def reconstruct(self, t, x):

~/workspace/fastai/fastai/vision/image.py in create(cls, h, w, bboxes, labels, classes, pad_idx, scale)
    335                pad_idx:int=0, scale:bool=True)->'ImageBBox':
    336         "Create an ImageBBox object from `bboxes`."
--> 337         bboxes = tensor(bboxes).float()
    338         tr_corners = torch.cat([bboxes[:,0][:,None], bboxes[:,3][:,None]], 1)
    339         bl_corners = bboxes[:,1:3].flip(1)

~/workspace/fastai/fastai/torch_core.py in tensor(x, *rest)
     68     # XXX: Pytorch bug in dataloader using num_workers>0; TODO: create repro and report
     69     if is_listy(x) and len(x)==0: return tensor(0)
---> 70     res = torch.tensor(x) if is_listy(x) else as_tensor(x)
     71     if res.dtype is torch.int32:
     72         warn('Tensor is int32: upgrading to int64; for better performance use int64 input')

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: double, float, float16, int64, int32, and uint8.
```

This is what lives in the x variable at the moment the error occurs:
![download](https://user-images.githubusercontent.com/2444926/50521162-9ae3d100-0ac4-11e9-8a84-075a8247c6a2.png)

This is what is assigned to x with randomized number of bboxes (when everything works)
![download](https://user-images.githubusercontent.com/2444926/50521223-f1e9a600-0ac4-11e9-8210-86e304f951b9.png)

**Comment by sgugger** [comment] 2018-12-28 17:02
Ugh, since everything is of the same size, I'm guessing numpy wants to make a proper array of the items and fails. Will try to look at this.

**Comment by sgugger** [comment] 2018-12-31 17:32
Should be fixed now.

**Comment by nikolaskaris** [comment] 2019-02-22 21:31
@sgugger Been trying to debug the exact same problem as is mentioned in this post. We're working with a custom dataset and getting the exact same error message still with fast.ai updated.

Our images are nested by label folder like:

images/
----->apple/
------------>000001.jpg
------------>000002.jpg
------------>000003.jpg
------------>.........
----->amazon/
------------>000001.jpg
------------>000002.jpg
------------>000003.jpg
------------>.........
----->bmw/
------------>000001.jpg
------------>000002.jpg
------------>000003.jpg
------------>.........

Many of the image files have the same filename, but are in different subdirectories.

So our annotations file is in the format (we're trying to replicate the Coco docs example):

` {'filename' : ['bboxes', 'labels']}`  

and looks like this: 


<img width="506" alt="screen shot 2019-02-22 at 4 07 43 pm" src="https://user-images.githubusercontent.com/10041710/53271535-cb0eb100-36bc-11e9-9ee9-786567f12563.png">

For example our annotated images look like:

<img width="722" alt="screen shot 2019-02-22 at 4 16 03 pm" src="https://user-images.githubusercontent.com/10041710/53271687-335d9280-36bd-11e9-9859-a8d0177339f1.png">


We cannot get the `label_from_func` to work when we initialize the databunch. All other steps — creating the objectItemList, creating the ItemList by splitting between train and valid sets, work fine. 

When we run `label_from_func` we repeatedly get this error message:

<img width="629" alt="screen shot 2019-02-22 at 4 17 22 pm" src="https://user-images.githubusercontent.com/10041710/53271753-5ee07d00-36bd-11e9-8980-5832299043d0.png">


Link to our code: https://github.com/fellowship/platform-demos2/blob/master/brands/notebooks/bboxes/fastai_bboxes.ipynb



Would very much appreciate direction on this. Thank you for your work, your posts in the forums usually save us from having to post questions like this.

Thanks!

**Comment by sgugger** [comment] 2019-02-22 21:33
Reopening so I don't forget to look at this (maybe sometime this weekend, maybe Monday).

**Comment by sgugger** [comment] 2019-02-25 14:53
Eh, the link to your code is dead. I am trying to reproduce the bug with a similar dataset (our COCO tiny dataset, but with only one bbox per image), I didn't get any error. Can you get me a link to a reproducible example?

**Comment by sgugger** [comment] 2019-03-08 15:57
Re-closing this since we can't reproduce. Please reopen with a reproducible example if needed.

**Closed by sgugger** 2019-03-08 15:57 UTC

**Comment by rothn** [comment] 2020-02-19 06:37
@sgugger Try training a ULMFiT model with integral labels from a Pandas dataframe. This will then happen in the `text_learner.predict()` method.
