### ISSUE TITLE
Fastai Medical Imaging Docs 404

### ISSUE THREAD

**Issue by marii-moe** [fastai/fastai#2979] opened 2020-11-13 06:48 UTC
I noticed that docs.fast.ai/medical.imaging.html gives a 404 Not Found.

**Comment by abhirooptalasila** [comment] 2020-11-16 13:30
Same as #2974

**Comment by hamelsmu** [comment] 2020-11-16 19:18
This is now a a duplicate of https://github.com/fastai/fastai/issues/2989

**Closed by hamelsmu** 2020-11-16 19:18 UTC
Labels: broken-link
