### ISSUE TITLE
Clarify dogs cats example needs num_workers=0 for Google Colab users

### ISSUE THREAD

**Issue by discdiver** [fastai/fastai#931] opened 2018-10-22 02:20 UTC
Memory issues with Google Colab if don't set num_workers=0

**To Reproduce**
Make a Colab project with FastAI V1. 

**Expected behavior**
The model should fit without error.

Instead it gives an error:
`RuntimeError: DataLoader worker (pid xxx) is killed by signal: Bus error. `

**Additional context**
This is caused by PyTorch v1 preview but messes up FastAI users using Colab with GPU following the cats-dogs example. https://github.com/fastai/fastai/blob/master/examples/dogs_cats.ipynb

Resolved by adding _num_workers=0_ in 
`data = ImageDataBunch.from_folder(path, ds_tfms=get_transforms(), tfms=imagenet_norm, size=224)`

Suggest adding num_workers=0 and/or a note for Colab users.

**Comment by sgugger** [comment] 2018-10-22 10:50
Duplicate of #932

**Comment by sgugger** [comment] 2018-10-22 10:50
Duplicate of #932

**Closed by sgugger** 2018-10-22 10:50 UTC
