### ISSUE TITLE
Inconsistent prediction results in multithreading

### ISSUE THREAD

**Issue by siyideng163** [fastai/fastai#2228] opened 2019-07-17 06:45 UTC
I load the model and use it to predict some same sentences with multithreads, but the results shows inconsistent, is it correct?

**Comment by sgugger** [comment] 2019-07-17 15:40
It's impossible to answer the question without more information. What kind of model? On what data? With which code?

**Comment by siyideng163** [comment] 2019-07-18 01:52
text classification model, data is abstract text, python code.
First I fine-tuning the language model, then use the data=load_data(),  learn=text_classifier_learner(data...), lean.load_encoder(encoder), learn.load(model)  to load the text classification model, is the model loaded this way thread-safe?

**Comment by siyideng163** [comment] 2019-07-18 01:53
text classification model, data is abstract text, python code.
First I fine-tuning the language model and text classification model, then use the data=load_data(), learn=text_classifier_learner(data...), lean.load_encoder(encoder), learn.load(model) to load the text classification model, is the model loaded this way thread-safe?

**Comment by sgugger** [comment] 2019-07-18 15:50
Yes, the model is loaded in a thread-safe way AFAICT.
Again, I can't help without code to reproduce.

**Comment by siyideng163** [comment] 2019-07-19 01:55
here is the code and the inconsistent result



[code.zip](https://github.com/fastai/fastai/files/3409068/code.zip)

**Comment by sgugger** [comment] 2019-07-19 14:33
Thanks! I noticed you're passing `senetence.split()` and not just `sentence`, why is that? Normally `learn.predict` will tokenize the text for you.

**Comment by siyideng163** [comment] 2019-07-20 03:01
There is no sentence.split(), you mean sentence.strip()?

**Comment by sgugger** [comment] 2019-07-20 03:12
Ah sorry, I misread. I tried your example and there is a tiny bit of difference when predicting on different thread, no greater than 2e-4, but that could suffice to change the predicted class if it's a close one. So maybe the threading does affect the predictions in some way (though that's more likely to be on the PyTorch side than ours).
Can you try printing the whole predictions, not just the category, to confirm if the difference is small?

**Comment by siyideng163** [comment] 2019-07-20 03:39
This time the former wrong sentence is correct, but there is another wrong sentence:
(Category 0, tensor(0), tensor([9.9946e-01, 5.3958e-04])) Real-life document recognition systems are composed of multiple modules including field extraction, segmentation recognition and language modeling.
(Category 1, tensor(1), tensor([5.3150e-06, 9.9999e-01])) Real-life document recognition systems are composed of multiple modules including field extraction, segmentation recognition and language modeling.
(Category 0, tensor(0), tensor([9.9946e-01, 5.3958e-04])) Real-life document recognition systems are composed of multiple modules including field extraction, segmentation recognition and language modeling.
(Category 0, tensor(0), tensor([9.9946e-01, 5.3958e-04])) Real-life document recognition systems are composed of multiple modules including field extraction, segmentation recognition and language modeling.

**Comment by sgugger** [comment] 2019-07-20 15:32
Ok, the one that is off is really off. That's weird. Do you have something similar when asking for the predictions four times in a row without multi-threading?

**Comment by BramVanroy** [comment] 2019-07-21 19:04
Are you sure that you are actually predicting and not checking the values during a training loop? (in other words, is your model frozen for the predictions) Because it sounds a lot like your model changes a tiny bit each time in a non-deterministic manner.

**Comment by siyideng163** [comment] 2019-07-22 01:26
> Ok, the one that is off is really off. That's weird. Do you have something similar when asking for the predictions four times in a row without multi-threading?

I haven't encountered this problem so far without multi-threading.

**Comment by siyideng163** [comment] 2019-07-22 01:31
> Are you sure that you are actually predicting and not checking the values during a training loop? (in other words, is your model frozen for the predictions; model.eval()) Because it sounds a lot like your model changes a tiny bit each time in a non-deterministic manner.

I use learn.save_encoder() and learn.save() to end the training, when I predict I use the learn.predict(), as illustrated in the documentation, so I also want to know is this way save&load safe.

**Comment by sgugger** [comment] 2019-07-22 13:57
FYI you only need save/load, not the save_encoder/load_encoder part. If you are not encountering the problem in multhithreading, I'd suggest not multi-threading and using batch predictions instead.

In any case I'd need a self-contained reproducible example (not relying on exterior data/model) do be able to fix the issue, as I wasn't able to reproduce with just the code. Closing this for now but please reopen if you manage to build such a self-contained reproducer and I will try to fix the problem.

**Closed by sgugger** 2019-07-22 13:57 UTC
