### ISSUE TITLE
Memory Error when loading data for LM using Textlist.from_folder()

### ISSUE THREAD

**Issue by javedsha** [fastai/fastai#1737] opened 2019-03-03 12:34 UTC
Getting memory error when trying to load data for training language Model.  Below is the code:

data_lm = (TextList.from_folder(path)
             .filter_by_folder(include=['train', 'test', 'unsup'])
             .random_split_by_pct(0.1)
             .label_for_lm()
             .databunch(bs=bs))

The 'unsup' folder contains around 700K documents. Total folder size is 3.5 GB. Total RAM is 112 GB. I think it is happening during pre-processing. I can only complete this step when the number of documents is 200K.

**Provide your installation details**

=== Software ===
python        : 3.6.8
fastai        : 1.0.46
fastprogress  : 0.1.20
torch         : 1.0.1
nvidia driver : 390.77
torch cuda    : 9.0.176 / is available
torch cudnn   : 7301 / is enabled

=== Hardware ===
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 22919MB | Tesla P40

=== Environment ===
platform      : Linux-4.15.0-1037-azure-x86_64-with-debian-buster-sid
distro        : #39-Ubuntu SMP Tue Jan 15 10:24:08 UTC 2019
conda env     : base
python        : /home/user/anaconda3/bin/python
sys.path      :
/home/user/anaconda3/lib/python36.zip
/home/user/anaconda3/lib/python3.6
/home/user/anaconda3/lib/python3.6/lib-dynload
/home/user/anaconda3/lib/python3.6/site-packages

**To Reproduce**
Try to run the above code with 'unsup' folder of size 3.5 GB. And number of documents anywhere between 300K-700K.

**Expected behavior**
MemoryError                               Traceback (most recent call last)
<ipython-input-6-d5da8691cea1> in <module>
      1 data_lm = (TextList.from_folder(path)
      2              .filter_by_folder(include=['train', 'test', 'unsup'])
----> 3              .random_split_by_pct(0.1)
      4              .label_for_lm()
      5              .databunch(bs=bs))

~/anaconda3/lib/python3.6/site-packages/fastai/data_block.py in _inner(*args, **kwargs)
    439             self.valid = fv(*args, from_item_lists=True, **kwargs)
    440             self.__class__ = LabelLists
--> 441             self.process()
    442             return self
    443         return _inner

~/anaconda3/lib/python3.6/site-packages/fastai/data_block.py in process(self)
    493         "Process the inner datasets."
    494         xp,yp = self.get_processors()
--> 495         for ds,n in zip(self.lists, ['train','valid','test']): ds.process(xp, yp, name=n)
    496         #progress_bar clear the outputs so in some case warnings issued during processing disappear.
    497         for ds in self.lists:

~/anaconda3/lib/python3.6/site-packages/fastai/data_block.py in process(self, xp, yp, name)
    665                     p.warns = []
    666                 self.x,self.y = self.x[~filt],self.y[~filt]
--> 667         self.x.process(xp)
    668         return self
    669 

~/anaconda3/lib/python3.6/site-packages/fastai/data_block.py in process(self, processor)
     72         if processor is not None: self.processor = processor
     73         self.processor = listify(self.processor)
---> 74         for p in self.processor: p.process(self)
     75         return self
     76 

~/anaconda3/lib/python3.6/site-packages/fastai/data_block.py in process(self, ds)
     39     def __init__(self, ds:Collection=None):  self.ref_ds = ds
     40     def process_one(self, item:Any):         return item
---> 41     def process(self, ds:Collection):        ds.items = array([self.process_one(item) for item in ds.items])
     42 
     43 PreProcessors = Union[PreProcessor, Collection[PreProcessor]]

~/anaconda3/lib/python3.6/site-packages/fastai/core.py in array(a, dtype, **kwargs)
    260     if np.int_==np.int32 and dtype is None and is_listy(a) and len(a) and isinstance(a[0],int):
    261         dtype=np.int64
--> 262     **return np.array(a, dtype=dtype, **kwargs)**
    263 
    264 class EmptyLabel(ItemBase):

**MemoryError:** 

**Additional context**
I have even tried this with fastai 1.0.35 version. Same error. If I monitor the RAM usage, it doesn't even occupy 8GB, i think it is just trying to allocate huge amount of memory and 112 gb RAM is apparently less.

@sgugger It would be great if you can help me here.

**Comment by javedsha** [comment] 2019-03-04 15:43
Thanks for the reply.
No, I don't see any progress bars in this case. It happens before the progress bars. The RAM increase up-to 8 GB and then boom.

I will give your suggestion a try and report back here.

**Comment by javedsha** [comment] 2019-03-05 16:51
@sgugger I tried you suggestion of setting the defaults.cpu = 1, but it is not working.

Also, I narrow down the issue, and the method 'label_for_lm' is causing it, still not sure why.

Below is the updated code:

`defaults.cpus=1
data_lm = (TextList.from_folder(path)
             .filter_by_folder(include=['train', 'test', 'unsup'])
             .random_split_by_pct(0.1)
             .label_for_lm())`

Any idea what can I try next, this is blocking me.

**Comment by sgugger** [comment] 2019-03-05 17:15
If it doesn't work with `defaults.cpus=1` then it really comes down to the dataset not fitting in RAM. If you don't even see a progress bar appearing, it means the full dataset with all the texts opened doesn't fit in your RAM.
You should try to tokenize it text by text outside of fastai and put it in a csv/dataframe, then you can use `TextList.from_csv` or `TextList.from_df` with `processor=NumericalizeProcessor` to load it.

**Comment by sgugger** [comment] 2019-03-13 17:57
Did this solve your issue? It's been a while with no news, so I'm closing, but feel free to reopen with an update.

**Closed by sgugger** 2019-03-13 17:57 UTC

**Comment by mfojtak** [comment] 2019-03-17 07:13
> If you don't even see a progress bar appearing, it means the full dataset with all the texts opened doesn't fit in your RAM.

I am new to fastai, sorry if I am missing something. I came accross the same issue.
But shouldn't it lazy load data? It is very unlikely that language model data fits in RAM.

**Comment by javedsha** [comment] 2019-03-28 10:55
@sgugger  Sorry for not replying on the thread.
I solve the issue by taking a VM with Big RAM.
As mfojtak is saying everyone is going to hit by this issue. I have not yet tried the solution you propose of doing tokenization outside fast ai.

I am fine in closing this issue, if it doesn't make sense to fix this in fast ai.

Thanks for the help.

**Comment by sgugger** [comment] 2019-03-28 17:12
I don't know the sizes of your datasets, but I've never went OOM, even when tokenizing the whole of wikipedia, so it's a bit of a stretch to say that everyone will be hit by this issue.
Tokenizing gigantic text datasets must be done with a different API to load the data. There are suggestions on the forum for this.

**Comment by karanshgl** [comment] 2019-04-20 11:16
I have hit this issue as well. The problem is that the LMDataBunch is trying to load the entire dataset and label it. This shouldn't be the case, if you are loading the entire dataset at once, what is the point of batching?

**Comment by sgugger** [comment] 2019-04-20 18:31
You can't create your vocab without loading the full dataset. Those aren't images and it takes a lot of texts to get out of RAM...

**Comment by karanshgl** [comment] 2019-04-20 18:44
You can create the vocab by loading one word at a time as well, just keep a dictionary of words with its frequency. I have 300 MB of text files and I can't load them into the memory, having 16GB of RAM. I found a workaround by tokenizing and concatenating the text myself but it shouldn't be this case.

On trying to fix the error, I found that the memory error occurs when the list of strings are converted into a numpy arrays (using the array function in core.py), if you keep them as python lists and concatenate them using the join method, you are able to load more text files.

**Comment by sgugger** [comment] 2019-04-20 18:46
In any case there is nothing I can do without a reproducible script.
If you're not able to load 300Mb of texts, there is clearly a problem. I have no problem loading the whole of wikipedia.

**Comment by karanshgl** [comment] 2019-04-20 18:52
I'm working on a music generation project using transformer network, I'll share the code once the project is finished. Someone could look into it and see if they can solve it, it'll help others facing this issue as well.
