### ISSUE TITLE
Closing since no answer in a while, please reopen to follow-up.

### ISSUE THREAD

**Issue by VadlamudiNaveen** [fastai/fastai#1929] opened 2019-04-05 12:44 UTC
Closing since no answer in a while, please reopen to follow-up.

_Originally posted by @sgugger in https://github.com/fastai/fastai/issues/1440#issuecomment-462047100_

**Comment by VadlamudiNaveen** [comment] 2019-04-05 12:48
hey i have a problem i am running on the windows 10 platform and i am also getting the same problem..
at the method to create the  databunch for specific language model i am getting  the error

BrokenProcessPool                         Traceback (most recent call last)
<ipython-input-43-b1c7e64c25ea> in <module>
      1 path1="D:\\fastai\\data\\imdb_sample\\"
----> 2 data_lm = TextDataBunch.from_csv(path1,'texts.csv')
      3    #  from_csv

~\Anaconda3\envs\fastai_v1\lib\site-packages\fastai\text\data.py in from_csv(cls, path, csv_name, valid_pct, test, tokenizer, vocab, classes, delimiter, header, text_cols, label_cols, label_delim, chunksize, max_vocab, min_freq, mark_fields, include_bos, include_eos, **kwargs)
    220                            label_cols=label_cols, label_delim=label_delim, chunksize=chunksize, max_vocab=max_vocab,
    221                            min_freq=min_freq, mark_fields=mark_fields,
--> 222                            include_bos=include_bos, include_eos=include_eos, **kwargs)
    223 
    224     @classmethod

~\Anaconda3\envs\fastai_v1\lib\site-packages\fastai\text\data.py in from_df(cls, path, train_df, valid_df, test_df, tokenizer, vocab, classes, text_cols, label_cols, label_delim, chunksize, max_vocab, min_freq, mark_fields, include_bos, include_eos, **kwargs)
    201                         TextList.from_df(valid_df, path, cols=text_cols, processor=processor))
    202         if cls==TextLMDataBunch: src = src.label_for_lm()
--> 203         else: src = src.label_from_df(cols=label_cols, classes=classes, label_delim=label_delim)
    204         if test_df is not None: src.add_test(TextList.from_df(test_df, path, cols=text_cols))
    205         return src.databunch(**kwargs)

~\Anaconda3\envs\fastai_v1\lib\site-packages\fastai\data_block.py in _inner(*args, **kwargs)
    463             self.valid = fv(*args, from_item_lists=True, **kwargs)
    464             self.__class__ = LabelLists
--> 465             self.process()
    466             return self
    467         return _inner

~\Anaconda3\envs\fastai_v1\lib\site-packages\fastai\data_block.py in process(self)
    517         "Process the inner datasets."
    518         xp,yp = self.get_processors()
--> 519         for ds,n in zip(self.lists, ['train','valid','test']): ds.process(xp, yp, name=n)
    520         #progress_bar clear the outputs so in some case warnings issued during processing disappear.
    521         for ds in self.lists:

~\Anaconda3\envs\fastai_v1\lib\site-packages\fastai\data_block.py in process(self, xp, yp, name)
    694                     p.warns = []
    695                 self.x,self.y = self.x[~filt],self.y[~filt]
--> 696         self.x.process(xp)
    697         return self
    698

**Comment by sgugger** [comment] 2019-04-05 18:41
I can't help without having the full code you are running and your installation template. Please follow the issue template.

**Comment by sgugger** [comment] 2019-04-15 13:04
Closing this since there was no news in 10 days. Please reopen with a reproducible example.

**Closed by sgugger** 2019-04-15 13:04 UTC
