### ISSUE TITLE
FocalLossFlat causing picking error upon model export

### ISSUE THREAD

**Issue by christymarc** [fastai/fastai#3927] opened 2023-07-19 17:03 UTC
![image](https://github.com/fastai/fastai/assets/70297740/4e6af17e-c355-425b-bb1b-32d14902bfb8)

I was having issues with exporting my model due to a pickling error, then I saw issue #3901 and decided to check the loss function I was using: FocalLossFlat. Seems to not be pickleable. Any solutions?

**Comment by wrignj08** [comment] 2023-08-01 01:23
I've encountered this issue as well. My workaround was to simply change the loss function prior to exporting the model. Alternatively, you can use the Dill module instead of Pickle.

**Comment by dharik-arsath** [comment] 2024-02-27 18:15
any updates regarding this issue? I am facing same issue.

**Comment by kevin-vitro** [comment] 2024-06-24 14:58
duplicate of #3901.  PR #4034 should address this

**Closed** 2024-07-30 22:14 UTC
