### ISSUE TITLE
Errors using fastai 1.0.42 for a classification problem with tabular data containing only continuous columns.

### ISSUE THREAD

**Issue by virilo** [fastai/fastai#1583] opened 2019-02-06 16:53 UTC
**Describe the bug**

I executed lesson 4 notebook without problems.

But when I tried to remove all the categorical columns some errors arise:

	- show_batch call returns: TypeError: len() of a 0-d tensor

	- learn.lr_find executes in 0.0 seconds and returns nothing to plot

	- learn.fit return nan for tran_loss and val_loss

	- learn.predict returns tensor([nan, nan]

I'm having the same issues with my script for my own dataset.

I have tried with cat_names=None and cat_names=[] having the same results.
I also have tried with learning rates of 1e-2, 1e-4 and 1e-6 having no success.

**Provide your installation details**

 No module named fastai.utils.show_install

fastai 1.0.42

**To Reproduce**

```

from fastai.tabular import *
from fastai.datasets import *
import pandas as pd
from fastai.metrics import accuracy

path = untar_data(URLs.ADULT_SAMPLE)
df = pd.read_csv(path/'adult.csv')

df.drop(['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country'],axis=1,inplace=True)
df

dep_var = 'salary'
cat_names = None #['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race']
cont_names = ['age', 'fnlwgt', 'education-num']
procs = [Normalize] #[FillMissing, Categorify, Normalize]

dep_var = 'salary'
cat_names = [] #None #['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race']
cont_names = ['age', 'fnlwgt', 'education-num']
procs = [Normalize] #[FillMissing, Categorify, Normalize]

test = TabularList.from_df(df.iloc[800:1000].copy(), path=path, cat_names=cat_names, cont_names=cont_names)

data = (TabularList.from_df(df, path=path, cat_names=cat_names, cont_names=cont_names, procs=procs)
                           .split_by_idx(list(range(800,1000)))
                           .label_from_df(cols=dep_var)
                           .add_test(test)
                           .databunch())

data.show_batch(rows=10)

'''
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-52-0ef5bf68f37d> in <module>()
----> 1 data.show_batch(rows=10)

~/anaconda3/envs/gender/lib/python3.6/site-packages/fastai/basic_data.py in show_batch(self, rows, ds_type, **kwargs)
    158             ys = [self.train_ds.y.reconstruct(grab_idx(y, i), x=x) for i,x in enumerate(xs)]
    159         else : ys = [self.train_ds.y.reconstruct(grab_idx(y, i)) for i in range(rows)]
--> 160         self.train_ds.x.show_xys(xs, ys, **kwargs)
    161 
    162     def export(self, fname:str='export.pkl'):

~/anaconda3/envs/gender/lib/python3.6/site-packages/fastai/tabular/data.py in show_xys(self, xs, ys)
    135         for i, (x,y) in enumerate(zip(xs,ys)):
    136             res = []
--> 137             for c, n in zip(x.cats, x.names[:len(x.cats)]):
    138                 res.append(str(x.classes[n][c]))
    139             res += [f'{c:.4f}' for c in x.conts] + [str(y)]

~/anaconda3/envs/gender/lib/python3.6/site-packages/torch/tensor.py in __len__(self)
    409     def __len__(self):
    410         if self.dim() == 0:
--> 411             raise TypeError("len() of a 0-d tensor")
    412         return self.shape[0]
    413 

TypeError: len() of a 0-d tensor
'''

learn = tabular_learner(data, layers=[200,100], metrics=accuracy)

learn.lr_find()

learn.recorder.plot()

learn.fit(1, 1e-2)

row = df.iloc[0]

learn.predict(row)
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment] 2019-02-06 19:44
I think this has been fixed in master (when solving a similar issue not so long ago). Can you check with a developer install? I can't reproduce your bug on my side.

**Comment by virilo** [comment] 2019-02-07 12:02
I updated to current master.
I noticed that 'education-num' has NaN values. 

So I removed also this column and now the code is working.
I'm not sure if updating to current master is necessary.

BTW, I tried also to use FillMissing for this column (instead of deleting it), and it causes an error.
I'm opening a new issue.

Thanks a lot for your help.

**Closed** 2019-02-07 12:02 UTC
