### ISSUE TITLE
RuntimeError: shape '[1]' is invalid for input of size 4

### ISSUE THREAD

**Issue by square-1111** [fastai/fastai#2323] opened 2019-09-09 12:59 UTC
Hi, I was trying to implement GAN:
Critic: `basic_critic` and
Generator: 'basic_generator` 
While training the model this issue popped up.
```
/usr/local/lib/python3.6/dist-packages/fastai/vision/gan.py in <lambda>(x)
     13 def AvgFlatten():
     14     "Takes the average of the input."
---> 15     return Lambda(lambda x: x.mean(0).view(1))
     16 
     17 def basic_critic(in_size:int, n_channels:int, n_features:int=64, n_extra_layers:int=0, **conv_kwargs):
```

**Comment by sgugger** [comment] 2019-09-09 13:26
It's impossible to help without a minimal reproducer and the whole error stack trace. If you need help debugging your code and putting together such a minimal example of the bug, please use the [forum](https://forums.fast.ai/).

Closing the issue since I don't know if it's a ug in your code or the library, don't hesitate to reopen with all the necessary info.

**Closed by sgugger** 2019-09-09 13:26 UTC
