### ISSUE TITLE
`Error(s) in loading state_dict for TabularModel:`

### ISSUE THREAD

**Issue by lucharo** [fastai/fastai#3415] opened 2021-07-01 14:22 UTC
Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): YES 
```
# Name                    Version                   Build  Channel
fastai                    2.4                      pypi_0    pypi
fastcore                  1.3.19                   pypi_0    pypi
```
no nbdev

**Describe the bug**
I am running a tabular AE using fastai. I am doing hyperparameter optimization by submitting several jobs in my compute cluster. These jobs are submitted in isolated containers though they all use the same file system. When I launch these jobs in parallel, only one of the jobs succeeds while all the others fail. When I run the jobs sequentially, they all succeed. From the traceback I hypothesise that some temporary file is being read/written from the same location and that's why only one of the model runs succeeds (I don't know the `fastai` internals):
```py
/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/fastai/callback/schedule.py in after_fit(self)
    191         tmp_f = self.path/self.model_dir/'_tmp.pth'
    192         if tmp_f.exists():
--> 193             self.learn.load('_tmp', with_opt=True)
    194             os.remove(tmp_f)
    195 

/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/fastai/learner.py in load(self, file, device, **kwargs)
    357     if self.opt is None: self.create_opt()
    358     file = join_path_file(file, self.path/self.model_dir, ext='.pth')
--> 359     load_model(file, self.model, self.opt, device=device, **kwargs)
    360     return self
    361 

/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/fastai/learner.py in load_model(file, model, opt, with_opt, device, strict)
     49     hasopt = set(state)=={'model', 'opt'}
     50     model_state = state['model'] if hasopt else state
---> 51     get_model(model).load_state_dict(model_state, strict=strict)
     52     if hasopt and with_opt:
     53         try: opt.load_state_dict(state['opt'])

/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
   1050         if len(error_msgs) > 0:
   1051             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
-> 1052                                self.__class__.__name__, "\n\t".join(error_msgs)))
   1053         return _IncompatibleKeys(missing_keys, unexpected_keys)
   1054 

RuntimeError: Error(s) in loading state_dict for TabularModel:
	size mismatch for layers.3.0.weight: copying a param with shape torch.Size([10, 2000]) from checkpoint, the shape in current model is torch.Size([30, 2000]).
	size mismatch for layers.3.2.weight: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([30]).
	size mismatch for layers.3.2.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([30]).
	size mismatch for layers.3.2.running_mean: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([30]).
	size mismatch for layers.3.2.running_var: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([30]).
	size mismatch for layers.4.0.weight: copying a param with shape torch.Size([2000, 10]) from checkpoint, the shape in current model is torch.Size([2000, 30]).
```

<details>

<summary> Find the full traceback below: </summary>

```py
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-22-38016b38ce98> in <module>
----> 1 lr = learn.lr_find(stop_div = True, suggest_funcs = [valley, steep])

/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/fastai/callback/schedule.py in lr_find(self, start_lr, end_lr, num_it, stop_div, show_plot, suggest_funcs)
    281     n_epoch = num_it//len(self.dls.train) + 1
    282     cb=LRFinder(start_lr=start_lr, end_lr=end_lr, num_it=num_it, stop_div=stop_div)
--> 283     with self.no_logging(): self.fit(n_epoch, cbs=cb)
    284     if suggest_funcs is not None:
    285         lrs, losses = tensor(self.recorder.lrs[num_it//10:-5]), tensor(self.recorder.losses[num_it//10:-5])

/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/fastai/learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)
    219             self.opt.set_hypers(lr=self.lr if lr is None else lr)
    220             self.n_epoch = n_epoch
--> 221             self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
    222 
    223     def _end_cleanup(self): self.dl,self.xb,self.yb,self.pred,self.loss = None,(None,),(None,),None,None

/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
    163         try: self(f'before_{event_type}');  f()
    164         except ex: self(f'after_cancel_{event_type}')
--> 165         self(f'after_{event_type}');  final()
    166 
    167     def all_batches(self):

/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/fastai/learner.py in __call__(self, event_name)
    139 
    140     def ordered_cbs(self, event): return [cb for cb in self.cbs.sorted('order') if hasattr(cb, event)]
--> 141     def __call__(self, event_name): L(event_name).map(self._call_one)
    142 
    143     def _call_one(self, event_name):

~/.local/lib/python3.7/site-packages/fastcore/foundation.py in map(self, f, gen, *args, **kwargs)
    152     def range(cls, a, b=None, step=None): return cls(range_of(a, b=b, step=step))
    153 
--> 154     def map(self, f, *args, gen=False, **kwargs): return self._new(map_ex(self, f, *args, gen=gen, **kwargs))
    155     def argwhere(self, f, negate=False, **kwargs): return self._new(argwhere(self, f, negate, **kwargs))
    156     def filter(self, f=noop, negate=False, gen=False, **kwargs):

~/.local/lib/python3.7/site-packages/fastcore/basics.py in map_ex(iterable, f, gen, *args, **kwargs)
    664     res = map(g, iterable)
    665     if gen: return res
--> 666     return list(res)
    667 
    668 # Cell

~/.local/lib/python3.7/site-packages/fastcore/basics.py in __call__(self, *args, **kwargs)
    649             if isinstance(v,_Arg): kwargs[k] = args.pop(v.i)
    650         fargs = [args[x.i] if isinstance(x, _Arg) else x for x in self.pargs] + args[self.maxi+1:]
--> 651         return self.func(*fargs, **kwargs)
    652 
    653 # Cell

/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/fastai/learner.py in _call_one(self, event_name)
    143     def _call_one(self, event_name):
    144         if not hasattr(event, event_name): raise Exception(f'missing {event_name}')
--> 145         for cb in self.cbs.sorted('order'): cb(event_name)
    146 
    147     def _bn_bias_state(self, with_bias): return norm_bias_params(self.model, with_bias).map(self.opt.state)

/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/fastai/callback/core.py in __call__(self, event_name)
     43                (self.run_valid and not getattr(self, 'training', False)))
     44         res = None
---> 45         if self.run and _run: res = getattr(self, event_name, noop)()
     46         if event_name=='after_fit': self.run=True #Reset self.run to True at each end of fit
     47         return res

/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/fastai/callback/schedule.py in after_fit(self)
    191         tmp_f = self.path/self.model_dir/'_tmp.pth'
    192         if tmp_f.exists():
--> 193             self.learn.load('_tmp', with_opt=True)
    194             os.remove(tmp_f)
    195 

/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/fastai/learner.py in load(self, file, device, **kwargs)
    357     if self.opt is None: self.create_opt()
    358     file = join_path_file(file, self.path/self.model_dir, ext='.pth')
--> 359     load_model(file, self.model, self.opt, device=device, **kwargs)
    360     return self
    361 

/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/fastai/learner.py in load_model(file, model, opt, with_opt, device, strict)
     49     hasopt = set(state)=={'model', 'opt'}
     50     model_state = state['model'] if hasopt else state
---> 51     get_model(model).load_state_dict(model_state, strict=strict)
     52     if hasopt and with_opt:
     53         try: opt.load_state_dict(state['opt'])

/projects/gds/chavesrl/condapv/envs/N2D/lib/python3.7/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
   1050         if len(error_msgs) > 0:
   1051             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
-> 1052                                self.__class__.__name__, "\n\t".join(error_msgs)))
   1053         return _IncompatibleKeys(missing_keys, unexpected_keys)
   1054 

RuntimeError: Error(s) in loading state_dict for TabularModel:
	size mismatch for layers.3.0.weight: copying a param with shape torch.Size([10, 2000]) from checkpoint, the shape in current model is torch.Size([30, 2000]).
	size mismatch for layers.3.2.weight: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([30]).
	size mismatch for layers.3.2.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([30]).
	size mismatch for layers.3.2.running_mean: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([30]).
	size mismatch for layers.3.2.running_var: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([30]).
	size mismatch for layers.4.0.weight: copying a param with shape torch.Size([2000, 10]) from checkpoint, the shape in current model is torch.Size([2000, 30]).
```

</details>

**To Reproduce**
The code that I am using is as follows:
```py
from fastai import *
from fastai.tabular.all import *
splits = TrainTestSplitter(test_size=0.2, random_state = 42)(range_of(df))
to = TabularPandas(df.to_pandas(),
                   procs = [],
                   cat_names = [],
                   cont_names = df.columns.tolist(), # these need to be lists
                   y_names = df.columns.tolist(),
                   splits=splits)
dls = to.dataloaders(bs=10**4)
learn = tabular_learner(dls,
                        [500, 500, 2000, emb_sz,2000, 500,500],
                        emb_szs = emb_sz,
                        loss_func = F.mse_loss,
                        opt_func = ranger)
lr = learn.lr_find(stop_div = True, suggest_funcs = [valley, steep]) # <- code fails here
```

I am then using a scheduler tool to launch this script in parallel, which is when the error arises.

**where `df` is just any tabular dataset**, I cannot share mine (corporate)**

**Expected behavior**
I expect this file system clash not to happen and to hopefully be able to run the same notebook/script in parallel with no errors.

**Comment by jph00** [comment] 2021-11-23 22:38
dupe of #3240

**Closed by jph00** 2021-11-23 22:38 UTC
