### ISSUE TITLE
IndexError: "too many indices for array" for Multi-Label-List

### ISSUE THREAD

**Issue by gshashank84** [fastai/fastai#1304] opened 2018-12-07 16:59 UTC
When I was executing learn.fit_one_cycle(1,1e-1, metrics = [acc_02,f_score]) it shows IndexError, by the way the one row of text contains more than one labels.
Please refer Images below for better Understanding.
![screenshot from 2018-12-07 22-18-38](https://user-images.githubusercontent.com/16812816/49661571-681f5d80-fa6f-11e8-8f21-dd423f4e53f0.png)
![screenshot from 2018-12-07 22-18-45](https://user-images.githubusercontent.com/16812816/49661584-71102f00-fa6f-11e8-9178-96fa6b1cd206.png)

Here is a look of DataClasBunch that I have created
![screenshot from 2018-12-07 22-18-57](https://user-images.githubusercontent.com/16812816/49661627-8dac6700-fa6f-11e8-8c34-2100fb337b21.png)

**Comment by gshashank84** [comment] 2018-12-07 18:04
After looking out carefully, I observed that the MultiCategoryList class have not passed argument of init function, as in this case **items must be 'train.csv' where as sep = '|'**, rather it is set as default to None. Please tell me how to pass the argument sepearation in this class through **learn** object?
```
class MultiCategoryList(CategoryListBase):
    "Basic `ItemList` for multi-classification labels."
    _processor=MultiCategoryProcessor
    def __init__(self, items:Iterator, classes:Collection=None, sep:str=None, **kwargs):
        if sep is not None: items = array(csv.reader(items.astype(str), delimiter=sep))
        super().__init__(items, classes=classes, **kwargs)
        self.loss_func = BCEWithLogitsFlat()

    def get(self, i):
        o = self.items[i]
        if o is None: return None
        return MultiCategory(one_hot(o, self.c), [self.classes[p] for p in o], o)
```

**Comment by gshashank84** [comment] 2018-12-07 18:40
Or I do think that at the one_hot method creates error due to multiple integers in the 'o'.
Here res[x] =1 raises IndexError because the x contains multiple integers. So I think there must be change in the code for **get** method in  **MultiCategoryList** Class for Multi-Labels.
```
def one_hot(x:Collection[int], c:int):
    "One-hot encode `x` with `c` classes."
    res = np.zeros((c,), np.float32)
    res[x] = 1.
    return res
```

**Comment by gshashank84** [comment] 2018-12-07 21:46
Do you mind looking at my [Jupyter Notebook](https://github.com/gshashank84/learn-pytorch/blob/master/Text_Tagging.ipynbl) , what I am trying to do is Text Tagging with a given Dataset, where there are Multiple tags for a row of text.

It will be extremely helpful for me if you can suggest where I am doing wrong or their must be changes in code of FASTAI for MultiLabelCategoryList

**Comment by sgugger** [comment] 2018-12-07 22:32
This is weird as your data is exactly as it should be. Can you run the planet example in this [doc notebook](https://github.com/fastai/fastai/blob/master/docs_src/data_block.ipynb) so that I see if the issue comes from your environment?

**Comment by gshashank84** [comment] 2018-12-07 23:22
Thanks for reaching out, I ran both the [Datablock API Notebook](https://github.com/gshashank84/learn-pytorch/blob/master/data_block.ipynb) and the [Lesson-3 Planet Notebook](https://github.com/gshashank84/learn-pytorch/blob/master/lesson3-planet%20(1).ipynb) and It works totally fine.

**Comment by sgugger** [comment] 2018-12-07 23:34
Ok, closing this here and let's go on the forum to debug your code more as it seems the issue is there.

**Closed by sgugger** 2018-12-07 23:34 UTC
