### ISSUE TITLE
Tab completion doesn't show the right type

### ISSUE THREAD

**Issue by muellerzr** [fastai/fastai#2645] opened 2020-08-21 00:20 UTC
For example, when doing `ImageBlock()` and pressing tab to see the parameters, it no longer shows `cls = PILImage`, instead it shows `cls = cls=fastcore.foundation.BypassNewMeta instance`. `CategoryBlock` and `TextBlock` look fine.

**Comment by hamelsmu** [comment] 2020-08-25 14:02
I can confirm that this is no longer the case in the latest fastai

I get this when doing help(ImageBlock)


![image](https://user-images.githubusercontent.com/1483922/91183005-c8b95880-e69f-11ea-8c09-f84c237c3b26.png)

![image](https://user-images.githubusercontent.com/1483922/91183082-e25aa000-e69f-11ea-9d60-d03e1b5ad610.png)

I was also able to verify this in a Colab notebook https://colab.research.google.com/drive/1DSqxFCN3i7rnpZjHuRPgDN9zkpsOUNpK?usp=sharing

I'll go ahead and close this

**Comment by muellerzr** [comment] 2020-08-25 14:05
@hamelsmu problem still persists. Just built with dev, see the attached screenshot:

![image](https://user-images.githubusercontent.com/7831895/91184326-82bdbe00-e6ba-11ea-9dff-4b0dae89f4d9.png)

**Comment by muellerzr** [comment] 2020-08-25 14:10
Looks like this was the case for previous versions as well, which is very very strange. I would have expected it to show `PILImage` here. So perhaps it's just a bug bug. The issue is the class signature shows:
```python
def ImageBlock(cls=PILImage):
```

If I had to guess it's taking the metaclass from `PILBase` for the type hinting rather than the super class that's inheriting it, not sure 100% how to fix that

**Comment by hamelsmu** [comment] 2020-08-25 14:22
Ok the reason I was led astray is that everything shows up correctly for `help(cls)` and `?cls` but oddly not for tab completion!

**Comment by muellerzr** [comment] 2020-08-25 14:39
Continuing this, there's a few more instances of this, and it has to do with the fact that these classes don't have an `__init__` explicitly. A few more are `TensorPoint` and `TensorBBox`. Doing `__class__` will simply show `type`:
```python
TensorPoint.__class__
TensorBBox.__class__
```

**Comment by jph00** [comment] 2020-08-26 18:57
Seems to be a colab bug, so I'll close this. But if you find a workaround for it, do let me know!

**Closed by jph00** 2020-08-26 18:57 UTC
