### ISSUE TITLE
SaveModelCall back failing

### ISSUE THREAD

**Issue by jaideep11061982** [fastai/fastai#1867] opened 2019-03-23 10:28 UTC
**Describe the bug**

I get the below error  possibly while using SaveModel Call back. I dint face this issue earlier any time. 

```
    93         if self.every=="epoch": self.learn.save(f'{self.name}_{epoch}')
     94         else: #every="improvement"
---> 95             current = self.get_monitor_value()
     96             if current is not None and self.operator(current, self.best):
     97                 print(f'Better model found at epoch {epoch} with {self.monitor} value: {current}.')

/opt/conda/lib/python3.6/site-packages/fastai/callbacks/tracker.py in get_monitor_value(self)
     44                   'val_loss':self.learn.recorder.val_losses[-1:][0]}
     45         for i, name in enumerate(self.learn.recorder.names[3:-1]):
---> 46             values[name]=self.learn.recorder.metrics[-1:][0][i]
     47         if values.get(self.monitor) is None:
     48             warn(f'{self.__class__} conditioned on metric `{self.monitor}` which is not available. Available metrics are: {", ".join(map(str, self.learn.recorder.names[1:]))}')

```
**IndexError: list index out of range**
**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment] 2019-03-23 12:02
Please follow the template when filing an issue. I'm not trying to be mean, but we can't fix a bug if we don't see at least:
- the code you're running
- the full error message
- your installation details
and ideally a minimal reproducible example.

This looks like #1858 so it may be fixed in master already. Feel free to reopen with all the necessary details.

**Closed by sgugger** 2019-03-23 12:02 UTC

**Comment by tinhb92** [comment] 2019-04-05 13:00
Hi Sylvain, I faced the same error. This happened when we do not provide metrics to the learner, so self.learn.recorder.metrics is an empty list.  Maybe should check whether metrics is empty first?

**Comment by sgugger** [comment] 2019-04-05 16:56
Seems like a good idea yes! (which is why providing code would have helped solve this bug earlier)

**Comment by jaideep11061982** [comment] 2023-10-28 07:58
> Hi Sylvain, I faced the same error. This happened when we do not provide metrics to the learner, so self.learn.recorder.metrics is an empty list. Maybe should check whether metrics is empty first?

@tinhb92  how to pass custom metric for callback
