### ISSUE TITLE
'NoneType' object has no attribute 'update'

### ISSUE THREAD

**Issue by nicolavivarelli** [fastai/fastai#1646] opened 2019-02-15 08:54 UTC
Hi, I tried to apply ULMFIT to many datasets but everytime I run textlmdatabunch.from_csv or from_df this error always occurs: `AttributeError: 'NoneType' object has no attribute 'update'`.

I tried to reproduce EXACTLY what this article [https://medium.com/datadriveninvestor/deep-learning-with-python-and-fast-ai-part-2-nlp-classification-with-transfer-learning-e7aaf7514e04](url) said, except for `data_lm = TextLMDataBunch.from_csv(path, 'train.csv')` instead of `data_lm = TextLMDataBunch.from_csv(path, valid='test')`

This is the code i try to run:
`from fastai import *
from fastai.text import *
from fastai.core import *

!tar -xvzf yelp_review_polarity_csv.tgz

path = Path('yelp_review_polarity_csv')

train_csv = path/'train.csv'
train = pd.read_csv(train_csv, header=None)
train.head()

valid_csv = path/'test.csv'
valid = pd.read_csv(valid_csv, header=None)
valid.head()

data_lm = TextLMDataBunch.from_csv(path, 'train.csv')`

and this is the error:
`AttributeError                            Traceback (most recent call last)
<ipython-input-16-289b6aba02de> in <module>()
----> 1 data_lm = TextLMDataBunch.from_csv(path, 'train.csv')

C:\Users\ev3nicvivare\AppData\Roaming\Python\Python36\site-packages\fastai\text\data.py in from_csv(cls, path, csv_name, valid_pct, test, tokenizer, vocab, classes, header, text_cols, label_cols, label_delim, **kwargs)
    180         test_df = None if test is None else pd.read_csv(Path(path)/test, header=header)
    181         return cls.from_df(path, train_df, valid_df, test_df, tokenizer, vocab, classes, text_cols,
--> 182                            label_cols, label_delim, **kwargs)
    183 
    184     @classmethod

C:\Users\ev3nicvivare\AppData\Roaming\Python\Python36\site-packages\fastai\text\data.py in from_df(cls, path, train_df, valid_df, test_df, tokenizer, vocab, classes, text_cols, label_cols, label_delim, **kwargs)
    165         src = ItemLists(path, TextList.from_df(train_df, path, cols=text_cols, processor=processor),
    166                         TextList.from_df(valid_df, path, cols=text_cols, processor=processor))
--> 167         src = src.label_for_lm() if cls==TextLMDataBunch else src.label_from_df(cols=label_cols, classes=classes, sep=label_delim)
    168         if test_df is not None: src.add_test(TextList.from_df(test_df, path, cols=text_cols))
    169         return src.databunch(**kwargs)

C:\Users\ev3nicvivare\AppData\Roaming\Python\Python36\site-packages\fastai\data_block.py in _inner(*args, **kwargs)
    348             self.valid = fv(*args, **kwargs)
    349             self.__class__ = LabelLists
--> 350             self.process()
    351             return self
    352         return _inner

C:\Users\ev3nicvivare\AppData\Roaming\Python\Python36\site-packages\fastai\data_block.py in process(self)
    392     def process(self):
    393         xp,yp = self.get_processors()
--> 394         for i,ds in enumerate(self.lists): ds.process(xp, yp, filter_missing_y=i==0)
    395         return self
    396 

C:\Users\ev3nicvivare\AppData\Roaming\Python\Python36\site-packages\fastai\data_block.py in process(self, xp, yp, filter_missing_y)
    483             filt = array([o is None for o in self.y])
    484             if filt.sum()>0: self.x,self.y = self.x[~filt],self.y[~filt]
--> 485         self.x.process(xp)
    486         return self
    487 

C:\Users\ev3nicvivare\AppData\Roaming\Python\Python36\site-packages\fastai\data_block.py in process(self, processor)
     58         if processor is not None: self.processor = processor
     59         self.processor = listify(self.processor)
---> 60         for p in self.processor: p.process(self)
     61         return self
     62 

C:\Users\ev3nicvivare\AppData\Roaming\Python\Python36\site-packages\fastai\text\data.py in process(self, ds)
    243         ds.items = _join_texts(ds.items, self.mark_fields)
    244         tokens = []
--> 245         for i in progress_bar(range(0,len(ds),self.chunksize), leave=False):
    246             tokens += self.tokenizer.process_all(ds.items[i:i+self.chunksize])
    247         ds.items = tokens

C:\Users\ev3nicvivare\AppData\Roaming\Python\Python36\site-packages\fastprogress\fastprogress.py in __iter__(self)
     61     def __iter__(self):
     62         self.on_iter_begin()
---> 63         self.update(0)
     64         try:
     65             for i,o in enumerate(self._gen):

C:\Users\ev3nicvivare\AppData\Roaming\Python\Python36\site-packages\fastprogress\fastprogress.py in update(self, val)
     76             self.pred_t = 0
     77             self.last_v,self.wait_for = 0,1
---> 78             self.update_bar(0)
     79         elif val >= self.last_v + self.wait_for or val == self.total:
     80             cur_t = time()

C:\Users\ev3nicvivare\AppData\Roaming\Python\Python36\site-packages\fastprogress\fastprogress.py in update_bar(self, val)
     95             warn("Your generator is empty.")
     96             self.on_update(0, '100% [0/0]')
---> 97         else: self.on_update(val, f'{100 * val/self.total:.2f}% [{val}/{self.total} {elapsed_t}<{remaining_t}{end}]')
     98 
     99 

C:\Users\ev3nicvivare\AppData\Roaming\Python\Python36\site-packages\fastprogress\fastprogress.py in on_update(self, val, text, interrupted)
    163         self.progress = html_progress_bar(val, self.total, text, interrupted)
    164         if self.display:
--> 165             self.out.update(HTML(self.progress))
    166         elif self.parent is not None: self.parent.show()
    167 

AttributeError: 'NoneType' object has no attribute 'update'`

What could it be?
Also, when i run 
from fastai import *
from fastai.text import *
from fastai.core import *

i get this:
C:\Users\ev3nicvivare\AppData\Local\Continuum\Anaconda3\lib\importlib\_bootstrap.py:205: RuntimeWarning: cymem.cymem.Pool size changed, may indicate binary incompatibility. Expected 48 from C header, got 64 from PyObject
  return f(*args, **kwds)
C:\Users\ev3nicvivare\AppData\Local\Continuum\Anaconda3\lib\importlib\_bootstrap.py:205: RuntimeWarning: cymem.cymem.Address size changed, may indicate binary incompatibility. Expected 24 from C header, got 40 from PyObject
  return f(*args, **kwds)

What does it mean?
Thank you

**Comment by sgugger** [comment] 2019-02-15 15:08
The issue seems to be with fastprogress. We'd need to know your installation details to help, and also what python you're using (jupyter notebook, console, other editor?) Please copy paste the result of
```
from fastai.utils.show_install import *
show_install()
```

**Comment by nicolavivarelli** [comment] 2019-02-18 08:07
I'm using Jupyter Notebook, but strangely if I try to run your code i get 'No module named 'fastai.utils.show_install'

**Comment by sgugger** [comment] 2019-02-18 14:34
That means you have a really old version of fastai, so update to the latest one first.

**Comment by nicolavivarelli** [comment] 2019-02-19 16:50
This is the result of show_install():


```text
=== Software === 
python       : 3.6.1
fastai       : 1.0.45
fastprogress : 0.1.19
torch        : 1.0.1
torch cuda   : None / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Windows-10-10.0.17134-SP0
conda env    : Unknown
python       : C:\Users\ev3nicvivare\AppData\Local\Continuum\Anaconda3\python.exe
sys.path     : 
C:\Users\ev3nicvivare\AppData\Local\Continuum\Anaconda3\python36.zip
C:\Users\ev3nicvivare\AppData\Local\Continuum\Anaconda3\DLLs
C:\Users\ev3nicvivare\AppData\Local\Continuum\Anaconda3\lib
C:\Users\ev3nicvivare\AppData\Local\Continuum\Anaconda3
C:\Users\ev3nicvivare\AppData\Roaming\Python\Python36\site-packages
C:\Users\ev3nicvivare\AppData\Local\Continuum\Anaconda3\lib\site-packages
C:\Users\ev3nicvivare\AppData\Local\Continuum\Anaconda3\lib\site-packages\Sphinx-1.5.6-py3.6.egg
C:\Users\ev3nicvivare\AppData\Local\Continuum\Anaconda3\lib\site-packages\win32
C:\Users\ev3nicvivare\AppData\Local\Continuum\Anaconda3\lib\site-packages\win32\lib
C:\Users\ev3nicvivare\AppData\Local\Continuum\Anaconda3\lib\site-packages\Pythonwin
C:\Users\ev3nicvivare\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\extensions
C:\Users\ev3nicvivare\.ipython
no supported gpus found on this system
```

Please make sure to include opening/closing ``` when you paste into forums/github to make the reports appear formatted as code sections.

**Comment by sgugger** [comment] 2019-02-21 14:33
Not sure what could be the reason. Did you try to pass the `text_cols` and `label_cols`, just in case the default don't correspond to your table?

**Comment by sgugger** [comment] 2019-03-08 15:58
Closing since it's been two weeks and I can't reproduce the bug. Feel free to re-open with a reproducible example on master.

**Closed by sgugger** 2019-03-08 15:58 UTC

**Comment by bingoong** [comment] 2019-04-04 05:07
I'm having a similar error message when I run lesson2_download.ipynb at verify_images(path/c, delete=True, max_size=500)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-61-341706d262d1> in <module>()
      1 for c in classes:
      2     print(c)
----> 3     verify_images(path/c, delete=True, max_size=500)

/Users/bingong1/anaconda/lib/python3.6/site-packages/fastai/vision/data.py in verify_images(path, delete, max_workers, max_size, recurse, dest, n_channels, interp, ext, img_format, resume, **kwargs)
    251     func = partial(verify_image, delete=delete, max_size=max_size, dest=dest, n_channels=n_channels, interp=interp,
    252                    ext=ext, img_format=img_format, resume=resume, **kwargs)
--> 253     parallel(func, files, max_workers=max_workers)
    254 
    255 class ImageList(ItemList):

/Users/bingong1/anaconda/lib/python3.6/site-packages/fastai/core.py in parallel(func, arr, max_workers)
    325         with ProcessPoolExecutor(max_workers=max_workers) as ex:
    326             futures = [ex.submit(func,o,i) for i,o in enumerate(arr)]
--> 327             for f in progress_bar(concurrent.futures.as_completed(futures), total=len(arr)): pass
    328 
    329 def subplots(rows:int, cols:int, imgsize:int=4, figsize:Optional[Tuple[int,int]]=None, title=None, **kwargs):

/Users/bingong1/anaconda/lib/python3.6/site-packages/fastprogress/fastprogress.py in __iter__(self)
     62     def __iter__(self):
     63         self.on_iter_begin()
---> 64         self.update(0)
     65         try:
     66             for i,o in enumerate(self._gen):

/Users/bingong1/anaconda/lib/python3.6/site-packages/fastprogress/fastprogress.py in update(self, val)
     77             self.pred_t = 0
     78             self.last_v,self.wait_for = 0,1
---> 79             self.update_bar(0)
     80         elif val >= self.last_v + self.wait_for or val == self.total:
     81             cur_t = time()

/Users/bingong1/anaconda/lib/python3.6/site-packages/fastprogress/fastprogress.py in update_bar(self, val)
     96             warn("Your generator is empty.")
     97             self.on_update(0, '100% [0/0]')
---> 98         else: self.on_update(val, f'{100 * val/self.total:.2f}% [{val}/{self.total} {elapsed_t}<{remaining_t}{end}]')
     99 
    100 

/Users/bingong1/anaconda/lib/python3.6/site-packages/fastprogress/fastprogress.py in on_update(self, val, text, interrupted)
    167     def on_update(self, val, text, interrupted=False):
    168         self.progress = html_progress_bar(val, self.total, text, interrupted)
--> 169         if self.display: self.out.update(HTML(self.progress))
    170         elif self.parent is not None: self.parent.show()
    171 

AttributeError: 'NoneType' object has no attribute 'update'

when I run show_install(), the output is
```text
=== Software === 
python       : 3.6.1
fastai       : 1.0.51
fastprogress : 0.1.20
torch        : 1.0.1.post2
torch cuda   : None / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Darwin-17.7.0-x86_64-i386-64bit
conda env    : Unknown
python       : /Users/bingong1/anaconda/bin/python
sys.path     : 
/Users/bingong1/anaconda/lib/python36.zip
/Users/bingong1/anaconda/lib/python3.6
/Users/bingong1/anaconda/lib/python3.6/lib-dynload
/Users/bingong1/anaconda/lib/python3.6/site-packages
/Users/bingong1/anaconda/lib/python3.6/site-packages/Mako-1.0.7-py3.6.egg
/Users/bingong1/anaconda/lib/python3.6/site-packages/Sphinx-1.5.6-py3.6.egg
/Users/bingong1/anaconda/lib/python3.6/site-packages/aeosa
/Users/bingong1/anaconda/lib/python3.6/site-packages/IPython/extensions
/Users/bingong1/.ipython
no supported gpus found on this system
```

Please make sure to include opening/closing ``` when you paste into forums/github to make the reports appear formatted as code sections.

Any suggestions what might be the problem?

**Comment by sgugger** [comment] 2019-04-04 13:14
Can't reproduce. Are you sure your folder contain images?

**Comment by bingoong** [comment] 2019-04-05 02:53
I was able to run "data.show_batch(rows=3, figsize=(7,8))" and see the images.

**Comment by sandalaphon** [comment] 2019-05-08 09:29
'''no supported gpus found on this system'''
You need a gpu.
I got the same error trying to run this on my laptop but it ran fine on remote gpu.

**Comment by bingoong** [comment] 2019-05-08 09:42
Oh! That would be it.
