### ISSUE TITLE
The train.csv and test.csv only have one column.

### ISSUE THREAD

**Issue by KaitouKK** [fastai/fastai#1058] opened 2018-11-02 03:05 UTC
When I run the code 
'if len(df.columns) == 1:
        labels = []' 
in create_tok.py, the labels is always null. So I checked the train.csv and test.csv which I have downloaded in the step of  0.prepare the wikipedia in /data/wiki/en, and found that the column of train.csv and test.csv is 1. So the labels is null.
Also when I run the create_tok.py, it is always stoped at the 3rd chunksize like the following:
 
![5aie990o r 2i n by _ f](https://user-images.githubusercontent.com/18696649/47891669-36730f80-de8f-11e8-850e-9d4542404f1f.png)

**Comment by sgugger** [comment] 2018-11-02 03:12
I'm not sure what the problem is as you didn't give much details. I don't really see why having only zero-labels when you didn't specify any is a non-intended behavior. I'm closing this here as it should be discussed on the [forum](https://forums.fast.ai/). Please explain to us more in detail what your problem is.

**Closed** 2018-11-02 03:13 UTC
