### ISSUE TITLE
Expected object of type Variable[torch.cuda.LongTensor] in model.py

### ISSUE THREAD

**Issue by BSalita** [fastai/fastai#71] opened 2017-12-27 19:27 UTC
Running on Windows 10 appears to expose a type mismatch issue in model.py. 

RuntimeError: Expected object of type Variable[torch.cuda.LongTensor] but found type Variable[torch.cuda.IntTensor] for argument #1 'target'​

Report on fastai forum: http://forums.fast.ai/t/windows-10-installation-notes-windows-command-and-wsl-bash/6500/54?u=bsalita

Patch and explanation: http://forums.fast.ai/t/windows-10-installation-notes-windows-command-and-wsl-bash/6500/55?u=bsalita

Is there a static type analyzer which can be run on fastai code to catch these kinds of errors?

**Comment by jph00** [comment] 2017-12-28 00:42
The solution you proposed assumes we're on CUDA, which may not be the case. I'll see if I can think of something...

**Comment by jph00** [comment] 2017-12-28 01:01
I think the right fix is to have the dataset return the correct type (np.int32) in the first place. Closing this issue since Windows isn't something I'm ready to officially support just yet. But if you create a fix that works on Linux and Windows with and without CUDA then I'll certainly consider merging it.

**Closed by jph00** 2017-12-28 01:01 UTC

**Comment by BSalita** [comment] 2017-12-28 15:33
I'm wondering why the issue is showing up at all? Seems like it should show up everywhere or nowhere. I'm guessing the difference is in some recent change to pytorch.

**Comment by jph00** [comment] 2017-12-28 16:02
It's because on Windows the int sizes are different.

**Comment by BSalita** [comment] 2017-12-29 23:04
I've done some research. In python 3, `int` is unlimited [sic] in magnitude on all platforms. numpy has a different set of numeric types which are similar to C. The size of a Tensor is the same on all platforms.

As you've stated, the issue is that the dataset returns a numpy data type (np.int) which has implementation dependent sizes. The size can differ according to machine architecture, OS, C compiler, and other factors. You can't make any assumptions about the size of an np.int. The size could even differ on the same system and same C compiler. Using np.int32 would make for consistent processing across all platforms -- all platforms would raise an error because a LongTensor is expected. LongTensor's are always 64-bits.

There's at least three possible solutions:
1. Have the dataset return np.int64.
2. For places where LongTensor is expected, such as in model.py, force the type to 64-bit using `variable.int64()`. This works for both cpu and gpu types.
3. Change the type earlier in the call sequence. This would help a static type checker. It would be more efficient if the variable undergoes multiple type changes.

http://pytorch-zh.readthedocs.io/en/latest/tensors.html
https://docs.scipy.org/doc/numpy-1.12.0/user/basics.types.html

**Comment by BSalita** [comment] 2017-12-30 10:22
The maintainer of pytorch for Windows, peterjc123, says "The Windows PRs are actively merged. The official Windows CI is near to be setup, and the official package is planned for 0.4.0." at https://github.com/pytorch/pytorch/issues/494#issuecomment-350527200

pytorch 1.3 + CUDA 9.0 for Windows is available and works for me.

**Comment by jph00** [comment] 2017-12-30 21:04
I think the .long() solution is a good one - I can't see any reason that this should cause problems on Linux or CPU. I'll try it out.

BTW, I'm well aware of the status of pytorch on Windows - the issue is whether I'm ready to support fastai on Windows :) . I suspect I'll endeavor to support it officially after 0.4 is out and Windows CI is done for pytorch, but where we have simple clear solutions to problems in the meantime I'll include them.

**Comment by davideboschetto** [comment] 2018-03-06 12:40
Just to let you know, was playing with this on Win7 and ended up with the same problem!
Will gladly wait for now, but I'm really hoping I'll be able to use Windows for Part2-2018!

**Comment by nikos-h** [comment] 2018-03-25 02:39
@davideboschetto Where did you change to y.long()?

    cat, cont, y = next(iter(md.trn_dl))
    cat, cont, y = Variable(cat), Variable(cont), Variable(y).long()
    pred = model(cat, cont)
    for p, true in zip(pred.data.numpy(), torch.max(y, 1)[0].data):
        print('pred log probs: {} -- True: {}'.format(p, true))

Then run lr_find() yields the error. y is set to a long so don't know where to change it.
