### ISSUE TITLE
RuntimeError: received 0 items of ancdata

### ISSUE THREAD

**Issue by kevinbird15** [fastai/fastai#23] opened 2017-11-12 06:46 UTC
I'm running into an issue when trying to predict with the dn models.  From what I've researched it seems maybe related to this issue https://github.com/pytorch/pytorch/issues/973 from the pytorch forums and the workaround there was setting the number of workers to 0.  If anybody else has encountered this or knows how to set the number of workers to 0, I tried setting num_workers on ImageClassifierData to 0, but that didn't solve the issue for me.  I don't know if there is anything that can be done on the fastai side since it appears to be a pytorch problem, but I figured it's at least worth documenting and if anybody has any ideas they can look into it.  

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-c94a818ff72b> in <module>()
     10     learn[i].fit(0.01, 3, cycle_len=1, cycle_mult=4)
     11 
---> 12     test_predictions = learn[i].predict(is_test=True)
     13 
     14     #tmp_log_preds,tmp_y = learn[i].TTA(is_test=True, n_aug=50)

~/fastaip1v2/fastai/courses/dl1/fastai/learner.py in predict(self, is_test)
    136         self.load('tmp')
    137 
--> 138     def predict(self, is_test=False): return self.predict_with_targs(is_test)[0]
    139 
    140     def predict_with_targs(self, is_test=False):

~/fastaip1v2/fastai/courses/dl1/fastai/learner.py in predict_with_targs(self, is_test)
    140     def predict_with_targs(self, is_test=False):
    141         dl = self.data.test_dl if is_test else self.data.val_dl
--> 142         return predict_with_targs(self.model, dl)
    143 
    144     def predict_dl(self, dl): return predict_with_targs(self.model, dl)[0]

~/fastaip1v2/fastai/courses/dl1/fastai/model.py in predict_with_targs(m, dl)
    115     if hasattr(m, 'reset'): m.reset()
    116     preda,targa = zip(*[(get_prediction(m(*VV(x))),y)
--> 117                         for *x,y in iter(dl)])
    118     return to_np(torch.cat(preda)), to_np(torch.cat(targa))
    119 

~/fastaip1v2/fastai/courses/dl1/fastai/model.py in <listcomp>(.0)
    114     m.eval()
    115     if hasattr(m, 'reset'): m.reset()
--> 116     preda,targa = zip(*[(get_prediction(m(*VV(x))),y)
    117                         for *x,y in iter(dl)])
    118     return to_np(torch.cat(preda)), to_np(torch.cat(targa))

~/fastaip1v2/fastai/courses/dl1/fastai/dataset.py in __next__(self)
    226         if self.i>=len(self.dl): raise StopIteration
    227         self.i+=1
--> 228         return next(self.it)
    229 
    230     @property

~/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    193         while True:
    194             assert (not self.shutdown and self.batches_outstanding > 0)
--> 195             idx, batch = self.data_queue.get()
    196             self.batches_outstanding -= 1
    197             if idx != self.rcvd_idx:

~/anaconda3/envs/fastai/lib/python3.6/multiprocessing/queues.py in get(self)
    335             res = self._reader.recv_bytes()
    336         # unserialize the data after having released the lock
--> 337         return _ForkingPickler.loads(res)
    338 
    339     def put(self, obj):

~/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/multiprocessing/reductions.py in rebuild_storage_fd(cls, df, size)
     68         fd = multiprocessing.reduction.rebuild_handle(df)
     69     else:
---> 70         fd = df.detach()
     71     try:
     72         storage = storage_from_cache(cls, fd_id(fd))

~/anaconda3/envs/fastai/lib/python3.6/multiprocessing/resource_sharer.py in detach(self)
     56             '''Get the fd.  This should only be called once.'''
     57             with _resource_sharer.get_connection(self._id) as conn:
---> 58                 return reduction.recv_handle(conn)
     59 
     60 

~/anaconda3/envs/fastai/lib/python3.6/multiprocessing/reduction.py in recv_handle(conn)
    180         '''Receive a handle over a local connection.'''
    181         with socket.fromfd(conn.fileno(), socket.AF_UNIX, socket.SOCK_STREAM) as s:
--> 182             return recvfds(s, 1)[0]
    183 
    184     def DupFd(fd):

~/anaconda3/envs/fastai/lib/python3.6/multiprocessing/reduction.py in recvfds(sock, size)
    159             if len(ancdata) != 1:
    160                 raise RuntimeError('received %d items of ancdata' %
--> 161                                    len(ancdata))
    162             cmsg_level, cmsg_type, cmsg_data = ancdata[0]
    163             if (cmsg_level == socket.SOL_SOCKET and

RuntimeError: received 0 items of ancdata
```

**Comment by yanneta** [comment] 2017-11-12 15:56
Can you please also share how you define the data and learner.
Thanks!

**Comment by kevinbird15** [comment] 2017-11-12 16:23
```
arch=[dn161,dn169,dn201]
tfms = []
data = []
learn = []

for i in range(len(arch)):
    tfms.append(tfms_from_model(arch[i], sz, aug_tfms=transforms_side_on, max_zoom=1.15))
    data.append(ImageClassifierData.from_paths(path, tfms=tfms[i], test_name="test", bs=bs))
    learn.append(ConvLearner.pretrained(arch[i],data[i], precompute=True))
```

**Comment by yanneta** [comment] 2017-11-12 17:02
Can you ran each of them independently?

**Comment by kevinbird15** [comment] 2017-11-12 17:04
Are you wanting me to post them independently or are you asking?

I tried doing dn121 by itself and got the same error.  

I am trying to do it with `precompute=False` now which I think will be a work-around just slower.

**Comment by yanneta** [comment] 2017-11-12 17:40
One thing is that if you are using different networks you have to delete
the tmp file in between runs.

**Comment by kevinbird15** [comment] 2017-11-12 18:43
Can you elaborate on that?  Doesn't each model generate its own folder in the tmp directory and it really shouldn't matter when you change between two separate architectures?  Is that what you mean by different networks?

**Comment by yanneta** [comment] 2017-11-12 20:10
You are right.  Different architectures don't make new folder but they make
new files.

**Comment by jph00** [comment] 2017-11-13 17:32
Does it go away if you reboot?

**Comment by kevinbird15** [comment] 2017-11-13 18:44
I'll let you know when I get off work. I set precompute to false and that seems to have fixed the issue for me. I'll see if I can still recreate the issue after a reboot tonight.

**Comment by jph00** [comment] 2017-11-13 23:52
It might also be a problem with you `tmp` folder.

**Comment by hiromis** [comment] 2017-11-15 23:49
I am encountering the same issue here. Here is the sequence of the event that led to the issue:
1. I made a submission file for the Planet competition. At this point, there was no error when running `learn.TTA(is_test=True)`
2. Noticed that I did not add images from test-jpg-additional.tar.7z
3. Added additional test images to test-jpg folder. 
4. Recreated the model with a new ImageClassifierData and loaded the saved weights
5. `learn.TTA(is_test=True)` failed so deleted /tmp. 

Here are things I have tried:
- Deleted /tmp folder
- Verified that `precompute` is not set to True
- Restarted kernel, jupyter notebook, AWS (also removed /tmp folder before running)
- Created a simpler version of the notebook I am having an issue with and still get the same error https://github.com/hiromis/fastai-workspace/blob/master/Lesson2-Copy1.ipynb

None of the above made any difference. `learn.TTA()` (the validation TTA) runs with no issues in the original notebook.

I am starting to consider http://wiki.fast.ai/index.php/Starting_Over_with_AWS and try out the new AMI for this class as I have a feeling that it is a issue in the environment rather than data or code...

**Comment by jph00** [comment] 2017-11-16 00:49
Creating a new AWS instance sounds like the best next step - let us know if that resolves it.

**Comment by hiromis** [comment] 2017-11-16 02:26
On a brand new AWS instance with fastai-part1v2-p2 (ami-8c4288f4), the Lesson2-Copy1.ipynb still gives the same error. I downloaded the planet directly from Kaggle rather than copying from the old instance.

The next step seems to be deleting the additional test data since that was the beginning of this all.

**Comment by apiltamang** [comment] 2017-11-16 02:50
I have a crazy proposition...
Started seeing this once I moved the pictures from test-jpg-additional into the test-jpg folder. Initially there'd be 40,669 images, for which learn.TTA(is_test=True) works fine. As soon as i copied the extra ~20,000 images into the test.jpg folder, the system goes kaboom!

Can you try removing all those additional images? Simply cd into test-jpg, and run "rm file_*.jpg". This ought to remove the additional images. Doing that helped me avoid the above exception.

Of course that doesn't mean I can make any submissions :( !

**Comment by apiltamang** [comment] 2017-11-16 03:11
another update:

if you use num_workers=0 while instantiating the 'ImageClassifierData.from_csv(...)' method, then the exception won't be thrown.

It'll take about 15 min. though to finish getting predictions. So likely not a good soln.

**Comment by hiromis** [comment] 2017-11-16 03:21
@apiltamang I don't think the proposition is crazy at all.

https://github.com/hiromis/fastai-workspace/blob/master/Lesson2-Broken.ipynb

So, it's the data. That, we know.

**Comment by apiltamang** [comment] 2017-11-16 03:27
@hiromis Glad you could reproduce it!

I suppose one could train all they want, then save it to a file, and later reinstantiate a model/data with 0 num_workers, then apply it for the training. I see that as the only side-step for the moment. Good luck!

**Comment by hiromis** [comment] 2017-11-16 04:49
Thanks, @apiltamang! 

I probably should have tried removing the data first before resorting to a new AWS instance 😅 But I guess hindsight is 50/50.

I tried running TTA on images in test-jpg-additional.tar.7z without changing num_workers, and that also ran fine. So we could just combine the predictions after running them separately.

**Comment by sampathweb** [comment] 2017-11-16 15:20
I was able to reproduce the problem in a New AWS EC2 instance I spun up and reproduced the steps from @hiromis.  

The problem is it's hitting the number of open file descriptors (fds).  It's set to a limit of 1024 by default.  I increased it to 2048 and it resolved the issue.  Can you try and let me know?

<img width="329" alt="screen shot 2017-11-16 at 7 17 55 am" src="https://user-images.githubusercontent.com/1437573/32898963-7ecd2d5c-ca9e-11e7-9202-57450ca6268c.png">

You can do in Jupyter Notebook or do it in the Terminal (Before launching Jupyter).  Please note that setting is only for that terminal session (which is good for now - you are not changing any global setting for the system)

We can change the default, and usually done when we want more fds (in Socket programming).  Let me know if this works and we can change the default.

**Comment by sampathweb** [comment] 2017-11-16 17:12
For reference, in my Docker container that was based on `nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04`, the `ulimit -n` is 1048576.  That may be why I don't see this problem.  Hopefully increasing the ulimit resolves it for you.  

Lots of posts online on how to change ulimit on your system.  If this works, someone can check with a devops person post what's the best way to set it on startup.

**Comment by jph00** [comment] 2017-11-16 17:40
Good sleuthing team! Sounds like I may have to rebuild the AMIs. What a pain :(

**Comment by sampathweb** [comment] 2017-11-16 18:07
@jph00 - Once it's confirmed that it works, I would suggest you just give us a script or command to increase `ulimit`.  Lots of them out there online, so I am hesitant to suggest.  Giving a new AMI doesn't help most of us that are actively using the machines and have local notebooks.  Might be useful to create one towards the end of the course for the future MOOC participants..

**Comment by hiromis** [comment] 2017-11-16 21:44
@sampathweb, thank you so much for solving the mystery for me!! 

This is what it looks like if I run the shell command from jupyter notebok:
<img width="347" alt="screen shot 2017-11-17 at 6 34 13 am" src="https://user-images.githubusercontent.com/5401333/32917084-60b36f0c-cb61-11e7-88cd-f14a41fb8d44.png">

And I think I know what's going wrong because in the past, I tried setting an environment variable from jupyter notebook using `!` and the change did not take. It seems as though each command you execute via `!` is backed by different session. I was able to set an environment in a "Pythony" way instead, so maybe we can do something similar here .

I will look into how we can do this in python.

Thanks once again!!

**Comment by sampathweb** [comment] 2017-11-16 22:23
@hiromis Try it from your Terminal before launching Jupyter notebook.  Let us know if that works.  Looks like it worked for one person who had similar error - http://forums.fast.ai/t/runtime-error-while-running-prediction-on-planet-dataset/7944/3

**Comment by pani6me** [comment] 2017-11-16 22:29
Thank you @sampathweb . Ran into the same issue in paperspace. Increased the limit from command-line worked (from within Jupyter Notebook didn't work.)

**Comment by hiromis** [comment] 2017-11-16 23:01
@sampathweb It works from Terminal 👍 

I also got it to work from jupyter notebook using python:

<img width="810" alt="screen shot 2017-11-17 at 7 50 59 am" src="https://user-images.githubusercontent.com/5401333/32920302-1ce5956a-cb6c-11e7-9943-cd2b4e2b7dc0.png">

So maybe we can check the `ulimit -n` value somewhere in the fastai library and up it a bit if it's considered not enough. Or if that's too invasive, we can display a warning. What does everybody think?


Putting the actual code for copying and pasting:
```
import resource
rlimit = resource.getrlimit(resource.RLIMIT_NOFILE)
resource.setrlimit(resource.RLIMIT_NOFILE, (2048, rlimit[1]))
```

**Comment by sampathweb** [comment] 2017-11-17 01:04
Cool.  Glad that it helped.  I would not recommend adding the `ulimit` setting automatically into fast.ai code.  `ulimit` affects all applications on the system, so we should not do it as part of an application library.

Two suggestions that come to mind  -
1. Add to Readme of fast.ai on Installation / known issues and reference this github issue
2. Add `try` and `catch` exception in `TTA` and print the `ulimit` increase suggestion.

**Comment by jph00** [comment] 2017-11-17 01:48
Better still would be to figure out *why* so many FDs are being used. It sounds like some code isn't closing file handles when it should be. 

Is it only in learn.predict() that this is happening?

**Comment by hiromis** [comment] 2017-11-17 02:35
> figure out why so many FDs are being used

That would definitely be better. My tracing skill with python is limited but I shall give it a try.

**Comment by sampathweb** [comment] 2017-11-17 02:40
Yeah..it's coming from pytorch's forked multiprocessing code.  I have no idea.  I am hoping the core-devs in Pytorch can figure it out.  I posted our workaround in the pytorch's github issue linked to this.

**Comment by hiromis** [comment] 2017-11-17 04:27
It was actually 60k images that caused the issue - 40k ran fine.

I stared at [`DataLoaderIter.__next__`](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L185) function for a little while. It has a statement `if self.num_workers == 0: ` that will result in a different path, and considering some people changing `num_workers` to zero to avoid the issue makes me think the issue is in the `else` portion of that code.

Do you guys think`validate` (fastai model.py line 98ish) could run into the same issue since it uses `iter(dl)` if we ever had ....however unlikely... 60k images for validation? Or would the list comprehension in `predict_with_targs` make some differences? 

validate:
```
    for (*x,y) in iter(dl):
        preds,l = stepper.evaluate(VV(x), VV(y))
        loss.append(to_np(l))
        res.append([f(to_np(preds),to_np(y)) for f in metrics])
```

predict_with_targs:

`preda,targa = zip(*[(get_prediction(m(*VV(x))),y) for *x,y in iter(dl)])`

**Comment by kevinbird15** [comment] 2017-11-17 07:06
Thank you guys for finding a work-around to the issue.  Very much appreciated.  I ran into the issue again tonight and the three lines from @hiromis fixed the error for me.  It definitely seems like it's a pytorch issue underlying, so I don't know if they know of that work-around or not, but It seems like a leak of some sort and I'm glad you were all able to recreate it.  

```
#Code from Hiromis above
import resource
rlimit = resource.getrlimit(resource.RLIMIT_NOFILE)
resource.setrlimit(resource.RLIMIT_NOFILE, (2048, rlimit[1]))
```

**Comment by pani6me** [comment] 2017-11-17 16:26
Filer resource limits will be there. If we had 1 million files to process and the prediction goes fast then increasing the ulimit probably won't help. How about we check number of open files of PID against the ulimit and wait if the open_fds < X%ulimit ?

**Comment by sampathweb** [comment] 2017-11-17 16:51
@pani6me - I would then Test in Chunks.  Pass through 10K Files or smaller number of files through test.  You will hit memory limitations before `ulimit` alone becomes a problem.  So I would not worry about it.  In most applications, you can chunk (pass in smaller batches) the data that goes through to resolve this.

**Comment by WNoxchi** [comment] 2017-11-17 18:04
> Is it only in learn.predict() that this is happening?

I just triggered this bug by calling `.TTA()` on a test set:
`log_preds = learn.TTA(is_test=True)`

**Comment by pani6me** [comment] 2017-11-18 00:35
@sampathweb Makes sense to test it by chunk and a warning to increase limit.

**Comment by jph00** [comment] 2017-11-18 02:39
I just changed the predictions so they're calculated with a loop rather than a list comprehension. Can you let me know if that fixes the problem?

**Comment by hiromis** [comment] 2017-11-18 04:46
I pulled the change and still fails for 61,191 images, but runs fine for 40,669. 

The one difference I noticed was that once the error occurs, it does not release the open file descriptors - requiring kernel restart to do anything on that notebook.

Current: https://github.com/hiromis/fastai-workspace/blob/master/Lesson2-Broken-Part2.ipynb
Before: https://github.com/hiromis/fastai-workspace/blob/master/Lesson2-Broken.ipynb

**Comment by WNoxchi** [comment] 2017-11-18 06:43
I'm getting a TypeError when trying to initialize a learner on the lesson1-rxt50 notebook now (just git pulled fastai).

Specific error: `TypeError: __init__() takes 1 positional argument but 2 were given`

 Steps to reproduce it:

(NOTE: this assumes data directory is setup as is class default: Notebook_Folder/data/dogscats/...)


```
%reload_ext autoreload
%autoreload 2
%matplotlib inline

from fastai.imports import *

from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *

PATH = "data/dogscats/"
sz = 299
ARCH = resnext50
bs = 8

tfms = tfms_from_model(ARCH, sz, aug_tfms=transforms_side_on, max_zoom=1.1)
data = ImageClassifierData.from_paths(PATH, tfms=tfms, bs=6, num_workers=4, test_name='test1')
learn = ConvLearner.pretrained(ARCH, data, ps=0.5, precompute=False)
```

Learner initialization in the last line is what's triggering it. Clearing the tmp/ folder had no effect. If at all useful, below is the error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-8882f3608021> in <module>()
     19 tfms = tfms_from_model(ARCH, sz, aug_tfms=transforms_side_on, max_zoom=1.1)
     20 data = ImageClassifierData.from_paths(PATH, tfms=tfms, bs=6, num_workers=4, test_name='test1')
---> 21 learn = ConvLearner.pretrained(ARCH, data, ps=0.5, precompute=False)

~/Kaukasos/FADL1/fastai/conv_learner.py in pretrained(cls, f, data, ps, xtra_fc, xtra_cut, **kwargs)
     91     @classmethod
     92     def pretrained(cls, f, data, ps=None, xtra_fc=None, xtra_cut=0, **kwargs):
---> 93         models = ConvnetBuilder(f, data.c, data.is_multi, data.is_reg, ps=ps, xtra_fc=xtra_fc, xtra_cut=xtra_cut)
     94         return cls(data, models, **kwargs)
     95 

~/Kaukasos/FADL1/fastai/conv_learner.py in __init__(self, f, c, is_multi, is_reg, ps, xtra_fc, xtra_cut)
     43         if not isinstance(self.ps, list): self.ps = [self.ps]*n_fc
     44 
---> 45         fc_layers = self.get_fc_layers()
     46         self.n_fc = len(fc_layers)
     47         self.fc_model = to_gpu(nn.Sequential(*fc_layers))

~/Kaukasos/FADL1/fastai/conv_learner.py in get_fc_layers(self)
     65             res += self.create_fc_layer(ni, nf, p=self.ps[i], actn=nn.ReLU())
     66             ni=nf
---> 67         final_actn = nn.Sigmoid() if self.is_multi else nn.LogSoftmax(1)
     68         if self.is_reg: final_actn = None
     69         res += self.create_fc_layer(ni, self.c, p=self.ps[-1], actn=final_actn)

TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by WNoxchi** [comment] 2017-11-18 07:12
**Update**: I editted line 67 of conv_learner.py to remove the argument to `nn.LogSoftmax()`

`        final_actn = nn.Sigmoid() if self.is_multi else nn.LogSoftmax(1)`

To:

`        final_actn = nn.Sigmoid() if self.is_multi else nn.LogSoftmax()`

And I'm no longer getting the TypeError when initializing the learner. Haven't tested this in actual predictions yet though.

I'm guessing `nn.LogSoftmax()` only takes self as its argument? I'm not familiar enough w/ PyTorch or fastai to know if the `1` had a purpose.

**Edit**: yeah I'm seeing the change from: 
`        final_actn = nn.Sigmoid if self.is_multi else nn.LogSoftmax`
to:
`         final_actn = nn.Sigmoid() if self.is_multi else nn.LogSoftmax(1)`

In the last commit. Hmm. Again, don't know if my change breaks the intended loop yet.

**Final Edit**: yup, back to the `RuntimeError: received 0 items of ancdata`

**Comment by binga** [comment] 2017-11-18 08:11
As @WNoxchi  mentioned, `nn.LogSoftmax()` seems to be working.

**Comment by jph00** [comment] 2017-11-18 20:09
Might be worth trying compiling pytorch from source. I did it yesterday and it was surprisingly easy. Just conda uninstall pytorch before installing your compiled version. That way, we'll know if they've already fixed it.

**Comment by WNoxchi** [comment] 2017-11-19 00:52
Just uninstalled pytorch & reinstalled from source, still getting the` RuntimeError: received 0 items of ancdata`

**Comment by WNoxchi** [comment] 2017-11-19 01:05
Just git pulled fastai, uninstalled pytorch & reinstalled from source. Still getting `RuntimeError: received 0 items of ancdata`

Will use the workaround in the mean time.

Also this deprecation warning: (running `.TTA(.)`)
```
.../miniconda3/envs/fastai/lib/python3.6/site-packages/torch/nn/modules/container.py:72: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
```

**Comment by jph00** [comment] 2017-11-22 16:39
I changed the dataloader recently to use ThreadPool instead of ProcessPool. Has that resolved this problem?

**Comment by hiromis** [comment] 2017-11-22 17:12
Yes!!!

https://github.com/hiromis/fastai-workspace/blob/master/Lesson2-Fixed-Part3.ipynb

![screen shot 2017-11-22 at 11 08 29 am](https://user-images.githubusercontent.com/5401333/33140543-ea4e8dd8-cf75-11e7-81d2-7655d33efc42.png)

**Comment by WNoxchi** [comment] 2017-11-23 01:17
Just tested my notebook again, works without complaint.

**Closed** 2017-11-29 23:09 UTC
