### ISSUE TITLE
Language model not predicting

### ISSUE THREAD

**Issue by JosephPB** [fastai/fastai#2209] opened 2019-07-09 10:21 UTC
**Describe the bug**
After training a `language_model_learner`, and successfully saving and loading, running a prediction flags the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-135dd315cd3b> in <module>
----> 1 print("\n".join(learn.predict(TEXT, N_WORDS, temperature=0.75) for _ in range(N_SENTENCES)))

<ipython-input-11-135dd315cd3b> in <genexpr>(.0)
----> 1 print("\n".join(learn.predict(TEXT, N_WORDS, temperature=0.75) for _ in range(N_SENTENCES)))

/efs/data/jpb/fastai/fastai/fastai/text/learner.py in predict(self, text, n_words, no_unk, temperature, min_p, sep, decoder)
    119         ds = self.data.single_dl.dataset
    120         self.model.reset()
--> 121         xb,yb = self.data.one_item(text)
    122         new_idx = []
    123         for _ in range(n_words): #progress_bar(range(n_words), leave=False):

/efs/data/jpb/fastai/fastai/fastai/basic_data.py in one_item(self, item, detach, denorm, cpu)
    178         "Get `item` into a batch. Optionally `detach` and `denorm`."
    179         ds = self.single_ds
--> 180         with ds.set_item(item):
    181             return self.one_batch(ds_type=DatasetType.Single, detach=detach, denorm=denorm, cpu=cpu)
    182 

~/anaconda3/envs/fastai_test/lib/python3.6/contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

/efs/data/jpb/fastai/fastai/fastai/data_block.py in set_item(self, item)
    594     def set_item(self,item):
    595         "For inference, will briefly replace the dataset with one that only contains `item`."
--> 596         self.item = self.x.process_one(item)
    597         yield None
    598         self.item = None

/efs/data/jpb/fastai/fastai/fastai/data_block.py in process_one(self, item, processor)
     80         if processor is not None: self.processor = processor
     81         self.processor = listify(self.processor)
---> 82         for p in self.processor: item = p.process_one(item)
     83         return item
     84 

/efs/data/jpb/fastai/fastai/fastai/text/data.py in process_one(self, item)
    286 
    287     def process_one(self, item):
--> 288         return self.tokenizer._process_all_1(_join_texts([item], self.mark_fields, self.include_bos, self.include_eos))[0]
    289 
    290     def process(self, ds):

AttributeError: 'TokenizeProcessor' object has no attribute 'include_bos'
```

**Provide your installation details**
```
=== Software ===
python        : 3.6.8
fastai        : 1.0.51.dev0
fastprogress  : 0.1.20
torch         : 1.1.0a0+929cd23
nvidia driver : 384.130
torch cuda    : 8.0.61 / is available
torch cudnn   : 7104 / is enabled

=== Hardware ===
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11439MB | Tesla K80

=== Environment ===
platform      : Linux-4.4.0-1075-aws-x86_64-with-debian-stretch-sid
distro        : Ubuntu 16.04 xenial
conda env     : fastai_test
python        : /home/ubuntu/anaconda3/envs/fastai_test/bin/python
sys.path      :
/home/ubuntu/src/cntk/bindings/python
/home/ubuntu/pytorch/build
/efs/data/jpb/Detectron/Detectron
/home/ubuntu/anaconda3/envs/fastai_test/lib/python36.zip
/home/ubuntu/anaconda3/envs/fastai_test/lib/python3.6
/home/ubuntu/anaconda3/envs/fastai_test/lib/python3.6/lib-dynload
/home/ubuntu/.local/lib/python3.6/site-packages
/home/ubuntu/anaconda3/envs/fastai_test/lib/python3.6/site-packages
/home/ubuntu/anaconda3/envs/fastai_test/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg
/home/ubuntu/anaconda3/envs/fastai_test/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg
/home/ubuntu/anaconda3/envs/fastai_test/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg
/efs/data/jpb/fastai/fastai
```

**To Reproduce**
Train language model

`learn.load('./unga_uf_1');`
```
TEXT = "The is test text"
N_WORDS = 100
N_SENTENCES = 2

print("\n".join(learn.predict(TEXT, N_WORDS, temperature=0.75) for _ in range(N_SENTENCES)))
```

**Expected behavior**
Prediction of the next 100 words split into 2 sentences

**Comment by sgugger** [comment] 2019-07-09 13:05
I can't reproduce on master. I see you're using v1.0.51 on your install details, try updating the library and see if the bug persists? I think it has been fixed already.

**Comment by JosephPB** [comment] 2019-07-09 13:50
Hi, I have updated to 1.0.55 and not get a tensor shape error. I have tried changing the `awd_lstm_lm_config['n_hid']` but this isn't fixing it. Thanks for the help.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-16-752e3a734fec> in <module>
----> 1 learn.load('./unga_uf_1');

/efs/data/jpb/fastai/fastai/fastai/basic_train.py in load(self, file, device, strict, with_opt, purge, remove_module)
    269             model_state = state['model']
    270             if remove_module: model_state = remove_module_load(model_state)
--> 271             get_model(self.model).load_state_dict(model_state, strict=strict)
    272             if ifnone(with_opt,True):
    273                 if not hasattr(self, 'opt'): self.create_opt(defaults.lr, self.wd)

~/anaconda3/envs/fastai_test/lib/python3.6/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
    769         if len(error_msgs) > 0:
    770             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
--> 771                                self.__class__.__name__, "\n\t".join(error_msgs)))
    772 
    773     def _named_members(self, get_members_fn, prefix='', recurse=True):

RuntimeError: Error(s) in loading state_dict for SequentialRNN:
	size mismatch for 0.rnns.0.weight_hh_l0_raw: copying a param with shape torch.Size([4600, 1150]) from checkpoint, the shape in current model is torch.Size([4608, 1152]).
	size mismatch for 0.rnns.0.module.weight_ih_l0: copying a param with shape torch.Size([4600, 400]) from checkpoint, the shape in current model is torch.Size([4608, 400]).
	size mismatch for 0.rnns.0.module.weight_hh_l0: copying a param with shape torch.Size([4600, 1150]) from checkpoint, the shape in current model is torch.Size([4608, 1152]).
	size mismatch for 0.rnns.0.module.bias_ih_l0: copying a param with shape torch.Size([4600]) from checkpoint, the shape in current model is torch.Size([4608]).
	size mismatch for 0.rnns.0.module.bias_hh_l0: copying a param with shape torch.Size([4600]) from checkpoint, the shape in current model is torch.Size([4608]).
	size mismatch for 0.rnns.1.weight_hh_l0_raw: copying a param with shape torch.Size([4600, 1150]) from checkpoint, the shape in current model is torch.Size([4608, 1152]).
	size mismatch for 0.rnns.1.module.weight_ih_l0: copying a param with shape torch.Size([4600, 1150]) from checkpoint, the shape in current model is torch.Size([4608, 1152]).
	size mismatch for 0.rnns.1.module.weight_hh_l0: copying a param with shape torch.Size([4600, 1150]) from checkpoint, the shape in current model is torch.Size([4608, 1152]).
	size mismatch for 0.rnns.1.module.bias_ih_l0: copying a param with shape torch.Size([4600]) from checkpoint, the shape in current model is torch.Size([4608]).
	size mismatch for 0.rnns.1.module.bias_hh_l0: copying a param with shape torch.Size([4600]) from checkpoint, the shape in current model is torch.Size([4608]).
	size mismatch for 0.rnns.2.module.weight_ih_l0: copying a param with shape torch.Size([1600, 1150]) from checkpoint, the shape in current model is torch.Size([1600, 1152]).
```

**Comment by sgugger** [comment] 2019-07-09 13:59
You need to pass a config in your call to `Learner` to use the old size:
```
config = awd_lstm_lm_config.copy()
config['n_hid'] = 1150
learn = bla_learner(..., config=config)
```

**Comment by JosephPB** [comment] 2019-07-09 18:45
Hi, I updated fastai to the latest version and reran the training and predicting and I'm back at the original error again

**Comment by sgugger** [comment] 2019-07-09 18:47
I need a fully contained reproducible example to fix, like I said, I couldn't reproduce your bug. It's probably linked to the way you gathered your data too.

**Comment by sgugger** [comment] 2019-07-18 15:51
Closing since it has been a while with no news. Please reopen with reproducible code if you get the time to dig into it.

**Closed by sgugger** 2019-07-18 15:51 UTC
