### ISSUE TITLE
TextLMDataBunch.from_df() hangs indefinitely when processing string that contains very long token.

### ISSUE THREAD

**Issue by kmacmillan-ou** [fastai/fastai#1589] opened 2019-02-07 19:39 UTC
**Describe the bug**
TextLMDataBunch.from_df() hangs indefinitely when processing string that contains very long token. 

**Provide your installation details**
```text
=== Software === 
python version  : 3.6.5
fastai version  : 1.0.34
torch version   : 1.0.1
nvidia driver   : 396.44
torch cuda ver  : 9.0.176
torch cuda is   : available
torch cudnn ver : 7402
torch cudnn is  : enabled

=== Hardware === 
nvidia gpus     : 1
torch available : 1
  - gpu0        : 11441MB | Tesla K80

=== Environment === 
platform        : Linux-4.14.77-70.82.amzn1.x86_64-x86_64-with-glibc2.9
distro          : #1 SMP Mon Dec 3 20:01:27 UTC 2018
conda env       : python3
python          : /home/ec2-user/anaconda3/envs/python3/bin/python
sys.path        : 
/home/ec2-user/src/cntk/bindings/python
/home/ec2-user/anaconda3/envs/python3/lib/python36.zip
/home/ec2-user/anaconda3/envs/python3/lib/python3.6
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/lib-dynload
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/IPython/extensions
/home/ec2-user/.ipython
```

**To Reproduce**
```
train_df = pd.DataFrame({'TITLE':['shoes'], 
                         'DESCRIPTION':['size 5']})
valid_df = pd.DataFrame({'TITLE':['truck'], 
                         'DESCRIPTION':['6lug.dropped.ss.silverado.gmc.sierra.chevy.swb.bagged.35x12.5.35s.33x12.5.33s.20s.22s.24s.26s.']})

lm_databunch = TextLMDataBunch.from_df('tmp', 
                                      train_df=train_df, 
                                      valid_df=valid_df, 
                                      text_cols=['TITLE', 'DESCRIPTION'], 
                                      min_freq=0,
                                      max_vocab=100)
```

Running the code above causes the `TextLMDataBunch.from_df()` call to hang indefinitely (see screenshot). Cutting the 'DESCRIPTION' in valid_df down to less than 50 characters fixes this problem and the call runs quickly.

Backtrace after executing keyboard interrupt is pasted in the additional context section.

**Expected behavior**
Expected behavior is that TextLMDataBunch.from_df() runs quickly.

**Screenshots**
![screen shot 2019-02-07 at 11 36 30 am](https://user-images.githubusercontent.com/47431154/52437788-a1566700-2acc-11e9-8929-1cc918f17531.png)

**Additional context**
Keyboard Interrupt backtrace:

```
File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
~/anaconda3/envs/python3/lib/python3.6/site-packages/fastai/text/transform.py in process_all(self, texts)
    116         with ProcessPoolExecutor(self.n_cpus) as e:
--> 117             return sum(e.map(self._process_all_1, partition_by_cores(texts, self.n_cpus)), [])
    118 

~/anaconda3/envs/python3/lib/python3.6/concurrent/futures/process.py in _chain_from_iterable_of_lists(iterable)
    365     """
--> 366     for element in iterable:
    367         element.reverse()

~/anaconda3/envs/python3/lib/python3.6/concurrent/futures/_base.py in result_iterator()
    585                     if timeout is None:
--> 586                         yield fs.pop().result()
    587                     else:

~/anaconda3/envs/python3/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    426 
--> 427             self._condition.wait(timeout)
    428 

~/anaconda3/envs/python3/lib/python3.6/threading.py in wait(self, timeout)
    294             if timeout is None:
--> 295                 waiter.acquire()
    296                 gotit = True

KeyboardInterrupt: 

During handling of the above exception, another exception occurred:

KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-111-8ecd87a3b309> in <module>()
      4                                       text_cols=['TITLE', 'DESCRIPTION'],
      5                                       min_freq=0,
----> 6                                       max_vocab=100)

~/anaconda3/envs/python3/lib/python3.6/site-packages/fastai/text/data.py in from_df(cls, path, train_df, valid_df, test_df, tokenizer, vocab, classes, text_cols, label_cols, label_delim, **kwargs)
    168         src = ItemLists(path, TextList.from_df(train_df, path, cols=text_cols, processor=processor),
    169                         TextList.from_df(valid_df, path, cols=text_cols, processor=processor))
--> 170         src = src.label_for_lm() if cls==TextLMDataBunch else src.label_from_df(cols=label_cols, classes=classes, sep=label_delim)
    171         if test_df is not None: src.add_test(TextList.from_df(test_df, path, cols=text_cols))
    172         return src.databunch(**kwargs)

~/anaconda3/envs/python3/lib/python3.6/site-packages/fastai/data_block.py in _inner(*args, **kwargs)
    373             self.valid = fv(*args, **kwargs)
    374             self.__class__ = LabelLists
--> 375             self.process()
    376             return self
    377         return _inner

~/anaconda3/envs/python3/lib/python3.6/site-packages/fastai/data_block.py in process(self)
    420         "Process the inner datasets."
    421         xp,yp = self.get_processors()
--> 422         for i,ds in enumerate(self.lists): ds.process(xp, yp, filter_missing_y=i==0)
    423         return self
    424 

~/anaconda3/envs/python3/lib/python3.6/site-packages/fastai/data_block.py in process(self, xp, yp, filter_missing_y)
    519             filt = array([o is None for o in self.y])
    520             if filt.sum()>0: self.x,self.y = self.x[~filt],self.y[~filt]
--> 521         self.x.process(xp)
    522         return self
    523 

~/anaconda3/envs/python3/lib/python3.6/site-packages/fastai/data_block.py in process(self, processor)
     65         if processor is not None: self.processor = processor
     66         self.processor = listify(self.processor)
---> 67         for p in self.processor: p.process(self)
     68         return self
     69 

~/anaconda3/envs/python3/lib/python3.6/site-packages/fastai/text/data.py in process(self, ds)
    245         tokens = []
    246         for i in progress_bar(range(0,len(ds),self.chunksize), leave=False):
--> 247             tokens += self.tokenizer.process_all(ds.items[i:i+self.chunksize])
    248         ds.items = tokens
    249 

~/anaconda3/envs/python3/lib/python3.6/site-packages/fastai/text/transform.py in process_all(self, texts)
    115         if self.n_cpus <= 1: return self._process_all_1(texts)
    116         with ProcessPoolExecutor(self.n_cpus) as e:
--> 117             return sum(e.map(self._process_all_1, partition_by_cores(texts, self.n_cpus)), [])
    118 
    119 class Vocab():

~/anaconda3/envs/python3/lib/python3.6/concurrent/futures/_base.py in __exit__(self, exc_type, exc_val, exc_tb)
    609 
    610     def __exit__(self, exc_type, exc_val, exc_tb):
--> 611         self.shutdown(wait=True)
    612         return False

~/anaconda3/envs/python3/lib/python3.6/concurrent/futures/process.py in shutdown(self, wait)
    504             self._result_queue.put(None)
    505             if wait:
--> 506                 self._queue_management_thread.join()
    507         # To reduce the risk of opening too many files, remove references to
    508         # objects that use file descriptors.

~/anaconda3/envs/python3/lib/python3.6/threading.py in join(self, timeout)
   1054 
   1055         if timeout is None:
-> 1056             self._wait_for_tstate_lock()
   1057         else:
   1058             # the behavior of a negative timeout isn't documented, but

~/anaconda3/envs/python3/lib/python3.6/threading.py in _wait_for_tstate_lock(self, block, timeout)
   1070         if lock is None:  # already determined that the C code is done
   1071             assert self._is_stopped
-> 1072         elif lock.acquire(block, timeout):
   1073             lock.release()
   1074             self._stop()

KeyboardInterrupt: 

  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
```

**Comment by sgugger** [comment] 2019-02-08 18:03
I can't reproduce that bug. Did you try on the latest version of fastai?

**Comment by sgugger** [comment] 2019-02-19 13:50
Closing this since in a while. Feel free to reopen with an example I can reproduce!

**Closed by sgugger** 2019-02-19 13:50 UTC

**Comment by ben0it8** [comment] 2019-02-26 10:18
@kmacmillan-ou did you figure out why processing hangs indefinitely? I'm facing the same issue.

**Comment by dianhuang** [comment] 2019-05-29 04:46
I have the same issue. I just followed the example of text classification. It hangs when I called TextLMDataBunch.from_df


import fastai
from fastai import *
from fastai.text import * 
import pandas as pd
import numpy as np
from functools import partial
import io
import os

from sklearn.datasets import fetch_20newsgroups
dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers', 'footers', 'quotes'))
documents = dataset.data


df = pd.DataFrame({'label':dataset.target, 'text':dataset.data})
##Select only label 1 and 10 for classification
df = df[df['label'].isin([1,10])]
df = df.reset_index(drop = True)
df['label'].value_counts()

###Remove non-letter
df['text'] = df['text'].str.replace("[^a-zA-Z]", " ")


import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords 
stop_words = stopwords.words('english')



# tokenization 
tokenized_doc = df['text'].apply(lambda x: x.split())

# remove stop-words 
tokenized_doc = tokenized_doc.apply(lambda x: [item for item in x if item not in stop_words])

# de-tokenization 
detokenized_doc = [] 
for i in range(len(df)): 
    t = ' '.join(tokenized_doc[i]) 
    detokenized_doc.append(t) 

df['text'] = detokenized_doc

##Split dataset into training and validation
from sklearn.model_selection import train_test_split

# split data into training and validation set
df_trn, df_val = train_test_split(df, stratify = df['label'], test_size = 0.4, random_state = 12)


# Language model data
data_lm = TextLMDataBunch.from_df(train_df = df_trn, valid_df = df_val, path = "")

# Classifier model data
#data_clas = TextClasDataBunch.from_df(path = "", train_df = df_trn, valid_df = df_val, vocab=data_lm.train_ds.vocab, bs=32)
