### ISSUE TITLE
404 error loading https://docs.fast.ai/medical.imaging.html 

### ISSUE THREAD

**Issue by tibbsie** [fastai/fastai#2985] opened 2020-11-15 11:08 UTC
This is an issue with the documentation website. Its link "please tell us about it by filing a bug report here" gets me to fastai library bug reporting -- apologies if bug report misplaced.

**Description of the bug**
404 error loading https://docs.fast.ai/medical.imaging.html 

**To reproduce**
Go on 
docs.fast.ai
with Nav (navigation) on, navigate to **Medical** and then choose **Imagery** 

Alternatively, search in the search box for "medical imaging" and choose the first result.

**Additional context**
the text bit documentation works well (returns a valid page, promising further development)
https://docs.fast.ai/medical.text.html

**Comment by abhirooptalasila** [comment] 2020-11-16 13:30
Same as #2974

**Comment by hamelsmu** [comment] 2020-11-16 19:17
This is now a duplicate of https://github.com/fastai/fastai/issues/2989 we will triage all of these in that issue.

**Closed by hamelsmu** 2020-11-16 19:17 UTC
Labels: broken-link
