### ISSUE TITLE
Passing custom function or array to Rotate in transforms

### ISSUE THREAD

**Issue by ecatkins** [fastai/fastai#2785] opened 2020-09-10 16:43 UTC
According to the docs, you can pass `Rotate` a `callable` that returns a float to customize the angle applied. As i understand this...
```
def my_rotate(x):
    return 10.5

tfm_list = [Rotate(p=1.0, draw=my_rotate)]
my_tfms = setup_aug_tfms(tfm_list)
```

However when I call `show_batch` it returns the following error
![image](https://user-images.githubusercontent.com/8319226/92762814-f6212a00-f360-11ea-993f-ecb1b7316d89.png)

Using the standard `Rotate` without specifying `draw` e.g. ` Rotate(max_deg=10, p=0.5)` works fine.

To experiment, I also tried to pass an array of length `BATCH_SIZE` (16 in this case) to `draw`, which is also specified in the docs and I get a different error
```
thetas = [10.0] * BATCH_SIZE
tfm_list = [Rotate(p=1.0, draw=thetas]
my_tfms = setup_aug_tfms(tfm_list)
```
![image](https://user-images.githubusercontent.com/8319226/92764707-a4799f00-f362-11ea-8ec4-fd19d580191b.png)

The length of my `thetas` is not equal to `1` even though the docs say it must be equal to the batch size.

Strangely if I try to purposely misspecify the array so that it is less than the `BATCH_SIZE`...
```
thetas = [10.0] * (BATCH_SIZE-1)
```
Now the assertion is what I would have expected it to be `len(thetas)==len(BATCH_SIZE)`

![image](https://user-images.githubusercontent.com/8319226/92764487-772cf100-f362-11ea-8872-50b5c2c36614.png)

**Comment by marii-moe** [comment] 2020-09-26 00:11
I am now actively working on this issue.

**Comment by marii-moe** [comment] 2020-09-29 05:10
After looking into this a bit, an array will not work for batch_tfms, which I believe is where this code is being used, and where I was able to reproduce the issues listed here. I do think this points out that the documentation here needs to be updated. I will probably try to do that. 

Here are some examples of how this works with batch transforms. 
```
def my_rotate_different(x): 
    return torch.arange(0,x.size(0)*15,15,device=x.device)

tfm_list = [Rotate(p=1.0, draw=my_rotate_different)]
my_tfms_different = setup_aug_tfms(tfm_list)

tfm_list = [Rotate(p=1.0, draw=10.5)]
my_tfms_constant = setup_aug_tfms(tfm_list)

#Example 1
set_seed(42,True)
dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2, bs=4, seed=42,
    label_func=is_cat, item_tfms=Resize(224),batch_tfms=my_tfms_different)
dls.show_batch()
#Example 2
set_seed(42,True)
dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2, bs=4, seed=42,
    label_func=is_cat, item_tfms=Resize(224),batch_tfms=my_tfms_constant)
dls.show_batch()
```

In the first example, this is how I found to be able to use draw using a function. As you found the output of the function must be a tensor, or it will not have the 'cos' function. 

In the second example, you can see that it is possible to use a single constant for a rotation transform. 

Finally, the reason for the weird behavior with your code is that dataloaders have to be able to handle **variable** batch size, or at least a batch size of 1, this is needed to due things like dls._one_pass(). Behind the scenes fastai calls this _one_pass to make sure it has the correct types when it is decoding the tensors back into images. Since you provided a list this call fails because _one_pass operates on a single sample. 

@ecatkins does that solve your issue? I can provide a gist if this is not clear enough. 

I will look at this a bit more, to see what can be done about the documenting this further, thank you for reporting this issue!

**Comment by marii-moe** [comment] 2020-10-01 00:56
@ecatkins Code should be updated now to work with a list. I am currently updating the documentation, which is probably harder than the code fix itself. Using a function is actually "difficult" and a more advanced use case given the code I see though. The list should work now.

**Comment by ecatkins** [comment] 2020-10-01 21:57
@marii-moe amazing, thank you!

**Comment by marii-moe** [comment] 2020-10-27 01:53
@ecatkins Okay to close this one? 

This is what the docs look like now: https://docs.fast.ai/vision.augment#Rotate

**Comment by marii-moe** [comment] 2020-11-02 23:07
@ecatkins I think this is good now, how does https://docs.fast.ai/vision.augment#Rotate look?

**Comment by marii-moe** [comment] 2020-11-08 13:08
@ecatkins Going ahead and closing this one pretty sure it is all fixed now.

**Closed by marii-moe** 2020-11-08 13:08 UTC
