### ISSUE TITLE
bug when trying to train new model

### ISSUE THREAD

**Issue by bbowles-personal** [fastai/fastai#1323] opened 2018-12-12 19:20 UTC
**Describe the bug**
The code
 ```
learn = create_cnn(data, models.resnet50, metrics=accuracy)
learn.fit_one_cycle(1,1e-2)
```
fails because it the attribute `out` was never assigned to the `ProgressBar' class.

example stack trace

```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-f50636af9890> in <module>()
      1 learn = create_cnn(data, models.resnet50, metrics=accuracy)
----> 2 learn.fit_one_cycle(1,1e-2)

/home/ec2-user/anaconda3/lib/python3.6/site-packages/fastai/train.py in fit_one_cycle(learn, cyc_len, max_lr, moms, div_factor, pct_start, wd, callbacks, **kwargs)
     19     callbacks.append(OneCycleScheduler(learn, max_lr, moms=moms, div_factor=div_factor,
     20                                         pct_start=pct_start, **kwargs))
---> 21     learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
     22 
     23 def lr_find(learn:Learner, start_lr:Floats=1e-7, end_lr:Floats=10, num_it:int=100, stop_div:bool=True, **kwargs:Any):

/home/ec2-user/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py in fit(self, epochs, lr, wd, callbacks)
    164         callbacks = [cb(self) for cb in self.callback_fns] + listify(callbacks)
    165         fit(epochs, self.model, self.loss_func, opt=self.opt, data=self.data, metrics=self.metrics,
--> 166             callbacks=self.callbacks+callbacks)
    167 
    168     def create_opt(self, lr:Floats, wd:Floats=0.)->None:

/home/ec2-user/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py in fit(epochs, model, loss_func, opt, data, callbacks, metrics)
     92     except Exception as e:
     93         exception = e
---> 94         raise e
     95     finally: cb_handler.on_train_end(exception)
     96 

/home/ec2-user/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py in fit(epochs, model, loss_func, opt, data, callbacks, metrics)
     80             cb_handler.on_epoch_begin()
     81 
---> 82             for xb,yb in progress_bar(data.train_dl, parent=pbar):
     83                 xb, yb = cb_handler.on_batch_begin(xb, yb)
     84                 loss = loss_batch(model, xb, yb, loss_func, opt, cb_handler)

/home/ec2-user/anaconda3/lib/python3.6/site-packages/fastprogress/fastprogress.py in __init__(self, gen, total, display, leave, parent, auto_update)
    144     def __init__(self, gen, total=None, display=True, leave=True, parent=None, auto_update=True):
    145         self.progress = html_progress_bar(0, len(gen) if total is None else total, "")
--> 146         super().__init__(gen, total, display, leave, parent, auto_update)
    147 
    148     def on_iter_begin(self):

/home/ec2-user/anaconda3/lib/python3.6/site-packages/fastprogress/fastprogress.py in __init__(self, gen, total, display, leave, parent, auto_update)
     48         else:
     49             self.leave,self.display=False,False
---> 50             parent.add_child(self)
     51         self.comment = ''
     52         if not self.auto_update:

/home/ec2-user/anaconda3/lib/python3.6/site-packages/fastprogress/fastprogress.py in add_child(self, child)
    193         self.child = child
    194         self.inner_dict['pb2'] = self.child.progress
--> 195         self.show()
    196 
    197     def show(self):

/home/ec2-user/anaconda3/lib/python3.6/site-packages/fastprogress/fastprogress.py in show(self)
    200         to_show = [name for name in self.order if name in self.inner_dict.keys()]
    201         self.html_code = '\n'.join([self.inner_dict[n] for n in to_show])
--> 202         self.out.update(HTML(self.html_code))
    203 
    204     def write(self, line, table=False):

AttributeError: 'NoneType' object has no attribute 'update'```




```
In [56]: import fastai; fastai.show_install(1)

```text
=== Software === 
python version  : 3.6.3
fastai version  : 1.0.36
torch version   : 1.0.0
nvidia driver   : 396.44
torch cuda ver  : 9.0.176
torch cuda is   : available
torch cudnn ver : 7401
torch cudnn is  : enabled

=== Hardware === 
nvidia gpus     : 1
torch available : 1
  - gpu0        : 16160MB | Tesla V100-SXM2-16GB

=== Environment === 
platform        : Linux-4.14.77-70.59.amzn1.x86_64-x86_64-with-glibc2.9
distro          : #1 SMP Mon Nov 12 22:02:45 UTC 2018
conda env       : Unknown
python          : /home/ec2-user/anaconda3/bin/python
sys.path        : 
/home/ec2-user/anaconda3/bin
/home/ec2-user/src/cntk/bindings/python
/home/ec2-user/anaconda3/lib/python36.zip
/home/ec2-user/anaconda3/lib/python3.6
/home/ec2-user/anaconda3/lib/python3.6/lib-dynload
/home/ec2-user/anaconda3/lib/python3.6/site-packages
/home/ec2-user/anaconda3/lib/python3.6/site-packages/Sphinx-1.5.1-py3.6.egg
/home/ec2-user/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg
/home/ec2-user/anaconda3/lib/python3.6/site-packages/IPython/extensions
/home/ec2-user/.ipython

Wed Dec 12 19:15:07 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   36C    P0    37W / 300W |   1398MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      9695      C   python                                      1388MiB |
+-----------------------------------------------------------------------------+

```

**Comment by sgugger** [comment] 2018-12-12 21:35
Are you sure you have the last version of fastprogress (1.0.18)?

**Comment by bbowles-personal** [comment] 2018-12-12 22:15
Yes, I do. I noticed that its only 8 days old, i wondered if there was a problem with it. An older version didnt' work either. managed to replicate with .  ```
from fastprogress import master_bar, progress_bar
from time import sleep
mb = master_bar(range(10))
for i in mb:
    for j in progress_bar(range(100), parent=mb):
        sleep(0.01)
        mb.child.comment = f'second bar stat'
    mb.first_bar.comment = f'first bar stat'
    mb.write(f'Finished loop {i}.')```

**Comment by bbowles-personal** [comment] 2018-12-12 22:17
Its a notebook specific thing, works in ipython terminal

**Comment by sgugger** [comment] 2018-12-12 22:37
This bit of code works perfectly for me. Are you sure you didn't do a developer install and changed something in the code of fastprogress? Or that you are in the right conda environment?

**Comment by sgugger** [comment] 2018-12-26 10:33
Closing this since there is no news and we can't reproduce the bug on our side.

**Closed by sgugger** 2018-12-26 10:33 UTC
