### ISSUE TITLE
Add import statement to fast.ai quickstart doc

### ISSUE THREAD

**Issue by lehmannerich** [fastai/fastai#3782] opened 2022-08-28 07:13 UTC
The very first code example at [Computer vision classification](https://docs.fast.ai/quick_start.html) should have this statement
`from fastai.vision.all import *`

I think a lot of people trip up there and get a NameError.

**Comment by Ben-Karr** [comment] 2022-09-26 16:39
This issue is a duplicate of #3771, I created a PR there.

**Comment by hamelsmu** [comment] 2022-10-06 04:24
closing duplicate issue

**Closed by hamelsmu** 2022-10-06 04:24 UTC
