### ISSUE TITLE
Pandas output is broken after fastai import

### ISSUE THREAD

**Issue by mamamot** [fastai/fastai#1531] opened 2019-01-28 11:37 UTC
**Describe the bug**
After importing fastai.text, pandas output (like `.head()`) raises an exception:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/miniconda3/envs/ml/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/miniconda3/envs/ml/lib/python3.7/site-packages/pandas/core/frame.py in _repr_html_(self)
    647         # display HTML, so this check can be removed when support for
    648         # IPython 2.x is no longer needed.
--> 649         if console.in_qtconsole():
    650             # 'HTML output is disabled in QtConsole'
    651             return None

~/miniconda3/envs/ml/lib/python3.7/site-packages/pandas/io/formats/console.py in in_qtconsole()
    121             ip.config.get('KernelApp', {}).get('parent_appname', "") or
    122             ip.config.get('IPKernelApp', {}).get('parent_appname', ""))
--> 123         if 'qtconsole' in front_end.lower():
    124             return True
    125     except NameError:

AttributeError: 'LazyConfigValue' object has no attribute 'lower'

```

**Provide your installation details**

```text
=== Software === 
python        : 3.7.2
fastai        : 1.0.42
fastprogress  : 0.1.18
torch         : 1.0.0
nvidia driver : 384.130
torch cuda    : 9.0.176 / is available
torch cudnn   : 7401 / is enabled

=== Environment === 
platform      : Linux-4.4.0-62-generic-x86_64-with-debian-stretch-sid
distro        : #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017
conda env     : ml
python        : /home/username/miniconda3/envs/ml/bin/python
sys.path      : /home/username/ml_experiments
/home/username/miniconda3/envs/ml/lib/python37.zip
/home/username/miniconda3/envs/ml/lib/python3.7
/home/username/miniconda3/envs/ml/lib/python3.7/lib-dynload

/home/username/miniconda3/envs/ml/lib/python3.7/site-packages
/home/username/miniconda3/envs/ml/lib/python3.7/site-packages/IPython/extensions
/home/username/.ipython
```

The same problem exists with python 3.6 (except with python 3.6 there seems to be a broken `dataclasses` dependency as well).

**To Reproduce**
Import pandas, read a dataframe, show `head`. Then import * from fastai.text. Show `head` again.

```python
# coding: utf-8
# In[1]:
import pandas as pd

# In[3]:
df = pd.DataFrame(pd.np.zeros((2, 2))) 

# In[4]:
df  # works fine

# In[5]:
from fastai.text import *

# In[6]:
df  # doesn't work now
```

**Expected behavior**
Output is the same.

**Comment by sgugger** [comment] 2019-01-28 15:51
I think the bug is linked to the IPython you're using (QT console?) could you try to replace from
```
fastai.text import *
```
with
```
from IPython.display import clear_output, display, HTML
```
then tell me if you have the same problem?

**Comment by mamamot** [comment] 2019-01-28 15:59
After this step, there is no error.
![image](https://user-images.githubusercontent.com/14188757/51848508-c4478500-232e-11e9-9799-78b9e489264b.png)

An aside: I run jupyter on a remote machine using ssh.

**Comment by sgugger** [comment] 2019-01-28 16:35
I'm also on a jupyter notebook with a ssh tunnel but I can't reproduce the bug. So I'll need your help figuring out which import breaks it for you. Could you try to see which one of the imports in fastai/imports/core.py or fastai/imports/torch_core.py is at fault? Thanks

**Comment by mamamot** [comment] 2019-01-28 16:45
Sure.
Seems that ```from fastai.imports import torch``` is the culprit.

**Comment by mamamot** [comment] 2019-01-28 16:57
Wow, it's `import spacy`, so seems fastai is not at fault here :)

**Comment by sgugger** [comment] 2019-01-28 16:59
Can you open an issue on their side then? I'm closing this here.
Thanks for digging!

**Closed by sgugger** 2019-01-28 16:59 UTC

**Comment by mamamot** [comment] 2019-01-28 17:07
Thank you for walking me through!
