### ISSUE TITLE
name 'train_cats' is not defined 

### ISSUE THREAD

**Issue by koushikam** [fastai/fastai#1941] opened 2019-04-08 05:38 UTC
How to fix the error name 'train_cats' is not defined ?

**Comment by charusat09** [comment] 2019-04-08 06:00
@koushikam it seems like you are using v1.0 fastai with old notebooks. You need to use v0.7 of fastai for this old ML1 course or you can copy old code for your function `train_cats` from here: https://github.com/fastai/fastai/blob/master/old/fastai/structured.py#L112.

But, I have question related to `structured.py` module. Why this module is not in v1.0. It has fantastic methods for data. At least the medoths should be migrated to new modules as `add_datepart` migrated to `tabular` module. Am I missing anythig? Thanks.

**Comment by sgugger** [comment] 2019-04-08 13:04
You can always copy-paste the source code for the ones you are interested in. If you are really missing a feature that was there and you feel it's important, try to convert it to a tabular processor and make a PR out of it :)

Closing this issue in the meantime since there is no reproducible code for a bug/context.

**Closed by sgugger** 2019-04-08 13:04 UTC

**Comment by Santiago8888** [comment] 2019-11-17 07:27
For a newer implementation this might be what you are looking:
https://docs.fast.ai/tabular.html

Still figuring the details though.

**Comment by yatinarora7** [comment] 2020-05-15 09:13
> @koushikam it seems like you are using v1.0 fastai with old notebooks. You need to use v0.7 of fastai for this old ML1 course or you can copy old code for your function `train_cats` from here: https://github.com/fastai/fastai/blob/master/old/fastai/structured.py#L112.
> 
> But, I have question related to `structured.py` module. Why this module is not in v1.0. It has fantastic methods for data. At least the medoths should be migrated to new modules as `add_datepart` migrated to `tabular` module. Am I missing anythig? Thanks.

i agree with you , i am facing the same issue

**Comment by czlcaltech** [comment] 2021-01-01 08:33
the source code is:
def train_cats(df):
    """Change any columns of strings in a panda's dataframe to a column of
    categorical values. This applies the changes inplace.
    Parameters:
    -----------
    df: A pandas dataframe. Any columns of strings will be changed to
        categorical values.
    Examples:
    ---------
    >>> df = pd.DataFrame({'col1' : [1, 2, 3], 'col2' : ['a', 'b', 'a']})
    >>> df
       col1 col2
    0     1    a
    1     2    b
    2     3    a
    note the type of col2 is string
    >>> train_cats(df)
    >>> df
       col1 col2
    0     1    a
    1     2    b
    2     3    a
    now the type of col2 is category
    """
    for n,c in df.items():
        if is_string_dtype(c): df[n] = c.astype('category').cat.as_ordered()

def apply_cats(df, trn):
    """Changes any columns of strings in df into categorical variables using trn as
    a template for the category codes.
    Parameters:
    -----------
    df: A pandas dataframe. Any columns of strings will be changed to
        categorical values. The category codes are determined by trn.
    trn: A pandas dataframe. When creating a category for df, it looks up the
        what the category's code were in trn and makes those the category codes
        for df.
    Examples:
    ---------
    >>> df = pd.DataFrame({'col1' : [1, 2, 3], 'col2' : ['a', 'b', 'a']})
    >>> df
       col1 col2
    0     1    a
    1     2    b
    2     3    a
    note the type of col2 is string
    >>> train_cats(df)
    >>> df
       col1 col2
    0     1    a
    1     2    b
    2     3    a
    now the type of col2 is category {a : 1, b : 2}
    >>> df2 = pd.DataFrame({'col1' : [1, 2, 3], 'col2' : ['b', 'a', 'a']})
    >>> apply_cats(df2, df)
           col1 col2
        0     1    b
        1     2    a
        2     3    a
    now the type of col is category {a : 1, b : 2}
    """
    for n,c in df.items():
        if (n in trn.columns) and (trn[n].dtype.name=='category'):
            df[n] = c.astype('category').cat.as_ordered()
            df[n].cat.set_categories(trn[n].cat.categories, ordered=True, inplace=True)

and the website has been moved to 
https://github.com/fastai/fastai1/blob/master/old/fastai/structured.py

**Comment by Saad-Hussain31** [comment] 2021-04-03 22:20
where would I find source code of is_string_dtype()?
