### ISSUE TITLE
we need windows fastai v1.0

### ISSUE THREAD

**Issue by mengjiexu** [fastai/fastai#1315] opened 2018-12-09 09:26 UTC
the pytorch 1.0 stable has came yestday

**Comment by sgugger** [comment] 2018-12-09 17:36
Please be mindful that this is an open-source project. We know that pytorch v1 is out, we know Windows doesn't fully work with it (there are open issues and known bugs in the forum), and we will work on it at our pace in the next weeks.
Closing this in the meantime.

**Closed by sgugger** 2018-12-09 17:36 UTC

**Comment by stas00** [comment] 2018-12-09 18:14
And PRs to make fastai work better on windows are very welcome, @mengjiexu.

**Comment by EtienneT** [comment] 2019-01-27 03:42
Just wondering why this was closed?  I did the 2018 edition of the fastiai course on my windows machine and it worked great.  Anything we can do to make it work on windows?  Anything the community can do to help?

Thanks,

**Comment by sgugger** [comment] 2019-01-27 03:44
fastai 1 works fully on Windows, not sure why the problem is.

**Comment by EtienneT** [comment] 2019-01-27 03:58
Trying to run the course version 3 on my machine. [Link to my thread in the forums](https://forums.fast.ai/t/trying-to-run-lesson-1-on-windows/35985/2), but basically trying to run this line, the notebook start executing and never returns.  No error messages in the command line where the notebook was started.  The line in question from lesson 1 which is pretty basic:

learn = create_cnn(data, models.resnet34, metrics=error_rate)

**Comment by sgugger** [comment] 2019-01-27 04:11
I think you have an installation problem then. There's nothing even specific to windows in this line, but it may be the first time something is put on your GPU (here, the model).

**Comment by EtienneT** [comment] 2019-01-27 19:01
Thank you!  I spent all morning making this work.  I think my anaconda installation was broken because once I uninstalled anaconda and reisntalled everything it worked first shot...  The model seems to be training now, but I think it is using the CPU even though torch.cuda.is_available() returns true...  Why would that be?

![image](https://user-images.githubusercontent.com/265924/51805496-f2986800-223b-11e9-97e7-54bd56fa9d27.png)

**Comment by sgugger** [comment] 2019-01-27 20:07
Check manually the device of any parameter of the model (`one_param(learn.model).device`) if you're unsure, but the bottleneck might be the CPU (with loading images and applying data augmentation). I've read that the pytorch DataLoader isn't as efficient on Windows, which would probably only worsen that bottleneck.

**Comment by parthopdas** [comment] 2019-03-03 14:18
Fastai works well on Win10 + GPU. Here are the [informal instructions](https://github.com/parthopdas/c-fastai2019/blob/master/README.md).

Work is underway to formalize this, potentially into the fastai documentation itself. Please stay tuned.
