### ISSUE TITLE
Can't replicate results in Fastai

### ISSUE THREAD

**Issue by sebastienwood** [fastai/fastai#2139] opened 2019-06-03 18:09 UTC
**Describe the bug**
I'm trying to write up callbacks to run quantized networks using Fastai. I use as a baseline this Pytorch implementation that works really well : https://github.com/eghouti/BinaryConnect
However, using all the same parameters, optimizer, etc in Fastai my accuracy across a few runs struggle to reach 50% on CIFAR 10, while the baseline reach easily 90% in a rough dozen epochs. The loss saturate much quicker in Fastai.

**Provide your installation details**
```text
=== Software === 
python        : 3.7.3
fastai        : 1.0.52
fastprogress  : 0.1.21
torch         : 1.0.1
nvidia driver : 396.37
torch cuda    : 9.0.176 / is available
torch cudnn   : 7301 / is enabled

=== Hardware === 
nvidia gpus   : 4
torch devices : 4
  - gpu0      : 16280MB | Tesla P100-SXM2-16GB
  - gpu1      : 16280MB | Tesla P100-SXM2-16GB
  - gpu2      : 16280MB | Tesla P100-SXM2-16GB
  - gpu3      : 16280MB | Tesla P100-SXM2-16GB

=== Environment === 
platform      : Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
distro        : #1 SMP Thu Nov 29 14:49:43 UTC 2018
conda env     : base
python        : /users/henwood/anaconda3/bin/python
sys.path      : /users/henwood
/users/henwood/anaconda3/lib/python37.zip
/users/henwood/anaconda3/lib/python3.7
/users/henwood/anaconda3/lib/python3.7/lib-dynload
/users/henwood/anaconda3/lib/python3.7/site-packages
```

**To Reproduce**
I created a gist you can copy paste into a Jupyter Notebook : https://gist.github.com/sebastienwood/ac04d7296ecea9d3803fbd41038177f6

There is a part with the code from the baseline adapted for new version of Pytorch, and a part with Fastai. 

**Expected behavior**
Across a few tries, there should at least be one case of the Fastai implementation converging to the same level of performance as the raw Pytorch. However it can't manage to reach at least 50% accuracy. The loss is saturating much quicker.

**Additional context**
At the end of the 7th epoch, the raw Pytorch ususally has around 45% accuracy while the Fastai impl struggle to go past 25%.

Only difference there should be in the implementation are the transform : I used get_transforms() from Fastai while the Pytorch impl use reflected padding + random crop + random horizontal flip.

Using the proposed WRN or Fastai's WRN doesn't seem to bring any difference (same number of weights).

**Comment by sgugger** [comment] 2019-06-03 18:26
This way too broad for us to work with. I'm very happy to fix a bug with a small reproducible example (that works on one GPU), but this could come from any line of your re-implementation in fastai or be a deep problem on the library. If it's the latter it needs to be fixed, but you need to make the task a little bit easier on the maintainers and try to find which part has the problem by using exact same data/model/training loop in both cases and trying to find what create the problem. 

I'd suggest moving this on the forum to get help from the community, closing the issue in the meantime.

**Closed by sgugger** 2019-06-03 18:26 UTC

**Comment by sebastienwood** [comment] 2019-06-04 15:55
(sorry for the inconvenience if it's still not a good issue !)
After further debugging, it appears I have pinpointed the issue (while still not managing to solve it).

The optimizer step is not modifying the weights, thus rendering the network unable to learn. I have a modified MWE gist so has to show this issue (can be run on one GPU) : https://gist.github.com/sebastienwood/74ee9cd2013c0ce9cde2ccbc4ca949b0

The gist print detailed information on the models weights and grad, and show that they are indeed pointing to the weights and grad stored inside the callback function. It just seems that the step is not performed as the weights are not moving. I have applied the same printing information at multiple step of the callback process and the quantization to binary is working as intended. The grad are also moving on the print that is done on backward end. At one point, the grads are simply saturating to 0 themselves, yet the original weights are still here.

**Comment by sgugger** [comment] 2019-06-04 16:14
That suggests you are using parameters that are disconnected from the optimizer. Instead of looping over self.model.modules() to get them, maybe loop on the param groups `self.opt.param_groups()` then `param_group['params']`?

**Comment by sebastienwood** [comment] 2019-06-04 16:22
A further debugging : I tried to apply an on_train_begin like in fastai/fp16.py to reassign the optimizer.
`def on_train_begin(self, **kwargs:Any)->None:
        "Reinit the opt"
        print(self.learn.opt)
        new_opt = self.learn.opt.new_with_param(self.actual_params)
        self.learn.opt.opt = new_opt.opt`

2 weirds things are happening. First the print : 
`OptimWrapper over SGD (
Parameter Group 0
    dampening: 0
    lr: 0.003
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0005

Parameter Group 1
    dampening: 0
    lr: 0.003
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0005
).
True weight decay: False`

It seems the lr didn't take into account lr parameter of the line `opt_func = partial(optim.SGD, lr=0.1, momentum=0.9, nesterov = True)`. Second, a line later : 
`<ipython-input-13-814cb8ecfe83> in on_train_begin(self, **kwargs)
     36         "Reinit the opt"
     37         print(self.learn.opt)
---> 38         new_opt = self.learn.opt.new_with_param(self.actual_params)
     39         self.learn.opt.opt = new_opt.opt
     40 

TypeError: 'NoneType' object is not callable`.

**Comment by sebastienwood** [comment] 2019-06-04 16:22
> That suggests you are using parameters that are disconnected from the optimizer. Instead of looping over self.model.modules() to get them, maybe loop on the param groups `self.opt.param_groups()` then `param_group['params']`?

Just saw it, I'll try.

**Comment by sgugger** [comment] 2019-06-04 16:24
The lr is overwritten by defaults.lr or the learning rate you pass to fit.

**Comment by sebastienwood** [comment] 2019-06-04 17:28
After trying to use param_groups from self.opt, the results stays the same. Here is the code I used : 
    ```
def on_train_begin(self, **kwargs:Any)->None:
        "Reinit the opt and reassign the actual params pointer to the opt"
        for param_group in self.learn.opt.param_groups:
            for p in param_group['params']:
                for i in range(self.actual_params.__len__()):
                    if torch.equal(self.actual_params[i], p):
                        self.actual_params[i] = p
        #new_opt = self.learn.opt.new_with_params(self.actual_params)
        #self.learn.opt.opt = new_opt.opt
```
The comments part was also tried as an on off without success.

**Comment by sgugger** [comment] 2019-06-04 18:02
Yeah normally it just works because tensors are mutable. No idea why you get them disconnected from the optimizer here.

**Comment by sebastienwood** [comment] 2019-06-04 22:02
Another puzzle after further debugging, the grad of the params inside the optimizers are good at on_backward_end.

```
for param_group in self.learn.opt.param_groups:
            for p in param_group['params']:
                print(p.grad)
```

Following that I can safely conclude the issue is not that the tensors inside the opt are disconnected. To be sure, I did some sneaky dirty out of Fastai's callback spirit force-step and force-zero_grad:
```
for param_group in self.learn.opt.param_groups:
            for p in param_group['params']:
                print(p)
                print(p.grad)
                break
            break
        self.learn.opt.step()
        self.learn.opt.zero_grad()
        for param_group in self.learn.opt.param_groups:
            for p in param_group['params']:
                print(p)
                print(p.grad)
                break
            break
```
And it works really fine (finally !). Now the question is why the opt.step() and opt.zero_grad() are not performed. The original code works fine pointers speaking. As a proxy I'm performing self.learn.opt.step() and self.learn.opt.zero_grad() inside the on_backward_end callback.

I don't know if it's an unknown doc that I should PR asap, but feel free to let me know so I can do so ! 😆
