### ISSUE TITLE
markdown2html() missing 1 required positional argument: 'source'

### ISSUE THREAD

**Issue by bwanaaa** [fastai/fastai#2109] opened 2019-05-24 01:09 UTC
I installed fastAI in a conda environment specifically created for FastAI. FastAI was installed as per the instructions. Lesson1 of Fast AI gave an error with line 17

doc(interp.plot_top_losses)

gives

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-a7fe6964f6f7> in <module>
----> 1 doc(interp.plot_top_losses)

~/miniconda3/envs/p37cu10FastAI/lib/python3.7/site-packages/fastai/gen_doc/nbdoc.py in doc(elt)
    129     use_relative_links = False
    130     elt = getattr(elt, '__func__', elt)
--> 131     md = show_doc(elt, markdown=False)
    132     if is_fastai_class(elt):
    133         md += f'\n\n<a href="{get_fn_link(elt)}" target="_blank" rel="noreferrer noopener">Show in docs</a>'

~/miniconda3/envs/p37cu10FastAI/lib/python3.7/site-packages/fastai/gen_doc/nbdoc.py in show_doc(elt, doc_string, full_name, arg_comments, title_level, alt_doc_string, ignore_warn, markdown, show_tests)
    114     else: raise Exception(f'doc definition not supported for {full_name}')
    115     source_link = get_function_source(elt) if is_fastai_class(elt) else ""
--> 116     test_link, test_modal = get_pytest_html(elt, anchor_id=anchor_id) if show_tests else ('', '')
    117     title_level = ifnone(title_level, 2 if inspect.isclass(elt) else 4)
    118     doc =  f'<h{title_level} id="{anchor_id}" class="doc_header">{name}{source_link}{test_link}</h{title_level}>'

~/miniconda3/envs/p37cu10FastAI/lib/python3.7/site-packages/fastai/gen_doc/nbtest.py in get_pytest_html(elt, anchor_id)
     55 def get_pytest_html(elt, anchor_id:str)->Tuple[str,str]:
     56     md = build_tests_markdown(elt)
---> 57     html = HTMLExporter().markdown2html(md).replace('\n','') # nbconverter fails to parse markdown if it has both html and '\n'
     58     anchor_id = anchor_id.replace('.', '-') + '-pytest'
     59     link, body = get_pytest_card(html, anchor_id)

TypeError: markdown2html() missing 1 required positional argument: 'source'
```

=== Software === 
python        : 3.7.3
fastai        : 1.0.52
fastprogress  : 0.1.21
torch         : 1.1.0
nvidia driver : 418.56
torch cuda    : 10.0.130 / is available
torch cudnn   : 7501 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 12192MB | TITAN X (Pascal)

=== Environment === 
platform      : Linux-4.15.0-50-generic-x86_64-with-debian-buster-sid
distro        : #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019
conda env     : p37cu10FastAI
python        : /home/stefan/miniconda3/envs/p37cu10FastAI/bin/python
sys.path      : /home/stefan/Dropbox/aPython/aFastAI
/home/stefan/miniconda3/envs/p37cu10FastAI/lib/python37.zip
/home/stefan/miniconda3/envs/p37cu10FastAI/lib/python3.7
/home/stefan/miniconda3/envs/p37cu10FastAI/lib/python3.7/lib-dynload

/home/stefan/miniconda3/envs/p37cu10FastAI/lib/python3.7/site-packages
/home/stefan/miniconda3/envs/p37cu10FastAI/lib/python3.7/site-packages/IPython/extensions
/home/stefan/.ipython

I applied the changes listed here:

https://github.com/fastai/fastai/commit/21faa5d187b2cccf2a48315d183c2863ed2cdc50

by editing the the two files nbtest.py and nbdoc.py located at

~/miniconda3/pkgs/fastai-1.0.52-1/site-packages/fastai/gen_doc

Now i get this error:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-19-a7fe6964f6f7> in <module>
----> 1 doc(interp.plot_top_losses)

NameError: name 'doc' is not defined
```

**Comment by sgugger** [comment] 2019-05-24 04:19
This bug has been fixed in master. It will be in the next release. In the meantime you can either:
- do an editable install of master
or
- revert nbconvert to a version strictly before 5.5.0 (since the bug came for a change of API on their side)

**Closed by sgugger** 2019-05-24 04:19 UTC

**Comment by bwanaaa** [comment] 2019-05-28 02:59
How is this 
`do an editable install of master`

done? I thought in linux all files were editable. Isn't it enough to edit the files you mentioned in your patch here?

https://github.com/fastai/fastai/commit/21faa5d187b2cccf2a48315d183c2863ed2cdc50

**Comment by davidwyue** [comment] 2019-05-28 06:13
Previously used Conda install method to install which hit the same error with current release.

Confirmed workaround working when using the pip install method from master branch in test environment:

```
sudo apt-get purge nvidia*
sudo add-apt-repository ppa:graphics-drivers
sudo apt-get update

sudo apt-get install nvidia-driver-430 -y
sudo reboot

#Install Miniconda
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

# Install miniconda

conda install jupyterhub
conda install notebook

pip install git+https://github.com/fastai/fastai.git

sudo apt-get install nodejs
sudo npm install -g configurable-http-proxy

jupyterhub

```

**Comment by bwanaaa** [comment] 2019-05-29 00:58
@davidwyue

your solution stalls for me at this line
```

pip install git+https://github.com/fastai/fastai.git
Collecting git+https://github.com/fastai/fastai.git
  Cloning https://github.com/fastai/fastai.git to /tmp/pip-req-build-dglludhh
  Running command git clone -q https://github.com/fastai/fastai.git /tmp/pip-req-build-dglludhh
```
and the only thing inside the /tmp/pip-req-build-dglludhh is a .git folder
